pokermon.dex_order = {
  "bulbasaur",
  "ivysaur",
  { "venusaur", "mega_venusaur", "gmax_venusaur" },
  "charmander",
  "charmeleon",
  { "charizard", "mega_charizard_x", "mega_charizard_y", "gmax_charizard" },
  "squirtle",
  "wartortle",
  { "blastoise", "mega_blastoise", "gmax_blastoise" },
  "caterpie",
  "metapod",
  {"butterfree", "gmax_butterfree" },
  "weedle",
  "kakuna",
  { "beedrill", "mega_beedrill" },
  "pidgey",
  "pidgeotto",
  { "pidgeot", "mega_pidgeot" },
  { "rattata", "alolan_rattata" },
  { "raticate", "alolan_raticate" },
  "spearow",
  "fearow",
  "ekans",
  "arbok",
  { "pikachu", "gmax_pikachu" },
  { "raichu", "mega_raichu_x", "mega_raichu_y", "alolan_raichu" },
  { "sandshrew", "alolan_sandshrew" },
  { "sandslash", "alolan_sandslash" },
  "nidoranf",
  "nidorina",
  "nidoqueen",
  "nidoranm",
  "nidorino",
  "nidoking",
  "clefairy",
  { "clefable", "mega_clefable" },
  { "vulpix", "alolan_vulpix" },
  { "ninetales", "alolan_ninetales" },
  "jigglypuff",
  "wigglytuff",
  "zubat",
  "golbat",
  "oddish",
  "gloom",
  "vileplume",
  "paras",
  "parasect",
  "venonat",
  "venomoth",
  { "diglett", "alolan_diglett" },
  { "dugtrio", "alolan_dugtrio" },
  { "meowth", "alolan_meowth", "galarian_meowth", "gmax_meowth" },
  { "persian", "alolan_persian" },
  "psyduck",
  "golduck",
  "mankey",
  "primeape",
  { "growlithe", "hisuian_growlithe" },
  { "arcanine", "hisuian_arcanine" },
  "poliwag",
  "poliwhirl",
  "poliwrath",
  "abra",
  "kadabra",
  { "alakazam", "mega_alakazam" },
  "machop",
  "machoke",
  { "machamp", "gmax_machamp" },
  "bellsprout",
  "weepinbell",
  { "victreebel", "mega_victreebel" },
  "tentacool",
  "tentacruel",
  { "geodude", "alolan_geodude" },
  { "graveler", "alolan_graveler" },
  { "golem", "alolan_golem" },
  { "ponyta", "galarian_ponyta" },
  { "rapidash", "galarian_rapidash" },
  { "slowpoke", "galarian_slowpoke" },
  { "slowbro", "mega_slowbro", "galarian_slowbro" },
  "magnemite",
  "magneton",
  { "farfetchd", "galarian_farfetchd" },
  "doduo",
  "dodrio",
  "seel",
  "dewgong",
  { "grimer", "alolan_grimer" },
  { "muk", "alolan_muk" },
  "shellder",
  "cloyster",
  "gastly",
  "haunter",
  { "gengar", "mega_gengar", "gmax_gengar" },
  "onix",
  "drowzee",
  "hypno",
  "krabby",
  { "kingler", "gmax_kingler" },
  { "voltorb", "hisuian_voltorb" },
  { "electrode", "hisuian_electrode" },
  "exeggcute",
  { "exeggutor", "alolan_exeggutor" },
  "cubone",
  { "marowak", "alolan_marowak" },
  "hitmonlee",
  "hitmonchan",
  "lickitung",
  "koffing",
  { "weezing", "galarian_weezing" },
  "rhyhorn",
  "rhydon",
  "chansey",
  "tangela",
  { "kangaskhan", "mega_kangaskhan" },
  "horsea",
  "seadra",
  "goldeen",
  "seaking",
  "staryu",
  { "starmie", "mega_starmie" },
  { "mrmime", "galarian_mrmime" },
  "scyther",
  "jynx",
  "electabuzz",
  "magmar",
  { "pinsir", "mega_pinsir" },
  { "tauros", "paldean_tauros_combat", "paldean_tauros_blaze", "paldean_tauros_aqua" },
  "magikarp",
  { "gyarados", "mega_gyarados" },
  { "lapras", "gmax_lapras" },
  "ditto",
  { "eevee", "gmax_eevee" },
  "vaporeon",
  "jolteon",
  "flareon",
  "porygon",
  "omanyte",
  "omastar",
  "kabuto",
  "kabutops",
  { "aerodactyl", "mega_aerodactyl" },
  { "snorlax", "gmax_snorlax" },
  { "articuno", "galarian_articuno" },
  { "zapdos", "galarian_zapdos" },
  { "moltres", "galarian_moltres" },
  "dratini",
  "dragonair",
  { "dragonite", "mega_dragonite" },
  { "mewtwo", "mega_mewtwo_x", "mega_mewtwo_y" },
  "mew",
  "chikorita",
  "bayleef",
  { "meganium", "mega_meganium" },
  "cyndaquil",
  "quilava",
  { "typhlosion", "hisuian_typhlosion" },
  "totodile",
  "croconaw",
  { "feraligatr", "mega_feraligatr" },
  "sentret",
  "furret",
  "hoothoot",
  "noctowl",
  "ledyba",
  "ledian",
  "spinarak",
  "ariados",
  "crobat",
  "chinchou",
  "lanturn",
  "pichu",
  "cleffa",
  "igglybuff",
  "togepi",
  "togetic",
  "natu",
  "xatu",
  "mareep",
  "flaaffy",
  { "ampharos", "mega_ampharos" },
  "bellossom",
  "marill",
  "azumarill",
  "sudowoodo",
  "politoed",
  "hoppip",
  "skiploom",
  "jumpluff",
  "aipom",
  "sunkern",
  "sunflora",
  "yanma",
  { "wooper", "paldean_wooper" },
  "quagsire",
  "espeon",
  "umbreon",
  "murkrow",
  { "slowking", "galarian_slowking" },
  "misdreavus",
  "unown",
  "wobbuffet",
  "girafarig",
  "pineco",
  "forretress",
  "dunsparce",
  "gligar",
  { "steelix", "mega_steelix" },
  "snubbull",
  "granbull",
  { "qwilfish", "hisuian_qwilfish" },
  { "scizor", "mega_scizor" },
  "shuckle",
  { "heracross", "mega_heracross" },
  { "sneasel", "hisuian_sneasel" },
  "teddiursa",
  "ursaring",
  "slugma",
  "magcargo",
  "swinub",
  "piloswine",
  { "corsola", "galarian_corsola" },
  "remoraid",
  "octillery",
  "delibird",
  "mantine",
  { "skarmory", "mega_skarmory" },
  "houndour",
  { "houndoom", "mega_houndoom" },
  "kingdra",
  "phanpy",
  "donphan",
  "porygon2",
  "stantler",
  "smeargle",
  "tyrogue",
  "hitmontop",
  "smoochum",
  "elekid",
  "magby",
  "miltank",
  "blissey",
  "raikou",
  "entei",
  "suicune",
  "larvitar",
  "pupitar",
  { "tyranitar", "mega_tyranitar" },
  "lugia",
  { "ho-oh" },
  "celebi",
  "treecko",
  "grovyle",
  { "sceptile", "mega_sceptile" },
  "torchic",
  "combusken",
  { "blaziken", "mega_blaziken" },
  "mudkip",
  "marshtomp",
  { "swampert", "mega_swampert" },
  "poochyena",
  "mightyena",
  {"zigzagoon", "galarian_zigzagoon"},
  {"linoone", "galarian_linoone"},
  "wurmple",
  "silcoon",
  "beautifly",
  "cascoon",
  "dustox",
  "lotad",
  "lombre",
  "ludicolo",
  "seedot",
  "nuzleaf",
  "shiftry",
  "taillow",
  "swellow",
  "wingull",
  "pelipper",
  "ralts",
  "kirlia",
  { "gardevoir", "mega_gardevoir" },
  "surskit",
  "masquerain",
  "shroomish",
  "breloom",
  "slakoth",
  "vigoroth",
  "slaking",
  "nincada",
  "ninjask",
  "shedinja",
  "whismur",
  "loudred",
  "exploud",
  "makuhita",
  "hariyama",
  "azurill",
  "nosepass",
  "skitty",
  "delcatty",
  { "sableye", "mega_sableye" },
  { "mawile", "mega_mawile" },
  "aron",
  "lairon",
  { "aggron", "mega_aggron" },
  "meditite",
  { "medicham", "mega_medicham" },
  "electrike",
  { "manectric", "mega_manectric" },
  "plusle",
  "minun",
  "volbeat",
  "illumise",
  "roselia",
  "gulpin",
  "swalot",
  "carvanha",
  { "sharpedo", "mega_sharpedo" },
  "wailmer",
  "wailord",
  "numel",
  { "camerupt", "mega_camerupt" },
  "torkoal",
  "spoink",
  "grumpig",
  "spinda",
  "trapinch",
  "vibrava",
  "flygon",
  "cacnea",
  "cacturne",
  "swablu",
  { "altaria", "mega_altaria" },
  "zangoose",
  "seviper",
  "lunatone",
  "solrock",
  "barboach",
  "whiscash",
  "corphish",
  "crawdaunt",
  "baltoy",
  "claydol",
  "lileep",
  "cradily",
  "anorith",
  "armaldo",
  "feebas",
  "milotic",
  "castform",
  "kecleon",
  "shuppet",
  { "banette", "mega_banette" },
  "duskull",
  "dusclops",
  "tropius",
  "chimecho",
  { "absol", "mega_absol" },
  "wynaut",
  "snorunt",
  { "glalie", "mega_glalie" },
  "spheal",
  "sealeo",
  "walrein",
  "clamperl",
  "huntail",
  "gorebyss",
  "relicanth",
  "luvdisc",
  "bagon",
  "shelgon",
  { "salamence", "mega_salamence" },
  "beldum",
  "metang",
  { "metagross", "mega_metagross" },
  "regirock",
  "regice",
  "registeel",
  { "latias", "mega_latias" },
  { "latios", "mega_latios" },
  { "kyogre", "primal_kyogre" },
  { "groudon", "primal_groudon" },
  { "rayquaza", "mega_rayquaza" },
  { "jirachi", "jirachi_banker", "jirachi_booster", "jirachi_invis", "jirachi_copy", "jirachi_negging", "jirachi_power", "jirachi_fixer" },
  { "deoxys", "deoxys_attack", "deoxys_defense", "deoxys_speed" },
  "turtwig",
  "grotle",
  "torterra",
  "chimchar",
  "monferno",
  "infernape",
  "piplup",
  "prinplup",
  "empoleon",
  "starly",
  "staravia",
  "staraptor",
  "bidoof",
  "bibarel",
  "kricketot",
  "kricketune",
  "shinx",
  "luxio",
  "luxray",
  "budew",
  "roserade",
  "cranidos",
  "rampardos",
  "shieldon",
  "bastiodon",
  "burmy",
  "wormadam",
  "mothim",
  "combee",
  "vespiquen",
  "pachirisu",
  "buizel",
  "floatzel",
  "cherubi",
  "cherrim",
  "shellos",
  "gastrodon",
  "ambipom",
  "drifloon",
  "drifblim",
  "buneary",
  { "lopunny", "mega_lopunny" },
  "mismagius",
  "honchkrow",
  "glameow",
  "purugly",
  "chingling",
  "stunky",
  "skuntank",
  "bronzor",
  "bronzong",
  "bonsly",
  "mimejr",
  "happiny",
  "chatot",
  "spiritomb",
  "gible",
  "gabite",
  { "garchomp", "mega_garchomp" },
  "munchlax",
  "riolu",
  { "lucario", "mega_lucario" },
  "hippopotas",
  "hippowdon",
  "skorupi",
  "drapion",
  "croagunk",
  "toxicroak",
  "carnivine",
  "finneon",
  "lumineon",
  "mantyke",
  "snover",
  { "abomasnow", "mega_abomasnow" },
  "weavile",
  "magnezone",
  "lickilicky",
  "rhyperior",
  "tangrowth",
  "electivire",
  "magmortar",
  "togekiss",
  "yanmega",
  "leafeon",
  "glaceon",
  "gliscor",
  "mamoswine",
  "porygonz",
  { "gallade", "mega_gallade" },
  "probopass",
  "dusknoir",
  { "froslass", "mega_froslass" },
  { "rotom", "rotomh", "rotomw", "rotomf", "rotomfan", "rotomm" },
  "uxie",
  "mesprit",
  "azelf",
  "dialga",
  "palkia",
  "heatran",
  "regigigas",
  "giratina",
  "cresselia",
  "phione",
  "manaphy",
  "darkrai",
  { "shaymin", "shaymin_sky" },
  "arceus",
  "victini",
  "snivy",
  "servine",
  "serperior",
  "tepig",
  "pignite",
  { "emboar", "mega_emboar" },
  "oshawott",
  "dewott",
  { "samurott", "hisuian_samurott" },
  "patrat",
  "watchog",
  "lillipup",
  "herdier",
  "stoutland",
  "purrloin",
  "liepard",
  "pansage",
  "simisage",
  "pansear",
  "simisear",
  "panpour",
  "simipour",
  "munna",
  "musharna",
  "pidove",
  "tranquill",
  "unfezant",
  "blitzle",
  "zebstrika",
  "roggenrola",
  "boldore",
  "gigalith",
  "woobat",
  "swoobat",
  "drilbur",
  { "excadrill", "mega_excadrill" },
  { "audino", "mega_audino" },
  "timburr",
  "gurdurr",
  "conkeldurr",
  "tympole",
  "palpitoad",
  "seismitoad",
  "throh",
  "sawk",
  "sewaddle",
  "swadloon",
  "leavanny",
  "venipede",
  "whirlipede",
  { "scolipede", "mega_scolipede" },
  "cottonee",
  "whimsicott",
  "petilil",
  { "lilligant", "hisuian_lilligant" },
  "basculin",
  "sandile",
  "krokorok",
  "krookodile",
  { "darumaka", "galarian_darumaka" },
  { "darmanitan", "darmanitan_zen", "galarian_darmantian", "galarian_darmanitan_zen" },
  "maractus",
  "dwebble",
  "crustle",
  "scraggy",
  { "scrafty", "mega_scrafty" },
  "sigilyph",
  { "yamask", "galarian_yamask" },
  "cofagrigus",
  "tirtouga",
  "carracosta",
  "archen",
  "archeops",
  "trubbish",
  { "garbodor", "gmax_garbodor" },
  { "zorua", "hisuian_zorua" },
  { "zoroark", "hisuian_zoroark" },
  "minccino",
  "cinccino",
  "gothita",
  "gothorita",
  "gothitelle",
  "solosis",
  "duosion",
  "reuniclus",
  "ducklett",
  "swanna",
  "vanillite",
  "vanillish",
  "vanilluxe",
  "deerling",
  "sawsbuck",
  "emolga",
  "karrablast",
  "escavalier",
  "foongus",
  "amoonguss",
  "frillish",
  "jellicent",
  "alomomola",
  "joltik",
  "galvantula",
  "ferroseed",
  "ferrothorn",
  "klink",
  "klang",
  "klinklang",
  "tynamo",
  "eelektrik",
  { "eelektross", "mega_eelektross" },
  "elgyem",
  "beheeyem",
  "litwick",
  "lampent",
  { "chandelure", "mega_chandelure" },
  "axew",
  "fraxure",
  "haxorus",
  "cubchoo",
  "beartic",
  "cryogonal",
  "shelmet",
  "accelgor",
  { "stunfisk", "galarian_stunfisk" },
  "mienfoo",
  "mienshao",
  "druddigon",
  "golett",
  "golurk",
  "pawniard",
  "bisharp",
  "bouffalant",
  "rufflet",
  { "braviary", "hisuian_braviary" },
  "vullaby",
  "mandibuzz",
  "heatmor",
  "durant",
  "deino",
  "zweilous",
  "hydreigon",
  "larvesta",
  "volcarona",
  "cobalion",
  "terrakion",
  "virizion",
  { "tornadus", "tornadus_therian" },
  { "thundurus", "thundurus_therian" },
  "reshiram",
  "zekrom",
  { "landorus", "landorus_therian" },
  { "kyurem", "kyurem_white", "kyurem_black" },
  { "keldeo", "keldeo_resolute" },
  { "meloetta", "meloetta_pirouette" },
  "genesect",
  "chespin",
  "quilladin",
  { "chesnaught", "mega_chesnaught" },
  "fennekin",
  "braixen",
  { "delphox", "mega_delphox" },
  "froakie",
  "frogadier",
  { "greninja", "mega_greninja", "greninja_ash" },
  "bunnelby",
  "diggersby",
  "fletchling",
  "fletchinder",
  "talonflame",
  "scatterbug",
  "spewpa",
  "vivillon",
  "litleo",
  { "pyroar", "mega_pyroar" },
  "flabebe",
  { "floette", "floette_eternal", "mega_floette_eternal" },
  "florges",
  "skiddo",
  "gogoat",
  "pancham",
  "pangoro",
  "furfrou",
  "espurr",
  "meowstic",
  "honedge",
  "doublade",
  "aegislash",
  "spritzee",
  "aromatisse",
  "swirlix",
  "slurpuff",
  "inkay",
  { "malamar", "mega_malamar" },
  "binacle",
  { "barbaracle", "mega_barbaracle" },
  "skrelp",
  { "dragalge", "mega_dragalge" },
  "clauncher",
  "clawitzer",
  "helioptile",
  "heliolisk",
  "tyrunt",
  "tyrantrum",
  "amaura",
  "aurorus",
  "sylveon",
  { "hawlucha", "mega_hawlucha" },
  "dedenne",
  "carbink",
  "goomy",
  { "sliggoo", "hisuian_sliggoo" },
  { "goodra", "hisuian_goodra" },
  "klefki",
  "phantump",
  "trevenant",
  "pumpkaboo",
  "gourgeist",
  "bergmite",
  { "avalugg", "hisuian_avalugg" },
  "noibat",
  "noivern",
  "xerneas",
  "yveltal",
  { "zygarde_10", "zygarde_50", "zygarde_complete", "mega_zygarde_complete" },
  { "diancie", "mega_diancie" },
  "hoopa",
  "volcanion",
  "rowlet",
  "dartrix",
  { "decidueye", "hisuian_decidueye" },
  "litten",
  "torracat",
  "incineroar",
  "popplio",
  "brionne",
  "primarina",
  "pikipek",
  "trumbeak",
  "toucannon",
  "yungoos",
  "gumshoos",
  "grubbin",
  "charjabug",
  "vikavolt",
  "crabrawler",
  "crabominable",
  { "oricorio_baile", "oricorio_pompom", "oricorio_pau", "oricorio_sensu" },
  "cutiefly",
  "ribombee",
  "rockruff",
  { "lycanroc_day", "lycanroc_night", "lycanroc_dusk" },
  { "wishiwashi", "wishiwashi_school" },
  "mareanie",
  "toxapex",
  "mudbray",
  "mudsdale",
  "dewpider",
  "araquanid",
  "fomantis",
  "lurantis",
  "morelull",
  "shiinotic",
  "salandit",
  "salazzle",
  "stufful",
  "bewear",
  "bounsweet",
  "steenee",
  "tsareena",
  "comfey",
  "oranguru",
  "passimian",
  "wimpod",
  "golisopod",
  "sandygast",
  "palossand",
  "pyukumuku",
  "type_null",
  "silvally",
  "minior",
  "komala",
  "turtonator",
  "togedemaru",
  "mimikyu",
  "bruxish",
  { "drampa", "mega_drampa" },
  "dhelmise",
  "jangmoo",
  "hakamoo",
  "kommoo",
  "tapu_koko",
  "tapu_lele",
  "tapu_bulu",
  "tapu_fini",
  "cosmog",
  "cosmoem",
  "solgaleo",
  "lunala",
  "nihilego",
  "buzzwole",
  "pheromosa",
  "xurkitree",
  "celesteela",
  "kartana",
  "guzzlord",
  { "necrozma", "necrozma_dusk", "necrozma_dawn", "ultra_necrozma" },
  "magearna",
  "marshadow",
  "poipole",
  "naganadel",
  "stakataka",
  "blacephalon",
  "zeraora",
  "meltan",
  { "melmetal", "gmax_melmetal" },
  "grookey",
  "thwackey",
  { "rillaboom", "gmax_rillaboom" },
  "scorbunny",
  "raboot",
  { "cinderace", "gmax_cinderace" },
  "sobble",
  "drizzile",
  { "inteleon", "gmax_inteleon" },
  "skwovet",
  "greedent",
  "rookidee",
  "corvisquire",
  { "corviknight", "gmax_corviknight" },
  "blipbug",
  "dottler",
  { "orbeetle", "gmax_orbeetle" },
  "nickit",
  "thievul",
  "gossifleur",
  "eldegoss",
  "wooloo",
  "dubwool",
  "chewtle",
  { "drednaw", "gmax_drednaw" },
  "yamper",
  "boltund",
  "rolycoly",
  "carkol",
  { "coalossal", "gmax_coalossal" },
  "applin",
  { "flapple", "gmax_flapple" },
  { "appletun", "gmax_appletun" },
  "silicobra",
  { "sandaconda", "gmax_sandaconda" },
  "cramorant",
  "arrokuda",
  "barraskewda",
  "toxel",
  { "toxtricity", "gmax_toxtricity" },
  "sizzlipede",
  { "centiskorch", "gmax_centiskorch" },
  "clobbopus",
  "grapploct",
  "sinistea",
  "polteageist",
  "hatenna",
  "hattrem",
  { "hatterene", "gmax_hatterene" },
  "impidimp",
  "morgrem",
  { "grimmsnarl", "gmax_grimmsnarl" },
  "obstagoon",
  "perrserker",
  "cursola",
  "sirfetchd",
  "mrrime",
  "runerigus",
  "milcery",
  { "alcremie", "alcremie_berry", "alcremie_love", "alcremie_star", "alcremie_clover", "alcremie_flower", "alcremie_ribbon" },
  { "falinks", "mega_falinks" },
  "pincurchin",
  "snom",
  "frosmoth",
  "stonjourner",
  "eiscue",
  { "indeedee_f", "indeedee_m" },
  "morpeko",
  "cufant",
  { "copperajah", "gmax_copperajah" },
  "dracozolt",
  "arctozolt",
  "dracovish",
  "arctovish",
  { "duraludon", "gmax_duraludon" },
  "dreepy",
  "drakloak",
  "dragapult",
  "zacian",
  "zamazenta",
  "eternatus",
  "kubfu",
  { "urshifu_single_strike", "urshifu_rapid_strike", "gmax_urshifu_single_strike", "gmax_urshifu_rapid_strike" },
  "zarude",
  "regieleki",
  "regidrago",
  "glastrier",
  "spectrier",
  { "calyrex", "calyrex_ice", "calyrex_shadow" },
  "wyrdeer",
  "kleavor",
  { "ursaluna", "bloodmoon_ursaluna" },
  "basculegion",
  "sneasler",
  "overqwil",
  { "enamorus", "enamorus_therian" },
  "sprigatito",
  "floragato",
  "meowscarada",
  "fuecoco",
  "crocalor",
  "skeledirge",
  "quaxly",
  "quaxwell",
  "quaquaval",
  "lechonk",
  "oinkologne",
  "tarountula",
  "spidops",
  "nymble",
  "lokix",
  "pawmi",
  "pawmo",
  "pawmot",
  "tandemaus",
  "maushold",
  "fidough",
  "dachsbun",
  "smoliv",
  "dolliv",
  "arboliva",
  "squawkabilly",
  "nacli",
  "naclstack",
  "garganacl",
  "charcadet",
  "armarouge",
  "ceruledge",
  "tadbulb",
  "bellibolt",
  "wattrel",
  "kilowattrel",
  "maschiff",
  "mabosstiff",
  "shroodle",
  "grafaiai",
  "bramblin",
  "brambleghast",
  "toedscool",
  "toedscruel",
  "klawf",
  "capsakid",
  "scovillain",
  "rellor",
  "rabsca",
  "flittle",
  "espathra",
  "tinkatink",
  "tinkatuff",
  "tinkaton",
  "wiglett",
  "wugtrio",
  "bombirdier",
  "finizen",
  { "palafin", "palafin_hero" },
  "varoom",
  "revavroom",
  "cyclizar",
  "orthworm",
  "glimmet",
  "glimmora",
  "greavard",
  "houndstone",
  "flamigo",
  "cetoddle",
  "cetitan",
  "veluza",
  "dondozo",
  "tatsugiri",
  "annihilape",
  "clodsire",
  "farigiraf",
  "dudunsparce",
  "kingambit",
  "great_tusk",
  "scream_tail",
  "brute_bonnet",
  "flutter_mane",
  "slither_wing",
  "sandy_shocks",
  "iron_treads",
  "iron_bundle",
  "iron_hands",
  "iron_jugulis",
  "iron_moth",
  "iron_thorns",
  "frigibax",
  "arctibax",
  "baxcalibur",
  "gimmighoul",
  "gholdengo",
  "wo_chien",
  "chien_pao",
  "ting_lu",
  "chi_yu",
  "roaring_moon",
  "iron_valiant",
  "koraidon",
  "miraidon",
  "walking_wake",
  "iron_leaves",
  "dipplin",
  "poltchageist",
  "sinistcha",
  "okidogi",
  "munkidori",
  "fezandipiti",
  { "ogerpon", "ogerpon_wellspring", "ogerpon_hearthflame", "ogerpon_cornerstone" },
  "archaludon",
  "hydrapple",
  "gouging_fire",
  "raging_bolt",
  "iron_boulder",
  "iron_crown",
  { "terapagos", "terapagos_terastal", "terapagos_stellar" },
  "pecharunt",
  "missingno",
}