local energizable_vanilla = {
  -- j_joker=            set = "Joker", effect = "Mult", cost_mult = 1.0, config = {mult = 4},
  ["Joker"] = {"mult", "mult"},
  -- j_greedy_joker=     set = "Joker", effect = "Suit Mult", cost_mult = 1.0, config = {extra = {s_mult = 3, suit = 'Diamonds'}},
  ["Greedy Joker"] = {"mult_mod", "s_mult"},
  -- j_lusty_joker=      set = "Joker", effect = "Suit Mult", cost_mult = 1.0, config = {extra = {s_mult = 3, suit = 'Hearts'}}},
  ["Lusty Joker"] = {"mult_mod", "s_mult"},
  -- j_wrathful_joker=   set = "Joker", effect = "Suit Mult", cost_mult = 1.0, config = {extra = {s_mult = 3, suit = 'Spades'}}},
  ["Wrathful Joker"] = {"mult_mod", "s_mult"},
  -- j_gluttenous_joker= set = "Joker", effect = "Suit Mult", cost_mult = 1.0, config = {extra = {s_mult = 3, suit = 'Clubs'}}},
  ["Gluttonous Joker"] = {"mult_mod", "s_mult"},
  -- j_jolly=            set = "Joker", effect = "Type Mult", cost_mult = 1.0, config = {t_mult = 8, type = 'Pair'}},
  ["Jolly Joker"] = {"mult", "t_mult"},
  -- j_zany=             set = "Joker", effect = "Type Mult", cost_mult = 1.0, config = {t_mult = 12, type = 'Three of a Kind'}},
  ["Zany Joker"] = {"mult", "t_mult"},
  -- j_mad=              set = "Joker", effect = "Type Mult", cost_mult = 1.0, config = {t_mult = 10, type = 'Two Pair'}},
  ["Mad Joker"] = {"mult", "t_mult"},
  -- j_crazy=            set = "Joker", effect = "Type Mult", cost_mult = 1.0, config = {t_mult = 12, type = 'Straight'}},
  ["Crazy Joker"] = {"mult", "t_mult"},
  -- j_droll=            set = "Joker", effect = "Type Mult", cost_mult = 1.0, config = {t_mult = 10, type = 'Flush'}},
  ["Droll Joker"] = {"mult", "t_mult"},
  -- j_sly=              set = "Joker", config = {t_chips = 50, type = 'Pair'},
  ["Sly Joker"] = {"chips", "t_chips"},
  -- j_wily=             set = "Joker", config = {t_chips = 100, type = 'Three of a Kind'},
  ["Wily Joker"] = {"chips", "t_chips"},
  -- j_clever=           set = "Joker", config = {t_chips = 80, type = 'Two Pair'},
  ["Clever Joker"] = {"chips", "t_chips"},
  -- j_devious=          set = "Joker", config = {t_chips = 100, type = 'Straight'},
  ["Devious Joker"] = {"chips", "t_chips"},
  -- j_crafty=           set = "Joker", config = {t_chips = 80, type = 'Flush'},
  ["Crafty Joker"] = {"chips", "t_chips"},
  -- j_half=             set = "Joker", effect = "Hand Size Mult", cost_mult = 1.0, config = {extra = {mult = 20, size = 3}}},
  ["Half Joker"] = {"mult", "mult"},
  -- j_stencil=          set = "Joker", effect = "Hand Size Mult", cost_mult = 1.0, config = {}},
    -- ["Joker Stencil"] = {"Xmult", nil}, -- Joker Stencil is hardcoded

  -- j_ceremonial=       set = "Joker", effect = "", config = {mult = 0}},
  -- ["Ceremonial Dagger"] = {"mult", "mult"}, -- Ceremonial dagger doesn't quite work out, although it maybe could if the sell values weren't hardcoded

  -- j_banner=           set = "Joker", effect = "Discard Chips", cost_mult = 1.0, config = {extra = 30}},
  ["Banner"] = {"chip_mod", "extra"},
  -- j_mystic_summit=    set = "Joker", effect = "No Discard Mult", cost_mult = 1.0, config = {extra = {mult = 15, d_remaining = 0}}},
  ["Mystic Summit"] = {"mult", "mult"},
  -- j_loyalty_card=     set = "Joker", effect = "1 in 10 mult", cost_mult = 1.0, config = {extra = {Xmult = 4, every = 5, remaining = "5 remaining"}}},
  ["Loyalty Card"] = {"Xmult", "Xmult"},
  -- j_misprint=         set = "Joker", effect = "Random Mult", cost_mult = 1.0, config = {extra = {max = 23, min = 0}}},
  ["Misprint"] = {"mult", "max"},
  -- j_raised_fist=      set = "Joker", effect = "Socialized Mult", cost_mult = 1.0, config = {}},
    -- ["Raised Fist"] = {"mult_mod", nil}, -- Raised Fist is hardcoded

  -- j_fibonacci=        set = "Joker", effect = "Card Mult", cost_mult = 1.0, config = {extra = 8}},
  ["Fibonacci"] = {"mult_mod", "extra"},
  -- j_steel_joker=      set = "Joker", effect = "Steel Card Buff", cost_mult = 1.0, config = {extra = 0.2}, enhancement_gate = 'm_steel'},
  ["Steel Joker"] = {"Xmult_mod", "extra"},
  -- j_scary_face=       set = "Joker", effect = "Scary Face Cards", cost_mult = 1.0, config = {extra = 30}},
  ["Scary Face"] = {"chip_mod", "extra"},
  -- j_abstract=         set = "Joker", effect = "Joker Mult", cost_mult = 1.0, config = {extra = 3}},
  ["Abstract Joker"] = {"mult_mod", "extra"},
  -- j_delayed_grat=     set = "Joker", effect = "Discard dollars", cost_mult = 1.0, config = {extra = 2}},
  ["Delayed Gratification"] = {"money", "extra"},
  -- j_gros_michel=      set = "Joker", effect = "", config = {extra = {odds = 6, mult = 15}}, no_pool_flag = 'gros_michel_extinct'},
  ["Gros Michel"] = {"mult", "mult"},
  -- j_even_steven=      set = "Joker", effect = "Even Card Buff", cost_mult = 1.0, config = {extra = 4}},
  ["Even Steven"] = {"mult_mod", "extra"},
  -- j_odd_todd=         set = "Joker", effect = "Odd Card Buff", cost_mult = 1.0, config = {extra = 31}},
  ["Odd Todd"] = {"chip_mod", "extra"},
  -- j_scholar=          set = "Joker", effect = "Ace Buff", cost_mult = 1.0, config = {extra = {mult = 4, chips = 20}}},
  ["Scholar"] = {"mult_mod", "mult", {field = "chip_mod", value = "chips"}},
  -- j_business=         set = "Joker", effect = "Face Card dollar Chance", cost_mult = 1.0, config = {extra = 2}},
    -- ["Business Card"] = {"money_mod", nil}, -- Business card is hardcoded

  -- j_supernova=        set = "Joker", effect = "Hand played mult", cost_mult = 1.0, config = {extra = 1}},
  ["Supernova"] = {"mult_mod", "extra"},
  -- j_ride_the_bus=     set = "Joker", effect = "", config = {extra = 1}, unlock_condition = {type = 'discard_custom'}},
  ["Ride the Bus"] = {"mult_mod", "extra"},
  -- j_egg=              set = 'Joker', config = {extra = 3}},
  ["Egg"] = {"money", "extra"},
  -- j_blackboard=       set = 'Joker', config = {extra = 3}},
  ["Blackboard"] = {"Xmult", "extra"},
  -- j_runner=           set = 'Joker', config = {extra = {chips = 0, chip_mod = 15}}},
  ["Runner"] = {"chip_mod", "chip_mod", {field = "chip_mod", value = "chips"}},
  -- j_ice_cream=        set = 'Joker', config = {extra = {chips = 100, chip_mod = 5}}},
  ["Ice Cream"] = {"chips", "chips"},
  -- j_blue_joker=       set = 'Joker', config = {extra = 2}},
  ["Blue Joker"] = {"chip_mod", "extra"},
  -- j_constellation=    set = 'Joker', config = {extra = 0.1, Xmult = 1}},
  ["Constellation"] = {"Xmult_mod", "extra"},
  -- j_hiker=            set = 'Joker', config = {extra = 5}},
  ["Hiker"] = {"chip_mod", "extra"},
  -- j_faceless=         set = 'Joker', config = {extra = {dollars = 5, faces = 3}}},
  ["Faceless Joker"] = {"money", "dollars"},
  -- j_green_joker=      set = 'Joker', config = {extra = {hand_add = 1, discard_sub = 1}}},
  ["Green Joker"] = {"mult_mod", "hand_add"},
  -- j_todo_list=        set = 'Joker', config = {extra = {dollars = 4, poker_hand = 'High Card'}}},
  ["To Do List"] = {"money", "dollars"},
  -- j_cavendish=        set = "Joker", cost_mult = 1.0, config = {extra = {odds = 1000, Xmult = 3}},
  ["Cavendish"] = {"Xmult", "Xmult"},
  -- j_card_sharp=       set = "Joker", cost_mult = 1.0, config = {extra = {Xmult = 3}}},
  ["Card Sharp"] = {"Xmult", "Xmult"},
  -- j_red_card=         set = "Joker", cost_mult = 1.0, config = {extra = 3}},
  ["Red Card"] = {"mult_mod", "extra"},
  -- j_madness=          set = "Joker", cost_mult = 1.0, config = {extra = 0.5}},
  ["Madness"] = {"Xmult_mod", "extra"},
  -- j_square=           set = "Joker", cost_mult = 1.0, config = {extra = {chips = 0, chip_mod = 4}}},
  ["Square Joker"] = {"chip_mod", "chip_mod", {field = "chip_mod", value = "chips"}},
  -- j_vampire=          set = "Joker", config = {extra = 0.1, Xmult = 1},  
  ["Vampire"] = {"Xmult_mod", "extra"},
  -- j_hologram=         set = "Joker", config = {extra = 0.25, Xmult = 1}, 
  ["Hologram"] = {"Xmult_mod", "extra"},
  -- j_baron=            set = "Joker", config = {extra = 1.5},
  ["Baron"] = {"Xmult_mod", "extra"},
  -- j_cloud_9=          set = "Joker", config = {extra = 1},
  ["Cloud 9"] = {"money", "extra"},
  -- j_rocket=           set = "Joker", config = {extra = {dollars = 1, increase = 2}},
  ["Rocket"] = {"money", "dollars", {field = "money", value = "increase"}},
  -- j_obelisk=          set = "Joker", config = {extra = 0.2, Xmult = 1},
  ["Obelisk"] = {"Xmult_mod", "extra"},
  -- j_photograph=       set = "Joker", config = {extra = 2},
  ["Photograph"] = {"Xmult_mod", "extra"},
  -- j_gift=             set = "Joker", config = {extra = 1},
  ["Gift Card"] = {"money", "extra"},
  -- j_erosion=          set = "Joker", config = {extra = 4},
  ["Erosion"] = {"mult_mod", "extra"},
  -- j_reserved_parking= set = "Joker", config = {extra = {odds = 2, dollars = 1}},
  ["Reserved Parking"] = {"money_mod", "dollars"},
  -- j_mail=             set = "Joker", config = {extra = 5},
  ["Mail-In Rebate"] = {"money_mod", "extra"},
  -- j_to_the_moon=      set = "Joker", config = {extra = 1},
  ["To the Moon"] = {"money_mod", "extra"},
  -- j_fortune_teller=   set = "Joker", effect = "", config = {extra = 1}},
  ["Fortune Teller"] = {"mult_mod", "extra"},
  -- j_stone=            set = "Joker", effect = "Stone Card Buff", cost_mult = 1.0, config = {extra = 25},
  ["Stone Joker"] = {"chip_mod", "extra"},
  -- j_golden=           set = "Joker", effect = "Bonus dollars", cost_mult = 1.0, config = {extra = 4}},
  ["Golden Joker"] = {"money", "extra"},
  -- j_lucky_cat=        set = "Joker", config = {Xmult = 1, extra = 0.25},
  ["Lucky Cat"] = {"Xmult_mod", "extra"},
  -- j_baseball=         set = "Joker", config = {extra = 1.5},
  ["Baseball Card"] = {"Xmult_mod", "extra"},
  -- j_bull=             set = "Joker", config = {extra = 2},
  ["Bull"] = {"chip_mod", "extra"},
  -- j_trading=          set = "Joker", config = {extra = 3}
  ["Trading Card"] = {"money", "extra"},
  -- j_flash=            set = "Joker", config = {extra = 2, mult = 0}
  ["Flash Card"] = {"mult_mod", "extra"},
  -- j_popcorn=          set = "Joker", config = {mult = 20, extra = 4}, pos = {x=1,y=15}},
  ["Popcorn"] = {"mult", "mult"},
  -- j_trousers=         set = "Joker", config = {extra = 2},
  ["Spare Trousers"] = {"mult_mod", "extra"},
  -- j_ancient=          set = "Joker", config = {extra = 1.5},
  ["Ancient Joker"] = {"Xmult_mod", "extra"},
  -- j_ramen=            set = "Joker", config = {Xmult = 2, extra = 0.01},
    -- Ramen gets covered by the default case

  -- j_walkie_talkie=    set = "Joker", config = {extra = {chips = 10, mult = 4}},
  ["Walkie Talkie"] = {"mult_mod", "mult", {field = "chip_mod", value = "chips"}},
  -- j_castle=           set = "Joker", config = {extra = {chips = 0, chip_mod = 3}},
  ["Castle"] = {"chip_mod", "chip_mod"},
  -- j_smiley=           set = "Joker", config = {extra = 5}, pos = {x=6,y=15}},
  ["Smiley Face"] = {"mult_mod", "extra"},
  -- j_campfire=         set = "Joker", config = {extra = 0.25},
  ["Campfire"] = {"Xmult_mod", "extra"},
  -- j_ticket=           set = "Joker", effect = "dollars for Gold cards", cost_mult = 1.0, config = {extra = 4},
  ["Golden Ticket"] = {"money_mod", "extra"},
  -- j_acrobat=          set = "Joker", effect = "Shop size", cost_mult = 1.0, config = {extra = 3},
  ["Acrobat"] = {"Xmult", "extra"},
  -- j_swashbuckler=     set = "Joker", effect = "Set Mult", cost_mult = 1.0, config = {mult = 1},
  ["Swashbuckler"] = {"mult", "mult"},
  -- j_throwback=        set = "Joker", effect = "", config = {extra = 0.25},
  ["Throwback"] = {"Xmult_mod", "extra"},
  -- j_rough_gem=        set = "Joker", effect = "", config = {extra = 1},
  ["Rough Gem"] = {"money_mod", "extra"},
  -- j_bloodstone=       set = "Joker", effect = "", config = {extra = {odds = 2, Xmult = 1.5}},
  ["Bloodstone"] = {"Xmult_mod", "Xmult"},
  -- j_arrowhead=        set = "Joker", effect = "", config = {extra = 50},
  ["Arrowhead"] = {"chip_mod", "extra"},
  -- j_onyx_agate=       set = "Joker", effect = "", config = {extra = 7},
  ["Onyx Agate"] = {"mult_mod", "extra"},
  -- j_glass=            set = "Joker", effect = "Glass Card", cost_mult = 1.0, config = {extra = 0.75, Xmult = 1},
  ["Glass Joker"] = {"Xmult_mod", "extra"},
  -- j_flower_pot=       set = "Joker", effect = "", config = {extra = 3},
  ["Flower Pot"] = {"Xmult", "extra"},
  -- j_wee=              set = "Joker", effect = "", config = {extra = {chips = 0, chip_mod = 8}},
  ["Wee Joker"] = {"chip_mod", "chip_mod"},
  -- j_idol=             set = "Joker", effect = "", config = {extra = 2},
  ["The Idol"] = {"Xmult_mod", "extra"},
  -- j_seeing_double=    set = "Joker", effect = "X1.5 Mult club 7", cost_mult = 1.0, config = {extra = 2},
  ["Seeing Double"] = {"Xmult", "extra"},
  -- j_matador=          set = "Joker", effect = "", config = {extra = 8},
  ["Matador"] = {"money", "extra"},
  -- j_hit_the_road=     set = "Joker", effect = "Jack Discard Effect", cost_mult = 1.0, config = {extra = 0.5},
  ["Hit the Road"] = {"Xmult_mod", "extra"},
  -- j_duo=              set = "Joker", effect = "X1.5 Mult", cost_mult = 1.0, config = {Xmult = 2, type = 'Pair'},
  ["The Duo"] = {"Xmult", "Xmult"},
  -- j_trio=             set = "Joker", effect = "X2 Mult", cost_mult = 1.0, config = {Xmult = 3, type = 'Three of a Kind'},
  ["The Trio"] = {"Xmult", "Xmult"},
  -- j_family=           set = "Joker", effect = "X3 Mult", cost_mult = 1.0, config = {Xmult = 4, type = 'Four of a Kind'},
  ["The Family"] = {"Xmult", "Xmult"},
  -- j_order=            set = "Joker", effect = "X3 Mult", cost_mult = 1.0, config = {Xmult = 3, type = 'Straight'},
  ["The Order"] = {"Xmult", "Xmult"},
  -- j_tribe=            set = "Joker", effect = "X3 Mult", cost_mult = 1.0, config = {Xmult = 2, type = 'Flush'},
  ["The Tribe"] = {"Xmult", "Xmult"},
  -- j_stuntman=         set = "Joker", effect = "", config = {extra = {h_size = 2, chip_mod = 250}},
  ["Stuntman"] = {"chips", "chip_mod"},
  -- j_satellite=        set = "Joker", effect = "", config = {extra = 1},
  ["Satellite"] = {"money", "extra"},
  -- j_shoot_the_moon=   set = "Joker", effect = "", config = {extra = 13},
  ["Shoot the Moon"] = {"mult_mod", "extra"},
  -- j_drivers_license=  set = "Joker", effect = "", config = {extra = 3},
  ["Driver's License"] = {"Xmult", "extra"},
  -- j_bootstraps=       set = "Joker", effect = "", config = {extra = {mult = 2, dollars = 5}},
  ["Bootstraps"] = {"mult_mod", "mult"},
  -- j_caino=            set = "Joker", effect = "", config = {extra = 1},
  ["Canio"] = {"Xmult_mod", "extra"},
  -- j_triboulet=        set = "Joker", effect = "", config = {extra = 2},
  ["Triboulet"] = {"Xmult_mod", "extra"},
  -- j_yorick=           set = "Joker", effect = "", config = {extra = {xmult = 1, discards = 23}},
  ["Yorick"] = {"Xmult_mod", "xmult"},
}

return energizable_vanilla