PokemonSprites = {
  lookup = {},
  artist_lookup = {},
  list = {
{name = "bulbasaur", base = {pos = {x = 0, y = 0}},},
{name = "ivysaur", base = {pos = {x = 2, y = 0}},},
{name = "venusaur", base = {pos = {x = 4, y = 0}},},
{name = "mega_venusaur", base = {pos = {x = 4, y = 0}, soul_pos = {x = 5, y = 0}},gen_atlas = 1},
{name = "gmax_venusaur", base = {pos = {x = 12, y = 6}, soul_pos = {x = 13, y = 6}},gen_atlas = 1},
{name = "charmander", base = {pos = {x = 6, y = 0}},},
{name = "charmeleon", base = {pos = {x = 8, y = 0}},},
{name = "charizard", base = {pos = {x = 10, y = 0}},},
{name = "mega_charizard_x", base = {pos = {x = 6, y = 0}, soul_pos = {x = 7, y = 0}},gen_atlas = 1},
{name = "mega_charizard_y", base = {pos = {x = 8, y = 0}, soul_pos = {x = 9, y = 0}},gen_atlas = 1},
{name = "gmax_charizard", base = {pos = {x = 0, y = 7}, soul_pos = {x = 1, y = 7}},gen_atlas = 1},
{name = "squirtle", base = {pos = {x = 12, y = 0}},},
{name = "wartortle", base = {pos = {x = 14, y = 0}},},
{name = "blastoise", base = {pos = {x = 16, y = 0}},},
{name = "mega_blastoise", base = {pos = {x = 10, y = 0}, soul_pos = {x = 11, y = 0}},gen_atlas = 1},
{name = "gmax_blastoise", base = {pos = {x = 14, y = 6}, soul_pos = {x = 15, y = 6}},gen_atlas = 1},
{name = "caterpie", base = {pos = {x = 18, y = 0}}, alts = {AtlasJokersSeriesA = {artist = 'RedHaering'}}},
{name = "metapod", base = {pos = {x = 20, y = 0}},},
{name = "butterfree", base = {pos = {x = 22, y = 0}},},
{name = "gmax_butterfree", base = {pos = {x = 2, y = 7}, soul_pos = {x = 3, y = 7}},gen_atlas = 1},
{name = "weedle", base = {pos = {x = 24, y = 0}},},
{name = "kakuna", base = {pos = {x = 26, y = 0}},},
{name = "beedrill", base = {pos = {x = 28, y = 0}},},
{name = "mega_beedrill", base = {pos = {x = 12, y = 0}, soul_pos = {x = 13, y = 0}},gen_atlas = 1},
{name = "pidgey", base = {pos = {x = 0, y = 1}},},
{name = "pidgeotto", base = {pos = {x = 2, y = 1}},},
{name = "pidgeot", base = {pos = {x = 4, y = 1}},},
{name = "mega_pidgeot", base = {pos = {x = 14, y = 0}, soul_pos = {x = 15, y = 0}},gen_atlas = 1},
{name = "rattata", base = {pos = {x = 6, y = 1}},},
{name = "alolan_rattata", base = {pos = {x = 2, y = 2}},gen_atlas = 1},
{name = "raticate", base = {pos = {x = 8, y = 1}},},
{name = "alolan_raticate", base = {pos = {x = 4, y = 2}},gen_atlas = 1},
{name = "spearow", base = {pos = {x = 10, y = 1}},},
{name = "fearow", base = {pos = {x = 12, y = 1}},},
{name = "ekans", base = {pos = {x = 14, y = 1}},},
{name = "arbok", base = {pos = {x = 16, y = 1}},},
{name = "pikachu", base = {pos = {x = 18, y = 1}}, alts = {AtlasJokersSeriesA = {artist = 'MyDude_YT'}}},
{name = "gmax_pikachu", base = {pos = {x = 4, y = 7}, soul_pos = {x = 5, y = 7}},gen_atlas = 1},
{name = "raichu", base = {pos = {x = 20, y = 1}}, alts = {AtlasJokersSeriesA = {artist = 'MyDude_YT'}}},
{name = "alolan_raichu", base = {pos = {x = 6, y = 2}},gen_atlas = 1, alts = {AtlasJokersSeriesA = {artist = 'MyDude_YT'}}},
{name = "mega_raichu_x", base = {pos = {x = 2, y = 9}, soul_pos = {x = 3, y = 9}},gen_atlas = 1, alts = {AtlasJokersSeriesA = {artist = 'MyDude_YT'}}},
{name = "mega_raichu_y", base = {pos = {x = 4, y = 9}, soul_pos = {x = 5, y = 9}},gen_atlas = 1, alts = {AtlasJokersSeriesA = {artist = 'MyDude_YT'}}},
{name = "sandshrew", base = {pos = {x = 22, y = 1}},},
{name = "alolan_sandshrew", base = {pos = {x = 8, y = 2}},gen_atlas = 1},
{name = "sandslash", base = {pos = {x = 24, y = 1}},},
{name = "alolan_sandslash", base = {pos = {x = 10, y = 2}},gen_atlas = 1},
{name = "nidoranf", base = {pos = {x = 26, y = 1}},},
{name = "nidorina", base = {pos = {x = 28, y = 1}},},
{name = "nidoqueen", base = {pos = {x = 0, y = 2}},},
{name = "nidoranm", base = {pos = {x = 2, y = 2}},},
{name = "nidorino", base = {pos = {x = 4, y = 2}},},
{name = "nidoking", base = {pos = {x = 6, y = 2}},},
{name = "clefairy", base = {pos = {x = 8, y = 2}}, alts = {AtlasJokersSeriesA = {artist = 'RibbonOnline'}}},
{name = "clefable", base = {pos = {x = 10, y = 2}},alts = {AtlasJokersSeriesA = {artist = 'RibbonOnline'}}},
{name = "vulpix", base = {pos = {x = 12, y = 2}},},
{name = "alolan_vulpix", base = {pos = {x = 12, y = 2}},gen_atlas = 1},
{name = "ninetales", base = {pos = {x = 14, y = 2}},alts = {AtlasJokersSeriesA = {artist = 'Celsie_RS'}}},
{name = "alolan_ninetales", base = {pos = {x = 14, y = 2}},gen_atlas = 1},
{name = "jigglypuff", base = {pos = {x = 16, y = 2}},alts = {AtlasJokersSeriesA = {artist = 'RibbonOnline'}}},
{name = "wigglytuff", base = {pos = {x = 18, y = 2}},alts = {AtlasJokersSeriesA = {artist = 'RibbonOnline'}}},
{name = "zubat", base = {pos = {x = 20, y = 2}},},
{name = "golbat", base = {pos = {x = 22, y = 2}},alts = {AtlasJokersSeriesA = {artist = 'MyDude_YT'}}},
{name = "oddish", base = {pos = {x = 24, y = 2}},alts = {AtlasJokersSeriesA = {artist = 'RedHaering'}}},
{name = "gloom", base = {pos = {x = 26, y = 2}},},
{name = "vileplume", base = {pos = {x = 28, y = 2}},},
{name = "paras", base = {pos = {x = 0, y = 3}},},
{name = "parasect", base = {pos = {x = 2, y = 3}},},
{name = "venonat", base = {pos = {x = 4, y = 3}},},
{name = "venomoth", base = {pos = {x = 6, y = 3}},},
{name = "diglett", base = {pos = {x = 8, y = 3}},},
{name = "alolan_diglett", base = {pos = {x = 0, y = 3}},gen_atlas = 1},
{name = "dugtrio", base = {pos = {x = 10, y = 3}},},
{name = "alolan_dugtrio", base = {pos = {x = 2, y = 3}},gen_atlas = 1},
{name = "meowth", base = {pos = {x = 12, y = 3}},},
{name = "alolan_meowth", base = {pos = {x = 4, y = 3}},gen_atlas = 1},
{name = "galarian_meowth", base = {pos = {x = 8, y = 4}},gen_atlas = 1},
{name = "gmax_meowth", base = {pos = {x = 6, y = 7}, soul_pos = {x = 7, y = 7}},gen_atlas = 1},
{name = "persian", base = {pos = {x = 14, y = 3}},},
{name = "alolan_persian", base = {pos = {x = 6, y = 3}},gen_atlas = 1},
{name = "psyduck", base = {pos = {x = 16, y = 3}},},
{name = "golduck", base = {pos = {x = 18, y = 3}},},
{name = "mankey", base = {pos = {x = 20, y = 3}},},
{name = "primeape", base = {pos = {x = 22, y = 3}},},
{name = "growlithe", base = {pos = {x = 24, y = 3}},alts = {AtlasJokersSeriesA = {artist = 'Xenellia'}}},
{name = "hisuian_growlithe", base = {pos = {x = 14, y = 5}},gen_atlas = 1},
{name = "arcanine", base = {pos = {x = 26, y = 3}},alts = {AtlasJokersSeriesA = {artist = 'Xenellia'}}},
{name = "hisuian_arcanine", base = {pos = {x = 0, y = 6}},gen_atlas = 1},
{name = "poliwag", base = {pos = {x = 28, y = 3}},},
{name = "poliwhirl", base = {pos = {x = 0, y = 4}},},
{name = "poliwrath", base = {pos = {x = 2, y = 4}},},
{name = "abra", base = {pos = {x = 4, y = 4}},},
{name = "kadabra", base = {pos = {x = 6, y = 4}},},
{name = "alakazam", base = {pos = {x = 8, y = 4}},},
{name = "mega_alakazam", base = {pos = {x = 0, y = 1}, soul_pos = {x = 1, y = 1}},gen_atlas = 1},
{name = "machop", base = {pos = {x = 10, y = 4}},},
{name = "machoke", base = {pos = {x = 12, y = 4}},},
{name = "machamp", base = {pos = {x = 14, y = 4}},},
{name = "gmax_machamp", base = {pos = {x = 8, y = 7}, soul_pos = {x = 9, y = 7}},gen_atlas = 1},
{name = "bellsprout", base = {pos = {x = 16, y = 4}},},
{name = "weepinbell", base = {pos = {x = 18, y = 4}},},
{name = "victreebel", base = {pos = {x = 20, y = 4}},},
{name = "tentacool", base = {pos = {x = 22, y = 4}},},
{name = "tentacruel", base = {pos = {x = 24, y = 4}},},
{name = "geodude", base = {pos = {x = 26, y = 4}},},
{name = "alolan_geodude", base = {pos = {x = 8, y = 3}},gen_atlas = 1},
{name = "graveler", base = {pos = {x = 28, y = 4}},},
{name = "alolan_graveler", base = {pos = {x = 10, y = 3}},gen_atlas = 1},
{name = "golem", base = {pos = {x = 0, y = 5}},},
{name = "alolan_golem", base = {pos = {x = 12, y = 3}},gen_atlas = 1},
{name = "ponyta", base = {pos = {x = 2, y = 5}},alts = {AtlasJokersSeriesA = {artist = 'Xenellia'}}},
{name = "galarian_ponyta", base = {pos = {x = 10, y = 4}},gen_atlas = 1},
{name = "rapidash", base = {pos = {x = 4, y = 5}},alts = {AtlasJokersSeriesA = {artist = 'Xenellia'}}},
{name = "galarian_rapidash", base = {pos = {x = 12, y = 4}},gen_atlas = 1},
{name = "slowpoke", base = {pos = {x = 6, y = 5}},},
{name = "galarian_slowpoke", base = {pos = {x = 14, y = 4}},gen_atlas = 1},
{name = "slowbro", base = {pos = {x = 8, y = 5}},},
{name = "galarian_slowbro", base = {pos = {x = 0, y = 5}},gen_atlas = 1},
{name = "mega_slowbro", base = {pos = {x = 2, y = 1}, soul_pos = {x = 3, y = 1}},gen_atlas = 1},
{name = "shell", base = {pos = {x = 4, y = 8}}, gen_atlas = 1,},
{name = "magnemite", base = {pos = {x = 10, y = 5}},alts = {AtlasJokersSeriesA = {artist = 'MyDude_YT'}}},
{name = "magneton", base = {pos = {x = 12, y = 5}},},
{name = "farfetchd", base = {pos = {x = 14, y = 5}},},
{name = "galarian_farfetchd", base = {pos = {x = 2, y = 5}},gen_atlas = 1},
{name = "doduo", base = {pos = {x = 16, y = 5}},},
{name = "dodrio", base = {pos = {x = 18, y = 5}},},
{name = "seel", base = {pos = {x = 20, y = 5}},},
{name = "dewgong", base = {pos = {x = 22, y = 5}},},
{name = "grimer", base = {pos = {x = 24, y = 5}},},
{name = "alolan_grimer", base = {pos = {x = 14, y = 3}},gen_atlas = 1},
{name = "muk", base = {pos = {x = 26, y = 5}},alts = {AtlasJokersSeriesA = {artist = 'MyDude_YT'}}},
{name = "alolan_muk", base = {pos = {x = 0, y = 4}},gen_atlas = 1},
{name = "shellder", base = {pos = {x = 28, y = 5}},},
{name = "cloyster", base = {pos = {x = 0, y = 6}},},
{name = "gastly", base = {pos = {x = 2, y = 6}},alts = {AtlasJokersSeriesA = {artist = 'MyDude_YT'}}},
{name = "haunter", base = {pos = {x = 4, y = 6}},alts = {AtlasJokersSeriesA = {artist = 'MyDude_YT', soul_pos = {x = 5, y = 6}}}},
{name = "gengar", base = {pos = {x = 6, y = 6}},alts = {AtlasJokersSeriesA = {artist = 'MyDude_YT', soul_pos = {x = 7, y = 6}}}},
{name = "mega_gengar", base = {pos = {x = 4, y = 1}, soul_pos = {x = 5, y = 1}},gen_atlas = 1, alts = {AtlasJokersSeriesA = {artist = 'MyDude_YT'}}},
{name = "gmax_gengar", base = {pos = {x = 10, y = 7}, soul_pos = {x = 11, y = 7}},gen_atlas = 1},
{name = "onix", base = {pos = {x = 8, y = 6}},},
{name = "drowzee", base = {pos = {x = 10, y = 6}},},
{name = "hypno", base = {pos = {x = 12, y = 6}},},
{name = "krabby", base = {pos = {x = 14, y = 6}},},
{name = "kingler", base = {pos = {x = 16, y = 6}},},
{name = "gmax_kingler", base = {pos = {x = 12, y = 7}, soul_pos = {x = 13, y = 7}},gen_atlas = 1},
{name = "voltorb", base = {pos = {x = 18, y = 6}},alts = {
    AtlasJokersSeriesA = {artist = 'Maelmc', anim_atlas = "AtlasJokersSeriesAVoltorb"},
    AtlasJokersSeriesB = {artist = 'MyDude_YT'}
}},
{name = "hisuian_voltorb", base = {pos = {x = 2, y = 6}},gen_atlas = 1},
{name = "electrode", base = {pos = {x = 20, y = 6}},alts = {AtlasJokersSeriesA = {artist = 'Maelmc',anim_atlas = "AtlasJokersSeriesAElectrode"}}},
{name = "hisuian_electrode", base = {pos = {x = 4, y = 6}},gen_atlas = 1},
{name = "exeggcute", base = {pos = {x = 22, y = 6}},},
{name = "exeggutor", base = {pos = {x = 24, y = 6}},alts = {AtlasJokersSeriesA = {artist = 'MyDude_YT'}}},
{name = "alolan_exeggutor", base = {pos = {x = 2, y = 4}},gen_atlas = 1},
{name = "cubone", base = {pos = {x = 26, y = 6}},},
{name = "marowak", base = {pos = {x = 28, y = 6}},},
{name = "alolan_marowak", base = {pos = {x = 6, y = 4}},gen_atlas = 1},
{name = "hitmonlee", base = {pos = {x = 0, y = 7}},alts = {AtlasJokersSeriesA = {artist = 'MyDude_YT'}}},
{name = "hitmonchan", base = {pos = {x = 2, y = 7}},alts = {AtlasJokersSeriesA = {artist = 'MyDude_YT'}}},
{name = "lickitung", base = {pos = {x = 4, y = 7}},},
{name = "koffing", base = {pos = {x = 6, y = 7}},},
{name = "weezing", base = {pos = {x = 8, y = 7}},},
{name = "galarian_weezing", base = {pos = {x = 4, y = 5}},gen_atlas = 1},
{name = "rhyhorn", base = {pos = {x = 10, y = 7}},},
{name = "rhydon", base = {pos = {x = 12, y = 7}},},
{name = "chansey", base = {pos = {x = 14, y = 7}},},
{name = "tangela", base = {pos = {x = 16, y = 7}},alts = {AtlasJokersSeriesA = {artist = 'MyDude_YT'}}},
{name = "kangaskhan", base = {pos = {x = 18, y = 7}},},
{name = "mega_kangaskhan", base = {pos = {x = 6, y = 1}, soul_pos = {x = 7, y = 1}},gen_atlas = 1},
{name = "horsea", base = {pos = {x = 20, y = 7}},},
{name = "seadra", base = {pos = {x = 22, y = 7}},},
{name = "goldeen", base = {pos = {x = 24, y = 7}},},
{name = "seaking", base = {pos = {x = 26, y = 7}},},
{name = "staryu", base = {pos = {x = 28, y = 7}},alts = {AtlasJokersSeriesA = {artist = {'Chartreuse_Chamber', 'Xenellia'}}}},
{name = "starmie", base = {pos = {x = 0, y = 8}},alts = {AtlasJokersSeriesA = {artist = {'MyDude_YT', 'Chartreuse_Chamber'}}}},
{name = "mrmime", base = {pos = {x = 2, y = 8}},alts = {AtlasJokersSeriesA = {artist = 'RedHaering', soul_pos = {x = 3, y = 8}}}},
{name = "galarian_mrmime", base = {pos = {x = 6, y = 5}},gen_atlas = 1},
{name = "scyther", base = {pos = {x = 4, y = 8}},},
{name = "jynx", base = {pos = {x = 6, y = 8}},},
{name = "electabuzz", base = {pos = {x = 8, y = 8}},},
{name = "magmar", base = {pos = {x = 10, y = 8}},},
{name = "pinsir", base = {pos = {x = 12, y = 8}},},
{name = "mega_pinsir", base = {pos = {x = 8, y = 1}, soul_pos = {x = 9, y = 1}},gen_atlas = 1},
{name = "tauros", base = {pos = {x = 14, y = 8}},},
{name = "taurosh", base = {pos = {x = 0, y = 0}}, gen_atlas = 1,},
{name = "paldean_tauros", base = {pos = {x = 6, y = 6}},gen_atlas = 1},
{name = "paldean_tauros_blaze", base = {pos = {x = 8, y = 6}},gen_atlas = 1},
{name = "paldean_tauros_aqua", base = {pos = {x = 10, y = 6}},gen_atlas = 1},
{name = "magikarp", base = {pos = {x = 16, y = 8}},},
{name = "gyarados", base = {pos = {x = 18, y = 8}},},
{name = "mega_gyarados", base = {pos = {x = 10, y = 1}, soul_pos = {x = 11, y = 1}},gen_atlas = 1},
{name = "lapras", base = {pos = {x = 20, y = 8}},alts = {AtlasJokersSeriesA = {artist = 'Celsie_RS'}}},
{name = "gmax_lapras", base = {pos = {x = 14, y = 7}, soul_pos = {x = 15, y = 7}},gen_atlas = 1},
{name = "ditto", base = {pos = {x = 22, y = 8}},},
{name = "eevee", base = {pos = {x = 24, y = 8}},alts = {AtlasJokersSeriesA = {artist = 'Desnik'}}},
{name = "gmax_eevee", base = {pos = {x = 0, y = 8}, soul_pos = {x = 1, y = 8}},gen_atlas = 1},
{name = "vaporeon", base = {pos = {x = 26, y = 8}},},
{name = "jolteon", base = {pos = {x = 28, y = 8}},},
{name = "flareon", base = {pos = {x = 0, y = 9}},alts = {AtlasJokersSeriesA = {artist = 'Dudelings'}}},
{name = "porygon", base = {pos = {x = 2, y = 9}},alts = {
    AtlasJokersSeriesA = {artist = 'Captain_Slime'}, 
    AtlasJokersSeriesB = {artist = 'MyDude_YT'}
}},
{name = "omanyte", base = {pos = {x = 4, y = 9}},},
{name = "omastar", base = {pos = {x = 6, y = 9}},},
{name = "kabuto", base = {pos = {x = 8, y = 9}},},
{name = "kabutops", base = {pos = {x = 10, y = 9}},},
{name = "aerodactyl", base = {pos = {x = 12, y = 9}},},
{name = "mega_aerodactyl", base = {pos = {x = 12, y = 1}, soul_pos = {x = 13, y = 1}},gen_atlas = 1},
{name = "snorlax", base = {pos = {x = 14, y = 9}},},
{name = "gmax_snorlax", base = {pos = {x = 2, y = 8}, soul_pos = {x = 3, y = 8}},gen_atlas = 1},
{name = "articuno", base = {pos = {x = 16, y = 9}, soul_pos = {x = 17, y = 9}},alts = {AtlasJokersSeriesA = {artist = {name = 'bt', layer = 'center'}}}},
{name = "galarian_articuno", base = {pos = {x = 8, y = 5}, soul_pos = {x = 9, y = 5}},gen_atlas = 1},
{name = "zapdos", base = {pos = {x = 18, y = 9}, soul_pos = {x = 19, y = 9}},alts = {AtlasJokersSeriesA = {artist = {name = 'Sonfive', layer = 'center'}}}},
{name = "galarian_zapdos", base = {pos = {x = 10, y = 5}, soul_pos = {x = 11, y = 5}},gen_atlas = 1},
{name = "moltres", base = {pos = {x = 20, y = 9}, soul_pos = {x = 21, y = 9}},alts = {AtlasJokersSeriesA = {}}},
{name = "galarian_moltres", base = {pos = {x = 12, y = 5}, soul_pos = {x = 13, y = 5}},gen_atlas = 1},
{name = "dratini", base = {pos = {x = 22, y = 9}},alts = {AtlasJokersSeriesA = {artist = 'Desnik'}}},
{name = "dragonair", base = {pos = {x = 24, y = 9}},},
{name = "dragonite", base = {pos = {x = 26, y = 9}},},
{name = "mewtwo", base = {pos = {x = 28, y = 9}, soul_pos = {x = 29, y = 9}},alts = {AtlasJokersSeriesA = {artist = {name = 'Catzzadilla', layer = 'center'}}}},
{name = "mega_mewtwo_x", base = {pos = {x = 14, y = 1}, soul_pos = {x = 15, y = 1}},gen_atlas = 1},
{name = "mega_mewtwo_y", base = {pos = {x = 0, y = 2}, soul_pos = {x = 1, y = 2}},gen_atlas = 1},
{name = "mew", base = {pos = {x = 0, y = 10}, soul_pos = {x = 1, y = 10}},alts = {AtlasJokersSeriesA = {artist = {name = 'Catzzadilla', layer = 'center'}}}},
{name = "missingno", base = {pos = {x = 2, y = 0}, soul_pos = {x = 3, y = 0}}, gen_atlas = 1, alts = {AtlasJokersSeriesA = {artist = {name = 'Catzzadilla', layer = 'center'}}}},
{name = "chikorita", base = {pos = {x = 2, y = 10}},},
{name = "bayleef", base = {pos = {x = 4, y = 10}},},
{name = "meganium", base = {pos = {x = 6, y = 10}},},
{name = "cyndaquil", base = {pos = {x = 8, y = 10}},},
{name = "quilava", base = {pos = {x = 10, y = 10}},},
{name = "typhlosion", base = {pos = {x = 12, y = 10}},},
{name = "hisuian_typhlosion", base = {pos = {x = 0, y = 5}},gen_atlas = 2},
{name = "totodile", base = {pos = {x = 14, y = 10}},},
{name = "croconaw", base = {pos = {x = 16, y = 10}},},
{name = "feraligatr", base = {pos = {x = 18, y = 10}},},
{name = "sentret", base = {pos = {x = 20, y = 10}},},
{name = "furret", base = {pos = {x = 22, y = 10}},},
{name = "hoothoot", base = {pos = {x = 24, y = 10}},},
{name = "noctowl", base = {pos = {x = 26, y = 10}},},
{name = "ledyba", base = {pos = {x = 28, y = 10}},},
{name = "ledian", base = {pos = {x = 0, y = 11}},},
{name = "spinarak", base = {pos = {x = 2, y = 11}},},
{name = "ariados", base = {pos = {x = 4, y = 11}},},
{name = "crobat", base = {pos = {x = 6, y = 11}},},
{name = "chinchou", base = {pos = {x = 8, y = 11}},},
{name = "lanturn", base = {pos = {x = 10, y = 11}},},
{name = "pichu", base = {pos = {x = 12, y = 11}},alts = {AtlasJokersSeriesA = {artist = 'MyDude_YT'}}},
{name = "cleffa", base = {pos = {x = 14, y = 11}},alts = {AtlasJokersSeriesA = {artist = 'RibbonOnline'}}},
{name = "igglybuff", base = {pos = {x = 16, y = 11}},alts = {AtlasJokersSeriesA = {artist = 'RibbonOnline'}}},
{name = "togepi", base = {pos = {x = 18, y = 11}},},
{name = "togetic", base = {pos = {x = 20, y = 11}},},
{name = "natu", base = {pos = {x = 22, y = 11}},},
{name = "xatu", base = {pos = {x = 24, y = 11}},},
{name = "mareep", base = {pos = {x = 26, y = 11}},},
{name = "flaaffy", base = {pos = {x = 28, y = 11}},},
{name = "ampharos", base = {pos = {x = 0, y = 12}},},
{name = "mega_ampharos", base = {pos = {x = 4, y = 3}, soul_pos = {x = 5, y = 3}},gen_atlas = 2},
{name = "bellossom", base = {pos = {x = 2, y = 12}},},
{name = "marill", base = {pos = {x = 4, y = 12}},},
{name = "azumarill", base = {pos = {x = 6, y = 12}},},
{name = "sudowoodo", base = {pos = {x = 8, y = 12}},},
{name = "weird_tree", base = {pos = {x = 0, y = 3}}, alts = {AtlasJokersSeriesA = {artist = 'RedHaering'}},gen_atlas = 2},
{name = "politoed", base = {pos = {x = 10, y = 12}},alts = {AtlasJokersSeriesA = {artist = 'Sonfive'}}},
{name = "hoppip", base = {pos = {x = 12, y = 12}},},
{name = "skiploom", base = {pos = {x = 14, y = 12}},},
{name = "jumpluff", base = {pos = {x = 16, y = 12}},alts = {AtlasJokersSeriesA = {artist = 'Celsie_RS'}}},
{name = "aipom", base = {pos = {x = 18, y = 12}},alts = {AtlasJokersSeriesA = {artist = 'Sunny'}}},
{name = "sunkern", base = {pos = {x = 20, y = 12}},},
{name = "sunflora", base = {pos = {x = 22, y = 12}},},
{name = "yanma", base = {pos = {x = 24, y = 12}},},
{name = "wooper", base = {pos = {x = 26, y = 12}},alts = {AtlasJokersSeriesA = {artist = 'Desnik'}}},
{name = "paldean_wooper", base = {pos = {x = 6, y = 5}},gen_atlas = 2},
{name = "quagsire", base = {pos = {x = 28, y = 12}},alts = {AtlasJokersSeriesA = {artist = 'Desnik'}}},
{name = "espeon", base = {pos = {x = 0, y = 13}},},
{name = "umbreon", base = {pos = {x = 2, y = 13}},},
{name = "murkrow", base = {pos = {x = 4, y = 13}},},
{name = "slowking", base = {pos = {x = 6, y = 13}},},
{name = "galarian_slowking", base = {pos = {x = 6, y = 4}},gen_atlas = 2},
{name = "misdreavus", base = {pos = {x = 8, y = 13}},},
{name = "unown", base = {pos = {x = 0, y = 0}, soul_pos = {x = 1, y = 0}},gen_atlas = 2},
{name = "wobbuffet", base = {pos = {x = 12, y = 13}},},
{name = "girafarig", base = {pos = {x = 14, y = 13}},},
{name = "pineco", base = {pos = {x = 16, y = 13}},},
{name = "forretress", base = {pos = {x = 18, y = 13}},},
{name = "dunsparce", base = {pos = {x = 20, y = 13}},},
{name = "gligar", base = {pos = {x = 22, y = 13}},},
{name = "steelix", base = {pos = {x = 24, y = 13}},},
{name = "mega_steelix", base = {pos = {x = 6, y = 3}, soul_pos = {x = 7, y = 3}},gen_atlas = 2},
{name = "snubbull", base = {pos = {x = 26, y = 13}},},
{name = "granbull", base = {pos = {x = 28, y = 13}},},
{name = "qwilfish", base = {pos = {x = 0, y = 14}},},
{name = "hisuian_qwilfish", base = {pos = {x = 2, y = 5}},gen_atlas = 2},
{name = "scizor", base = {pos = {x = 2, y = 14}},},
{name = "mega_scizor", base = {pos = {x = 8, y = 3}, soul_pos = {x = 9, y = 3}},gen_atlas = 2},
{name = "shuckle", base = {pos = {x = 4, y = 14}},},
{name = "heracross", base = {pos = {x = 6, y = 14}},},
{name = "mega_heracross", base = {pos = {x = 0, y = 4}, soul_pos = {x = 1, y = 4}},gen_atlas = 2},
{name = "sneasel", base = {pos = {x = 8, y = 14}},},
{name = "hisuian_sneasel", base = {pos = {x = 4, y = 5}},gen_atlas = 2},
{name = "teddiursa", base = {pos = {x = 10, y = 14}},},
{name = "ursaring", base = {pos = {x = 12, y = 14}},},
{name = "slugma", base = {pos = {x = 14, y = 14}},},
{name = "magcargo", base = {pos = {x = 16, y = 14}},},
{name = "swinub", base = {pos = {x = 18, y = 14}},},
{name = "piloswine", base = {pos = {x = 20, y = 14}},},
{name = "corsola", base = {pos = {x = 22, y = 14}},},
{name = "galarian_corsola", base = {pos = {x = 8, y = 4}},gen_atlas = 2},
{name = "remoraid", base = {pos = {x = 24, y = 14}},},
{name = "octillery", base = {pos = {x = 26, y = 14}},},
{name = "delibird", base = {pos = {x = 28, y = 14}},},
{name = "mantine", base = {pos = {x = 0, y = 15}},},
{name = "skarmory", base = {pos = {x = 2, y = 15}},},
{name = "houndour", base = {pos = {x = 4, y = 15}},},
{name = "houndoom", base = {pos = {x = 6, y = 15}},},
{name = "mega_houndoom", base = {pos = {x = 2, y = 4}, soul_pos = {x = 3, y = 4}},gen_atlas = 2},
{name = "kingdra", base = {pos = {x = 8, y = 15}},},
{name = "phanpy", base = {pos = {x = 10, y = 15}},},
{name = "donphan", base = {pos = {x = 12, y = 15}},},
{name = "porygon2", base = {pos = {x = 14, y = 15}},alts = {AtlasJokersSeriesA = {artist = 'Captain_Slime'}}},
{name = "stantler", base = {pos = {x = 16, y = 15}},},
{name = "smeargle", base = {pos = {x = 18, y = 15}},},
{name = "tyrogue", base = {pos = {x = 20, y = 15}},alts = {AtlasJokersSeriesA = {artist = 'MyDude_YT'}}},
{name = "hitmontop", base = {pos = {x = 22, y = 15}},alts = {AtlasJokersSeriesA = {artist = 'MyDude_YT'}}},
{name = "smoochum", base = {pos = {x = 24, y = 15}},},
{name = "elekid", base = {pos = {x = 26, y = 15}},},
{name = "magby", base = {pos = {x = 28, y = 15}},},
{name = "miltank", base = {pos = {x = 0, y = 16}},},
{name = "blissey", base = {pos = {x = 2, y = 16}},},
{name = "raikou", base = {pos = {x = 4, y = 16}, soul_pos = {x = 5, y = 16}},alts = {AtlasJokersSeriesA = {artist = {name = 'Tovivi', layer = 'center'}}}},
{name = "entei", base = {pos = {x = 6, y = 16}, soul_pos = {x = 7, y = 16}},alts = {AtlasJokersSeriesA = {artist = {name = 'bt', layer = 'center'}}}},
{name = "suicune", base = {pos = {x = 8, y = 16}, soul_pos = {x = 9, y = 16}},alts = {AtlasJokersSeriesA = {artist = {name = 'bt', layer = 'center'}}}},
{name = "larvitar", base = {pos = {x = 10, y = 16}},alts = {AtlasJokersSeriesA = {artist = 'MyDude_YT'}}},
{name = "pupitar", base = {pos = {x = 12, y = 16}},alts = {AtlasJokersSeriesA = {artist = 'MyDude_YT'}}},
{name = "tyranitar", base = {pos = {x = 14, y = 16}},alts = {AtlasJokersSeriesA = {artist = 'MyDude_YT'}}},
{name = "mega_tyranitar", base = {pos = {x = 4, y = 4}, soul_pos = {x = 5, y = 4}},gen_atlas = 2, alts = {AtlasJokersSeriesA = {artist = {'MyDude_YT', 'Silverfish07'}}}},
{name = "lugia", base = {pos = {x = 16, y = 16}, soul_pos = {x = 17, y = 16}},alts = {AtlasJokersSeriesA = {artist = {name = 'Tovivi', layer = 'center'}}}},
{name = "ho_oh", base = {pos = {x = 18, y = 16}, soul_pos = {x = 19, y = 16}},alts = {AtlasJokersSeriesA = {}}},
{name = "celebi", base = {pos = {x = 20, y = 16}, soul_pos = {x = 21, y = 16}},alts = {AtlasJokersSeriesA = {}}},
{name = "treecko", base = {pos = {x = 22, y = 16}},},
{name = "grovyle", base = {pos = {x = 24, y = 16}},},
{name = "sceptile", base = {pos = {x = 26, y = 16}},},
{name = "mega_sceptile", base = {pos = {x = 0, y = 4}, soul_pos = {x = 1, y = 4}},gen_atlas = 3},
{name = "torchic", base = {pos = {x = 28, y = 16}},},
{name = "combusken", base = {pos = {x = 0, y = 17}},},
{name = "blaziken", base = {pos = {x = 2, y = 17}},},
{name = "mega_blaziken", base = {pos = {x = 2, y = 4}, soul_pos = {x = 3, y = 4}},gen_atlas = 3},
{name = "mudkip", base = {pos = {x = 4, y = 17}},},
{name = "marshtomp", base = {pos = {x = 6, y = 17}},},
{name = "swampert", base = {pos = {x = 8, y = 17}},},
{name = "mega_swampert", base = {pos = {x = 4, y = 4}, soul_pos = {x = 5, y = 4}},gen_atlas = 3},
{name = "poochyena", base = {pos = {x = 10, y = 17}},},
{name = "mightyena", base = {pos = {x = 12, y = 17}},},
{name = "zigzagoon", base = {pos = {x = 14, y = 17}},},
{name = "galarian_zigzagoon", base = {pos = {x = 8, y = 7}},gen_atlas = 3},
{name = "linoone", base = {pos = {x = 16, y = 17}},},
{name = "galarian_linoone", base = {pos = {x = 10, y = 7}},gen_atlas = 3},
{name = "wurmple", base = {pos = {x = 18, y = 17}},},
{name = "silcoon", base = {pos = {x = 20, y = 17}},},
{name = "beautifly", base = {pos = {x = 22, y = 17}},},
{name = "cascoon", base = {pos = {x = 24, y = 17}},},
{name = "dustox", base = {pos = {x = 26, y = 17}},},
{name = "lotad", base = {pos = {x = 28, y = 17}}, alts = {AtlasJokersSeriesA = {artist = 'RedHaering'}}},
{name = "lombre", base = {pos = {x = 0, y = 18}},},
{name = "ludicolo", base = {pos = {x = 2, y = 18}},},
{name = "seedot", base = {pos = {x = 4, y = 18}},},
{name = "nuzleaf", base = {pos = {x = 6, y = 18}},},
{name = "shiftry", base = {pos = {x = 8, y = 18}},},
{name = "taillow", base = {pos = {x = 10, y = 18}},},
{name = "swellow", base = {pos = {x = 12, y = 18}},},
{name = "wingull", base = {pos = {x = 14, y = 18}},},
{name = "pelipper", base = {pos = {x = 16, y = 18}},},
{name = "ralts", base = {pos = {x = 18, y = 18}},},
{name = "kirlia", base = {pos = {x = 20, y = 18}},},
{name = "gardevoir", base = {pos = {x = 22, y = 18}},},
{name = "mega_gardevoir", base = {pos = {x = 6, y = 4}, soul_pos = {x = 7, y = 4}},gen_atlas = 3},
{name = "surskit", base = {pos = {x = 24, y = 18}},},
{name = "masquerain", base = {pos = {x = 26, y = 18}},},
{name = "shroomish", base = {pos = {x = 28, y = 18}},},
{name = "breloom", base = {pos = {x = 0, y = 19}},},
{name = "slakoth", base = {pos = {x = 2, y = 19}},},
{name = "vigoroth", base = {pos = {x = 4, y = 19}},},
{name = "slaking", base = {pos = {x = 6, y = 19}},},
{name = "nincada", base = {pos = {x = 8, y = 19}},},
{name = "ninjask", base = {pos = {x = 10, y = 19}},},
{name = "shedinja", base = {pos = {x = 12, y = 19}},},
{name = "whismur", base = {pos = {x = 14, y = 19}},},
{name = "loudred", base = {pos = {x = 16, y = 19}},},
{name = "exploud", base = {pos = {x = 18, y = 19}},},
{name = "makuhita", base = {pos = {x = 20, y = 19}},},
{name = "hariyama", base = {pos = {x = 22, y = 19}},},
{name = "azurill", base = {pos = {x = 24, y = 19}},},
{name = "nosepass", base = {pos = {x = 26, y = 19}},},
{name = "skitty", base = {pos = {x = 28, y = 19}},},
{name = "delcatty", base = {pos = {x = 0, y = 20}},},
{name = "sableye", base = {pos = {x = 2, y = 20}},},
{name = "mega_sableye", base = {pos = {x = 8, y = 4}, soul_pos = {x = 9, y = 4}},gen_atlas = 3},
{name = "mawile", base = {pos = {x = 4, y = 20}},},
{name = "mega_mawile", base = {pos = {x = 10, y = 4}, soul_pos = {x = 11, y = 4}},gen_atlas = 3},
{name = "aron", base = {pos = {x = 6, y = 20}},},
{name = "lairon", base = {pos = {x = 8, y = 20}},},
{name = "aggron", base = {pos = {x = 10, y = 20}},},
{name = "mega_aggron", base = {pos = {x = 0, y = 5}, soul_pos = {x = 1, y = 5}},gen_atlas = 3},
{name = "meditite", base = {pos = {x = 12, y = 20}},},
{name = "medicham", base = {pos = {x = 14, y = 20}},},
{name = "mega_medicham", base = {pos = {x = 2, y = 5}, soul_pos = {x = 3, y = 5}},gen_atlas = 3},
{name = "electrike", base = {pos = {x = 16, y = 20}},},
{name = "manectric", base = {pos = {x = 18, y = 20}},},
{name = "mega_manectric", base = {pos = {x = 4, y = 5}, soul_pos = {x = 5, y = 5}},gen_atlas = 3},
{name = "plusle", base = {pos = {x = 20, y = 20}},},
{name = "minun", base = {pos = {x = 22, y = 20}},},
{name = "volbeat", base = {pos = {x = 24, y = 20}},},
{name = "illumise", base = {pos = {x = 26, y = 20}},},
{name = "roselia", base = {pos = {x = 28, y = 20}},},
{name = "gulpin", base = {pos = {x = 0, y = 21}},},
{name = "swalot", base = {pos = {x = 2, y = 21}},},
{name = "carvanha", base = {pos = {x = 4, y = 21}},},
{name = "sharpedo", base = {pos = {x = 6, y = 21}},},
{name = "mega_sharpedo", base = {pos = {x = 10, y = 5}, soul_pos = {x = 11, y = 5}},gen_atlas = 3},
{name = "wailmer", base = {pos = {x = 8, y = 21}},},
{name = "wailord", base = {pos = {x = 10, y = 21}},alts = {AtlasJokersSeriesA = {artist = 'Celsie_RS'}}},
{name = "numel", base = {pos = {x = 12, y = 21}},},
{name = "camerupt", base = {pos = {x = 14, y = 21}},},
{name = "mega_camerupt", base = {pos = {x = 0, y = 6}, soul_pos = {x = 1, y = 6}},gen_atlas = 3},
{name = "torkoal", base = {pos = {x = 16, y = 21}},},
{name = "spoink", base = {pos = {x = 18, y = 21}},},
{name = "grumpig", base = {pos = {x = 20, y = 21}},},
{name = "spinda", base = {pos = {x = 22, y = 21}},},
{name = "trapinch", base = {pos = {x = 24, y = 21}},},
{name = "vibrava", base = {pos = {x = 26, y = 21}},},
{name = "flygon", base = {pos = {x = 28, y = 21}},},
{name = "cacnea", base = {pos = {x = 0, y = 22}},},
{name = "cacturne", base = {pos = {x = 2, y = 22}},},
{name = "swablu", base = {pos = {x = 4, y = 22}},},
{name = "altaria", base = {pos = {x = 6, y = 22}},},
{name = "mega_altaria", base = {pos = {x = 2, y = 6}, soul_pos = {x = 3, y = 6}},gen_atlas = 3},
{name = "zangoose", base = {pos = {x = 8, y = 22}}, alts = {AtlasJokersSeriesA = {artist = 'CBMX'}}},
{name = "seviper", base = {pos = {x = 10, y = 22}}, alts = {AtlasJokersSeriesA = {artist = 'CBMX'}}},
{name = "lunatone", base = {pos = {x = 12, y = 22}},},
{name = "solrock", base = {pos = {x = 14, y = 22}},},
{name = "barboach", base = {pos = {x = 16, y = 22}},},
{name = "whiscash", base = {pos = {x = 18, y = 22}},},
{name = "corphish", base = {pos = {x = 20, y = 22}},},
{name = "crawdaunt", base = {pos = {x = 22, y = 22}},},
{name = "baltoy", base = {pos = {x = 24, y = 22}},},
{name = "claydol", base = {pos = {x = 26, y = 22}},},
{name = "lileep", base = {pos = {x = 28, y = 22}},},
{name = "cradily", base = {pos = {x = 0, y = 23}},},
{name = "anorith", base = {pos = {x = 2, y = 23}},},
{name = "armaldo", base = {pos = {x = 4, y = 23}},},
{name = "feebas", base = {pos = {x = 6, y = 23}},},
{name = "milotic", base = {pos = {x = 8, y = 23}},},
{name = "castform", base = {pos = {x = 10, y = 23}},},
{name = "kecleon", base = {pos = {x = 12, y = 23}},},
{name = "shuppet", base = {pos = {x = 14, y = 23}},},
{name = "banette", base = {pos = {x = 16, y = 23}},},
{name = "mega_banette", base = {pos = {x = 6, y = 5}, soul_pos = {x = 7, y = 5}},gen_atlas = 3},
{name = "duskull", base = {pos = {x = 18, y = 23}},},
{name = "dusclops", base = {pos = {x = 20, y = 23}},},
{name = "tropius", base = {pos = {x = 22, y = 23}},},
{name = "chimecho", base = {pos = {x = 24, y = 23}},},
{name = "absol", base = {pos = {x = 26, y = 23}},},
{name = "mega_absol", base = {pos = {x = 8, y = 5}, soul_pos = {x = 9, y = 5}},gen_atlas = 3},
{name = "wynaut", base = {pos = {x = 28, y = 23}},},
{name = "snorunt", base = {pos = {x = 0, y = 24}},},
{name = "glalie", base = {pos = {x = 2, y = 24}},},
{name = "mega_glalie", base = {pos = {x = 4, y = 6}, soul_pos = {x = 5, y = 6}},gen_atlas = 3},
{name = "spheal", base = {pos = {x = 4, y = 24}},},
{name = "sealeo", base = {pos = {x = 6, y = 24}},},
{name = "walrein", base = {pos = {x = 8, y = 24}},},
{name = "clamperl", base = {pos = {x = 10, y = 24}},},
{name = "huntail", base = {pos = {x = 12, y = 24}},},
{name = "gorebyss", base = {pos = {x = 14, y = 24}},},
{name = "relicanth", base = {pos = {x = 16, y = 24}},},
{name = "luvdisc", base = {pos = {x = 18, y = 24}},},
{name = "bagon", base = {pos = {x = 20, y = 24}},},
{name = "shelgon", base = {pos = {x = 22, y = 24}},},
{name = "salamence", base = {pos = {x = 24, y = 24}},},
{name = "mega_salamence", base = {pos = {x = 8, y = 6}, soul_pos = {x = 9, y = 6}},gen_atlas = 3},
{name = "beldum", base = {pos = {x = 26, y = 24}},},
{name = "metang", base = {pos = {x = 28, y = 24}},},
{name = "metagross", base = {pos = {x = 0, y = 25}},},
{name = "mega_metagross", base = {pos = {x = 6, y = 6}, soul_pos = {x = 7, y = 6}},gen_atlas = 3},
{name = "regirock", base = {pos = {x = 2, y = 25}, soul_pos = {x = 3, y = 25}},},
{name = "regice", base = {pos = {x = 4, y = 25}, soul_pos = {x = 5, y = 25}},},
{name = "registeel", base = {pos = {x = 6, y = 25}, soul_pos = {x = 7, y = 25}},},
{name = "latias", base = {pos = {x = 8, y = 25}, soul_pos = {x = 9, y = 25}},},
{name = "mega_latias", base = {pos = {x = 10, y = 6}, soul_pos = {x = 11, y = 6}},gen_atlas = 3},
{name = "latios", base = {pos = {x = 10, y = 25}, soul_pos = {x = 11, y = 25}},},
{name = "mega_latios", base = {pos = {x = 0, y = 7}, soul_pos = {x = 3, y = 7}},gen_atlas = 3},
{name = "kyogre", base = {pos = {x = 12, y = 25}, soul_pos = {x = 13, y = 25}},},
{name = "primal_kyogre", base = {pos = {x = 4, y = 7}, soul_pos = {x = 5, y = 7}},gen_atlas = 3},
{name = "groudon", base = {pos = {x = 14, y = 25}, soul_pos = {x = 15, y = 25}},},
{name = "primal_groudon", base = {pos = {x = 2, y = 7}, soul_pos = {x = 3, y = 7}},gen_atlas = 3},
{name = "rayquaza", base = {pos = {x = 16, y = 25}, soul_pos = {x = 17, y = 25}},},
{name = "mega_rayquaza", base = {pos = {x = 6, y = 7}, soul_pos = {x = 7, y = 7}},gen_atlas = 3},
{name = "jirachi", base = {pos = {x = 18, y = 25}, soul_pos = {x = 19, y = 25}},},
{name = "jirachi_banker", base = {pos = {x = 4, y = 2}, soul_pos =  {x = 5, y = 2}}, gen_atlas = 3, alts = {AtlasJokersSeriesA = {artist = 'PrincessRoxie'}}},
{name = "jirachi_booster", base = {pos = {x = 6, y = 2}, soul_pos =  {x = 7, y = 2}}, gen_atlas = 3, alts = {AtlasJokersSeriesA = {artist = 'PrincessRoxie'}}},
{name = "jirachi_power", base = {pos = {x = 8, y = 2}, soul_pos =  {x = 9, y = 2}}, gen_atlas = 3, alts = {AtlasJokersSeriesA = {artist = 'PrincessRoxie'}}},
{name = "jirachi_invis", base = {pos = {x = 10, y = 2}, soul_pos =  {x = 11, y = 2}}, gen_atlas = 3, alts = {AtlasJokersSeriesA = {artist = 'PrincessRoxie'}}},
{name = "jirachi_fixer", base = {pos = {x = 0, y = 3}, soul_pos =  {x = 1, y = 3}}, gen_atlas = 3, alts = {AtlasJokersSeriesA = {artist = 'PrincessRoxie'}}},
{name = "deoxys", base = {pos = {x = 2, y = 3}, soul_pos = {x = 3, y = 3}}, gen_atlas = 3},
{name = "deoxys_attack", base = {pos = {x = 4, y = 3}, soul_pos = {x = 5, y = 3}}, gen_atlas = 3},
{name = "deoxys_defense", base = {pos = {x = 6, y = 3}, soul_pos = {x = 7, y = 3}}, gen_atlas = 3},
{name = "deoxys_speed", base = {pos = {x = 8, y = 3}, soul_pos = {x = 9, y = 3}}, gen_atlas = 3},
{name = "turtwig", base = {pos = {x = 22, y = 25}},},
{name = "grotle", base = {pos = {x = 24, y = 25}},},
{name = "torterra", base = {pos = {x = 26, y = 25}},},
{name = "chimchar", base = {pos = {x = 28, y = 25}},},
{name = "monferno", base = {pos = {x = 0, y = 26}},},
{name = "infernape", base = {pos = {x = 2, y = 26}},},
{name = "piplup", base = {pos = {x = 4, y = 26}},},
{name = "prinplup", base = {pos = {x = 6, y = 26}},},
{name = "empoleon", base = {pos = {x = 8, y = 26}},},
{name = "starly", base = {pos = {x = 10, y = 26}},},
{name = "staravia", base = {pos = {x = 12, y = 26}},},
{name = "staraptor", base = {pos = {x = 14, y = 26}},},
{name = "bidoof", base = {pos = {x = 16, y = 26}},},
{name = "bibarel", base = {pos = {x = 18, y = 26}},},
{name = "kricketot", base = {pos = {x = 20, y = 26}},},
{name = "kricketune", base = {pos = {x = 22, y = 26}},},
{name = "shinx", base = {pos = {x = 24, y = 26}},},
{name = "luxio", base = {pos = {x = 26, y = 26}},},
{name = "luxray", base = {pos = {x = 28, y = 26}},},
{name = "budew", base = {pos = {x = 0, y = 27}},},
{name = "roserade", base = {pos = {x = 2, y = 27}},},
{name = "cranidos", base = {pos = {x = 4, y = 27}},},
{name = "rampardos", base = {pos = {x = 6, y = 27}},},
{name = "shieldon", base = {pos = {x = 8, y = 27}},},
{name = "bastiodon", base = {pos = {x = 10, y = 27}},},
{name = "burmy", base = {pos = {x = 12, y = 27}},},
{name = "wormadam", base = {pos = {x = 14, y = 27}},},
{name = "mothim", base = {pos = {x = 16, y = 27}},},
{name = "combee", base = {pos = {x = 18, y = 27}},},
{name = "vespiquen", base = {pos = {x = 20, y = 27}},},
{name = "pachirisu", base = {pos = {x = 22, y = 27}},},
{name = "buizel", base = {pos = {x = 24, y = 27}},},
{name = "floatzel", base = {pos = {x = 26, y = 27}},},
{name = "cherubi", base = {pos = {x = 28, y = 27}},},
{name = "cherrim", base = {pos = {x = 0, y = 28}},},
{name = "shellos", base = {pos = {x = 2, y = 28}},},
{name = "gastrodon", base = {pos = {x = 4, y = 28}},},
{name = "ambipom", base = {pos = {x = 6, y = 28}},},
{name = "drifloon", base = {pos = {x = 8, y = 28}},},
{name = "drifblim", base = {pos = {x = 10, y = 28}},},
{name = "buneary", base = {pos = {x = 12, y = 28}},},
{name = "lopunny", base = {pos = {x = 14, y = 28}},},
{name = "mega_lopunny", base = {pos = {x = 8, y = 6}, soul_pos = {x = 9, y = 6}},gen_atlas = 4},
{name = "mismagius", base = {pos = {x = 16, y = 28}},},
{name = "honchkrow", base = {pos = {x = 18, y = 28}},},
{name = "glameow", base = {pos = {x = 20, y = 28}},},
{name = "purugly", base = {pos = {x = 22, y = 28}},},
{name = "chingling", base = {pos = {x = 24, y = 28}},},
{name = "stunky", base = {pos = {x = 26, y = 28}},},
{name = "skuntank", base = {pos = {x = 28, y = 28}},},
{name = "bronzor", base = {pos = {x = 0, y = 29}},},
{name = "bronzong", base = {pos = {x = 2, y = 29}},},
{name = "bonsly", base = {pos = {x = 4, y = 29}},alts = {AtlasJokersSeriesA = {artist = 'RedHaering'}}},
{name = "mimejr", base = {pos = {x = 6, y = 29}},alts = {AtlasJokersSeriesA = {artist = 'RedHaering'}}},
{name = "happiny", base = {pos = {x = 8, y = 29}},},
{name = "chatot", base = {pos = {x = 10, y = 29}},alts = {AtlasJokersSeriesA = {artist = 'RedHaering'}}},
{name = "spiritomb", base = {pos = {x = 12, y = 29}},},
{name = "gible", base = {pos = {x = 14, y = 29}},},
{name = "gabite", base = {pos = {x = 16, y = 29}},},
{name = "garchomp", base = {pos = {x = 18, y = 29}},},
{name = "mega_garchomp", base = {pos = {x = 2, y = 7}, soul_pos = {x = 3, y = 7}},gen_atlas = 4},
{name = "munchlax", base = {pos = {x = 20, y = 29}},},
{name = "riolu", base = {pos = {x = 22, y = 29}},},
{name = "lucario", base = {pos = {x = 24, y = 29}},},
{name = "mega_lucario", base = {pos = {x = 6, y = 6}, soul_pos = {x = 7, y = 6}},gen_atlas = 4},
{name = "hippopotas", base = {pos = {x = 26, y = 29}},},
{name = "hippowdon", base = {pos = {x = 28, y = 29}},},
{name = "skorupi", base = {pos = {x = 0, y = 30}},},
{name = "drapion", base = {pos = {x = 2, y = 30}},},
{name = "croagunk", base = {pos = {x = 4, y = 30}},},
{name = "toxicroak", base = {pos = {x = 6, y = 30}},},
{name = "carnivine", base = {pos = {x = 8, y = 30}},},
{name = "finneon", base = {pos = {x = 10, y = 30}},},
{name = "lumineon", base = {pos = {x = 12, y = 30}},},
{name = "mantyke", base = {pos = {x = 14, y = 30}},},
{name = "snover", base = {pos = {x = 16, y = 30}},},
{name = "abomasnow", base = {pos = {x = 18, y = 30}},},
{name = "mega_abomasnow", base = {pos = {x = 10, y = 6}, soul_pos = {x = 11, y = 6}},gen_atlas = 4},
{name = "weavile", base = {pos = {x = 20, y = 30}},},
{name = "magnezone", base = {pos = {x = 22, y = 30}},},
{name = "lickilicky", base = {pos = {x = 24, y = 30}},},
{name = "rhyperior", base = {pos = {x = 26, y = 30}},},
{name = "tangrowth", base = {pos = {x = 28, y = 30}},},
{name = "electivire", base = {pos = {x = 0, y = 31}},},
{name = "magmortar", base = {pos = {x = 2, y = 31}},},
{name = "togekiss", base = {pos = {x = 4, y = 31}},},
{name = "yanmega", base = {pos = {x = 6, y = 31}},},
{name = "leafeon", base = {pos = {x = 8, y = 31}},},
{name = "glaceon", base = {pos = {x = 10, y = 31}},},
{name = "gliscor", base = {pos = {x = 12, y = 31}},},
{name = "mamoswine", base = {pos = {x = 14, y = 31}},},
{name = "porygonz", base = {pos = {x = 16, y = 31}},alts = {AtlasJokersSeriesA = {artist = 'Captain_Slime'}}},
{name = "gallade", base = {pos = {x = 18, y = 31}},},
{name = "mega_gallade", base = {pos = {x = 0, y = 7}, soul_pos = {x = 1, y = 7}},gen_atlas = 4},
{name = "probopass", base = {pos = {x = 20, y = 31}},},
{name = "dusknoir", base = {pos = {x = 22, y = 31}},},
{name = "froslass", base = {pos = {x = 24, y = 31}},},
{name = "rotom", base = {pos = {x = 26, y = 31}},},
{name = "rotomh", base = {pos = {x = 0, y = 2}},gen_atlas = 4},
{name = "rotomw", base = {pos = {x = 8, y = 2}},gen_atlas = 4},
{name = "rotomf", base = {pos = {x = 6, y = 2}},gen_atlas = 4},
{name = "rotomfan", base = {pos = {x = 4, y = 2}},gen_atlas = 4},
{name = "rotomm", base = {pos = {x = 2, y = 2}},gen_atlas = 4},
{name = "uxie", base = {pos = {x = 28, y = 31}, soul_pos = {x = 29, y = 31}},},
{name = "mesprit", base = {pos = {x = 0, y = 32}, soul_pos = {x = 1, y = 32}},},
{name = "azelf", base = {pos = {x = 2, y = 32}, soul_pos = {x = 3, y = 32}},},
{name = "dialga", base = {pos = {x = 10, y = 2}, soul_pos = {x = 11, y = 2}},gen_atlas = 4},
{name = "dialga_origin", base = {pos = {x = 0, y = 3}, soul_pos = {x = 1, y = 3}},gen_atlas = 4},
{name = "palkia", base = {pos = {x = 4, y = 3}, soul_pos = {x = 5, y = 3}},gen_atlas = 4},
{name = "palkia_origin", base = {pos = {x = 6, y = 3}, soul_pos = {x = 7, y = 3}},gen_atlas = 4},
{name = "heatran", base = {pos = {x = 8, y = 32}, soul_pos = {x = 9, y = 32}},},
{name = "regigigas", base = {pos = {x = 10, y = 32}, soul_pos = {x = 11, y = 32}},},
{name = "giratina", base = {pos = {x = 8, y = 3}, soul_pos = {x = 9, y = 3}},gen_atlas = 4},
{name = "giratina_origin", base = {pos = {x = 10, y = 3}, soul_pos = {x = 11, y = 3}},gen_atlas = 4},
{name = "cresselia", base = {pos = {x = 14, y = 32}, soul_pos = {x = 15, y = 32}},},
{name = "phione", base = {pos = {x = 16, y = 32}, soul_pos = {x = 17, y = 32}},},
{name = "manaphy", base = {pos = {x = 18, y = 32}, soul_pos = {x = 19, y = 32}},},
{name = "darkrai", base = {pos = {x = 20, y = 32}, soul_pos = {x = 21, y = 32}},},
{name = "shaymin", base = {pos = {x = 0, y = 4}, soul_pos = {x = 1, y = 4}},gen_atlas = 4},
{name = "shaymin_sky", base = {pos = {x = 2, y = 4}, soul_pos = {x = 3, y = 4}},gen_atlas = 4},
{name = "arceus", base = {pos = {x = 4, y = 4}, soul_pos = {x = 5, y = 4}},gen_atlas = 4},
{name = "victini", base = {pos = {x = 26, y = 32}, soul_pos = {x = 27, y = 32}},},
{name = "snivy", base = {pos = {x = 28, y = 32}},},
{name = "servine", base = {pos = {x = 0, y = 33}},},
{name = "serperior", base = {pos = {x = 2, y = 33}},},
{name = "tepig", base = {pos = {x = 4, y = 33}},},
{name = "pignite", base = {pos = {x = 6, y = 33}},},
{name = "emboar", base = {pos = {x = 8, y = 33}},},
{name = "oshawott", base = {pos = {x = 10, y = 33}},},
{name = "dewott", base = {pos = {x = 12, y = 33}},},
{name = "samurott", base = {pos = {x = 14, y = 33}},},
{name = "hisuian_samurott", base = {pos = {x = 8, y = 8}},gen_atlas = 5},
{name = "patrat", base = {pos = {x = 16, y = 33}},},
{name = "watchog", base = {pos = {x = 18, y = 33}},},
{name = "lillipup", base = {pos = {x = 20, y = 33}},},
{name = "herdier", base = {pos = {x = 22, y = 33}},},
{name = "stoutland", base = {pos = {x = 24, y = 33}},},
{name = "purrloin", base = {pos = {x = 26, y = 33}},},
{name = "liepard", base = {pos = {x = 28, y = 33}},},
{name = "pansage", base = {pos = {x = 0, y = 34}},},
{name = "simisage", base = {pos = {x = 2, y = 34}},},
{name = "pansear", base = {pos = {x = 4, y = 34}},},
{name = "simisear", base = {pos = {x = 6, y = 34}},},
{name = "panpour", base = {pos = {x = 8, y = 34}},},
{name = "simipour", base = {pos = {x = 10, y = 34}},},
{name = "munna", base = {pos = {x = 12, y = 34}},},
{name = "musharna", base = {pos = {x = 14, y = 34}},},
{name = "pidove", base = {pos = {x = 16, y = 34}},},
{name = "tranquill", base = {pos = {x = 18, y = 34}},},
{name = "unfezant", base = {pos = {x = 20, y = 34}},},
{name = "blitzle", base = {pos = {x = 22, y = 34}},},
{name = "zebstrika", base = {pos = {x = 24, y = 34}},},
{name = "roggenrola", base = {pos = {x = 26, y = 34}}, alts = {AtlasJokersSeriesA = {artist = 'Sunny'}}},
{name = "boldore", base = {pos = {x = 28, y = 34}}, alts = {AtlasJokersSeriesA = {artist = 'Sunny'}}},
{name = "gigalith", base = {pos = {x = 0, y = 35}},},
{name = "woobat", base = {pos = {x = 2, y = 35}},},
{name = "swoobat", base = {pos = {x = 4, y = 35}},},
{name = "drilbur", base = {pos = {x = 6, y = 35}},},
{name = "excadrill", base = {pos = {x = 8, y = 35}},},
{name = "audino", base = {pos = {x = 10, y = 35}},},
{name = "mega_audino", base = {pos = {x = 6, y = 7},soul_pos = {x = 7, y = 7}},gen_atlas = 5},
{name = "timburr", base = {pos = {x = 12, y = 35}},},
{name = "gurdurr", base = {pos = {x = 14, y = 35}},},
{name = "conkeldurr", base = {pos = {x = 16, y = 35}},},
{name = "tympole", base = {pos = {x = 18, y = 35}},},
{name = "palpitoad", base = {pos = {x = 20, y = 35}},},
{name = "seismitoad", base = {pos = {x = 22, y = 35}},},
{name = "throh", base = {pos = {x = 24, y = 35}},},
{name = "sawk", base = {pos = {x = 26, y = 35}},},
{name = "sewaddle", base = {pos = {x = 28, y = 35}},},
{name = "swadloon", base = {pos = {x = 0, y = 36}},},
{name = "leavanny", base = {pos = {x = 2, y = 36}},},
{name = "venipede", base = {pos = {x = 4, y = 36}},},
{name = "whirlipede", base = {pos = {x = 6, y = 36}}, alts = {AtlasJokersSeriesA = {artist = 'Maelmc'}}},
{name = "scolipede", base = {pos = {x = 8, y = 36}},},
{name = "cottonee", base = {pos = {x = 10, y = 36}},},
{name = "whimsicott", base = {pos = {x = 12, y = 36}},},
{name = "petilil", base = {pos = {x = 14, y = 36}},},
{name = "lilligant", base = {pos = {x = 16, y = 36}},},
{name = "hisuian_lilligant", base = {pos = {x = 10, y = 8}},gen_atlas = 5},
{name = "basculin", base = {pos = {x = 18, y = 36}},},
{name = "sandile", base = {pos = {x = 20, y = 36}},},
{name = "krokorok", base = {pos = {x = 22, y = 36}},},
{name = "krookodile", base = {pos = {x = 24, y = 36}},},
{name = "darumaka", base = {pos = {x = 26, y = 36}},},
{name = "galarian_darumaka", base = {pos = {x = 10, y = 7}},gen_atlas = 5},
{name = "darmanitan", base = {pos = {x = 10, y = 0}},gen_atlas = 5},
{name = "galarian_darmanitan", base = {pos = {x = 0, y = 8}},gen_atlas = 5},
{name = "maractus", base = {pos = {x = 0, y = 37}},},
{name = "dwebble", base = {pos = {x = 2, y = 37}},},
{name = "crustle", base = {pos = {x = 4, y = 37}},},
{name = "scraggy", base = {pos = {x = 6, y = 37}},},
{name = "scrafty", base = {pos = {x = 8, y = 37}},},
{name = "sigilyph", base = {pos = {x = 10, y = 37}},},
{name = "yamask", base = {pos = {x = 12, y = 37}},},
{name = "galarian_yamask", base = {pos = {x = 4, y = 8}},gen_atlas = 5},
{name = "cofagrigus", base = {pos = {x = 14, y = 37}},},
{name = "tirtouga", base = {pos = {x = 16, y = 37}},},
{name = "carracosta", base = {pos = {x = 18, y = 37}},},
{name = "archen", base = {pos = {x = 20, y = 37}},},
{name = "archeops", base = {pos = {x = 22, y = 37}},},
{name = "trubbish", base = {pos = {x = 24, y = 37}},alts = {AtlasJokersSeriesA = {artist = 'MyDude_YT'}}},
{name = "garbodor", base = {pos = {x = 26, y = 37}},alts = {AtlasJokersSeriesA = {artist = 'MyDude_YT'}}},
{name = "gmax_garbodor", base = {pos = {x = 8, y = 7},soul_pos = {x = 9, y = 7}},gen_atlas = 5},
{name = "zorua", base = {pos = {x = 28, y = 37}},},
{name = "hisuian_zorua", base = {pos = {x = 0, y = 9}},gen_atlas = 5},
{name = "zoroark", base = {pos = {x = 0, y = 38}},},
{name = "hisuian_zoroark", base = {pos = {x = 2, y = 9}},gen_atlas = 5},
{name = "minccino", base = {pos = {x = 2, y = 38}},},
{name = "cinccino", base = {pos = {x = 4, y = 38}},},
{name = "gothita", base = {pos = {x = 6, y = 38}}, alts = {AtlasJokersSeriesA = {artist = 'RedHaering'}}},
{name = "gothorita", base = {pos = {x = 8, y = 38}}, alts = {AtlasJokersSeriesA = {artist = 'RedHaering'}}},
{name = "gothitelle", base = {pos = {x = 10, y = 38}},},
{name = "solosis", base = {pos = {x = 12, y = 38}},},
{name = "duosion", base = {pos = {x = 14, y = 38}},},
{name = "reuniclus", base = {pos = {x = 16, y = 38}},},
{name = "ducklett", base = {pos = {x = 18, y = 38}},},
{name = "swanna", base = {pos = {x = 20, y = 38}},},
{name = "vanillite", base = {pos = {x = 22, y = 38}},},
{name = "vanillish", base = {pos = {x = 24, y = 38}},},
{name = "vanilluxe", base = {pos = {x = 26, y = 38}},},
{name = "deerling", base = {pos = {x = 28, y = 38}},},
{name = "sawsbuck", base = {pos = {x = 0, y = 39}},},
{name = "emolga", base = {pos = {x = 2, y = 39}},},
{name = "karrablast", base = {pos = {x = 4, y = 39}},},
{name = "escavalier", base = {pos = {x = 6, y = 39}},},
{name = "foongus", base = {pos = {x = 8, y = 39}},},
{name = "amoonguss", base = {pos = {x = 10, y = 39}},},
{name = "frillish", base = {pos = {{x = 6, y = 2}, {x= 8, y = 2}}}, gen_atlas = 5,},
{name = "jellicent", base = {pos = {{x = 10, y = 2}, {x= 0, y = 3}}}, gen_atlas = 5,},
{name = "alomomola", base = {pos = {x = 16, y = 39}},},
{name = "joltik", base = {pos = {x = 18, y = 39}},alts = {AtlasJokersSeriesA = {artist = 'RedHaering'}}},
{name = "galvantula", base = {pos = {x = 20, y = 39}},},
{name = "ferroseed", base = {pos = {x = 22, y = 39}},},
{name = "ferrothorn", base = {pos = {x = 24, y = 39}},},
{name = "klink", base = {pos = {x = 26, y = 39}},},
{name = "klang", base = {pos = {x = 28, y = 39}},},
{name = "klinklang", base = {pos = {x = 0, y = 40}},},
{name = "tynamo", base = {pos = {x = 2, y = 40}},},
{name = "eelektrik", base = {pos = {x = 4, y = 40}},},
{name = "eelektross", base = {pos = {x = 6, y = 40}},},
{name = "elgyem", base = {pos = {x = 8, y = 40}},},
{name = "beheeyem", base = {pos = {x = 10, y = 40}},},
{name = "litwick", base = {pos = {x = 12, y = 40}}, alts = {AtlasJokersSeriesA = {artist = 'RedHaering'}}},
{name = "lampent", base = {pos = {x = 14, y = 40}},},
{name = "chandelure", base = {pos = {x = 16, y = 40}},},
{name = "axew", base = {pos = {x = 18, y = 40}},},
{name = "fraxure", base = {pos = {x = 20, y = 40}},},
{name = "haxorus", base = {pos = {x = 22, y = 40}},},
{name = "cubchoo", base = {pos = {x = 24, y = 40}},},
{name = "beartic", base = {pos = {x = 26, y = 40}},alts = {AtlasJokersSeriesA = {artist = 'TunaBear'}}},
{name = "cryogonal", base = {pos = {x = 28, y = 40}},},
{name = "shelmet", base = {pos = {x = 0, y = 41}},},
{name = "accelgor", base = {pos = {x = 2, y = 41}},},
{name = "stunfisk", base = {pos = {x = 4, y = 41}},},
{name = "galarian_stunfisk", base = {pos = {x = 6, y = 8}},gen_atlas = 5},
{name = "mienfoo", base = {pos = {x = 6, y = 41}},},
{name = "mienshao", base = {pos = {x = 8, y = 41}},},
{name = "druddigon", base = {pos = {x = 10, y = 41}},},
{name = "golett", base = {pos = {x = 12, y = 41}},},
{name = "golurk", base = {pos = {x = 14, y = 41}},},
{name = "pawniard", base = {pos = {x = 16, y = 41}},},
{name = "bisharp", base = {pos = {x = 18, y = 41}},},
{name = "bouffalant", base = {pos = {x = 20, y = 41}},},
{name = "rufflet", base = {pos = {x = 22, y = 41}},},
{name = "braviary", base = {pos = {x = 24, y = 41}},},
{name = "hisuian_braviary", base = {pos = {x = 4, y = 9}},gen_atlas = 5},
{name = "vullaby", base = {pos = {x = 26, y = 41}},},
{name = "mandibuzz", base = {pos = {x = 28, y = 41}},},
{name = "heatmor", base = {pos = {x = 0, y = 42}},},
{name = "durant", base = {pos = {x = 2, y = 42}},},
{name = "deino", base = {pos = {x = 4, y = 42}},},
{name = "zweilous", base = {pos = {x = 6, y = 42}},},
{name = "hydreigon", base = {pos = {x = 8, y = 42}},},
{name = "larvesta", base = {pos = {x = 10, y = 42}},},
{name = "volcarona", base = {pos = {x = 12, y = 42}},},
{name = "cobalion", base = {pos = {x = 14, y = 42}, soul_pos = {x = 15, y = 42}},},
{name = "terrakion", base = {pos = {x = 16, y = 42}, soul_pos = {x = 17, y = 42}},},
{name = "virizion", base = {pos = {x = 18, y = 42}, soul_pos = {x = 19, y = 42}},},
{name = "tornadus", base = {pos = {x = 6, y = 3}, soul_pos = {x = 7, y = 3}},gen_atlas = 5},
{name = "tornadus_therian", base = {pos = {x = 8, y = 3}, soul_pos = {x = 9, y = 3}},gen_atlas = 5},
{name = "thundurus", base = {pos = {x = 10, y = 3}, soul_pos = {x = 11, y = 3}},gen_atlas = 5},
{name = "thundurus_therian", base = {pos = {x = 0, y = 4}, soul_pos = {x = 1, y = 4}},gen_atlas = 5},
{name = "reshiram", base = {pos = {x = 2, y = 4}, soul_pos = {x = 3, y = 4}},gen_atlas = 5},
{name = "zekrom", base = {pos = {x = 6, y = 4}, soul_pos = {x = 7, y = 4}},gen_atlas = 5},
{name = "landorus", base = {pos = {x = 10, y = 4}, soul_pos = {x = 11, y = 4}},gen_atlas = 5},
{name = "landorus_therian", base = {pos = {x = 0, y = 5}, soul_pos = {x = 1, y = 5}},gen_atlas = 5},
{name = "kyurem", base = {pos = {x = 2, y = 5}, soul_pos = {x = 3, y = 5}},gen_atlas = 5},
{name = "kyurem_black", base = {pos = {x = 4, y = 5}, soul_pos = {x = 5, y = 5}},gen_atlas = 5},
{name = "kyurem_white", base = {pos = {x = 8, y = 5}, soul_pos = {x = 9, y = 5}},gen_atlas = 5},
{name = "keldeo", base = {pos = {x = 0, y = 6}, soul_pos = {x = 1, y = 6}},gen_atlas = 5},
{name = "keldeo_resolute", base = {pos = {x = 2, y = 6}, soul_pos = {x = 3, y = 6}},gen_atlas = 5},
{name = "meloetta", base = {pos = {x = 4, y = 6}, soul_pos = {x = 5, y = 6}},gen_atlas = 5},
{name = "meloetta_pirouette", base = {pos = {x = 6, y = 6}, soul_pos = {x = 7, y = 6}},gen_atlas = 5},
{name = "genesect", base = {pos = {x = 8, y = 6}, soul_pos = {x = 9, y = 6}},gen_atlas = 5},
{name = "chespin", base = {pos = {x = 8, y = 43}},},
{name = "quilladin", base = {pos = {x = 10, y = 43}},},
{name = "chesnaught", base = {pos = {x = 12, y = 43}},},
{name = "fennekin", base = {pos = {x = 14, y = 43}},},
{name = "braixen", base = {pos = {x = 16, y = 43}},},
{name = "delphox", base = {pos = {x = 18, y = 43}},},
{name = "froakie", base = {pos = {x = 20, y = 43}},},
{name = "frogadier", base = {pos = {x = 22, y = 43}},},
{name = "greninja", base = {pos = {x = 24, y = 43}},},
{name = "bunnelby", base = {pos = {x = 26, y = 43}},},
{name = "diggersby", base = {pos = {x = 28, y = 43}},},
{name = "fletchling", base = {pos = {x = 0, y = 44}}, alts = {AtlasJokersSeriesA = {artist = 'Alber_Pro'}}},
{name = "fletchinder", base = {pos = {x = 2, y = 44}}, alts = {AtlasJokersSeriesA = {artist = 'Alber_Pro'}}},
{name = "talonflame", base = {pos = {x = 4, y = 44}}, alts = {AtlasJokersSeriesA = {artist = 'Alber_Pro'}}},
{name = "scatterbug", base = {pos = {x = 6, y = 44}},},
{name = "spewpa", base = {pos = {x = 8, y = 44}},},
{name = "vivillon", base = {pos = {x = 10, y = 44}},},
{name = "litleo", base = {pos = {x = 12, y = 44}},alts = {AtlasJokersSeriesA = {artist = 'Xenellia'}}},
{name = "pyroar", base = {pos = {{x = 4, y = 3}, {x= 6, y = 3}}}, gen_atlas = 6,},
{name = "flabebe", base = {pos = {{x = 8, y = 3}, {x = 10, y = 3}, {x = 0, y = 4}, {x = 2, y = 4}, {x = 4, y = 4}}},gen_atlas = 6},
{name = "floette", base = {pos = {{x = 6, y = 4}, {x = 8, y = 4}, {x = 10, y = 4}, {x = 0, y = 5}, {x = 2, y = 5}}},gen_atlas = 6},
{name = "floette_eternal", base = {pos = {x = 4, y = 5}},gen_atlas = 6},
{name = "florges", base = {pos = {{x = 6, y = 5}, {x = 8, y = 5}, {x = 10, y = 5}, {x = 0, y = 5}, {x = 2, y = 5}}},gen_atlas = 6},
{name = "skiddo", base = {pos = {x = 22, y = 44}},},
{name = "gogoat", base = {pos = {x = 24, y = 44}},},
{name = "pancham", base = {pos = {x = 26, y = 44}},},
{name = "pangoro", base = {pos = {x = 28, y = 44}},},
{name = "furfrou", base = {pos = {x = 0, y = 45}},},
{name = "espurr", base = {pos = {x = 2, y = 45}},},
{name = "meowstic", base = {pos = {x = 4, y = 45}},},
{name = "honedge", base = {pos = {x = 6, y = 45}},},
{name = "doublade", base = {pos = {x = 8, y = 45}},},
{name = "aegislash", base = {pos = {x = 10, y = 45}},},
{name = "spritzee", base = {pos = {x = 12, y = 45}},},
{name = "aromatisse", base = {pos = {x = 14, y = 45}},},
{name = "swirlix", base = {pos = {x = 16, y = 45}},},
{name = "slurpuff", base = {pos = {x = 18, y = 45}},},
{name = "inkay", base = {pos = {x = 20, y = 45}},},
{name = "malamar", base = {pos = {x = 22, y = 45}},},
{name = "binacle", base = {pos = {x = 24, y = 45}},},
{name = "barbaracle", base = {pos = {x = 26, y = 45}},},
{name = "skrelp", base = {pos = {x = 28, y = 45}},},
{name = "dragalge", base = {pos = {x = 0, y = 46}},},
{name = "clauncher", base = {pos = {x = 2, y = 46}},},
{name = "clawitzer", base = {pos = {x = 4, y = 46}},},
{name = "helioptile", base = {pos = {x = 6, y = 46}},},
{name = "heliolisk", base = {pos = {x = 8, y = 46}},},
{name = "tyrunt", base = {pos = {x = 10, y = 46}},},
{name = "tyrantrum", base = {pos = {x = 12, y = 46}},},
{name = "amaura", base = {pos = {x = 14, y = 46}},},
{name = "aurorus", base = {pos = {x = 16, y = 46}},},
{name = "sylveon", base = {pos = {x = 18, y = 46}},},
{name = "hawlucha", base = {pos = {x = 20, y = 46}},},
{name = "dedenne", base = {pos = {x = 22, y = 46}},},
{name = "carbink", base = {pos = {x = 24, y = 46}},alts = {AtlasJokersSeriesA = {artist = 'MyDude_YT'}}},
{name = "goomy", base = {pos = {x = 26, y = 46}},},
{name = "sliggoo", base = {pos = {x = 28, y = 46}},},
{name = "hisuian_sliggoo", base = {pos = {x = 0, y = 12}},gen_atlas = 6},
{name = "goodra", base = {pos = {x = 0, y = 47}},},
{name = "hisuian_goodra", base = {pos = {x = 2, y = 12}},gen_atlas = 6},
{name = "klefki", base = {pos = {x = 2, y = 47}},},
{name = "phantump", base = {pos = {x = 4, y = 47}},},
{name = "trevenant", base = {pos = {x = 6, y = 47}},},
{name = "pumpkaboo", base = {pos = {x = 0, y = 9}},gen_atlas = 6},
{name = "gourgeist", base = {pos = {x = 8, y = 9}},gen_atlas = 6},
{name = "bergmite", base = {pos = {x = 12, y = 47}},},
{name = "avalugg", base = {pos = {x = 14, y = 47}},},
{name = "hisuian_avalugg", base = {pos = {x = 4, y = 12}},gen_atlas = 6},
{name = "noibat", base = {pos = {x = 16, y = 47}},},
{name = "noivern", base = {pos = {x = 18, y = 47}},},
{name = "xerneas", base = {pos = {x = 6, y = 10}, soul_pos = {x = 7, y = 10}},gen_atlas = 6},
{name = "yveltal", base = {pos = {x = 22, y = 47}, soul_pos = {x = 23, y = 47}},},
{name = "zygarde", base = {pos = {x = 2, y = 11}, soul_pos = {x = 3, y = 11}},gen_atlas = 6},
{name = "zygarde_10", base = {pos = {x = 0, y = 11}, soul_pos = {x = 1, y = 11}},gen_atlas = 6},
{name = "zygarde_complete", base = {pos = {x = 4, y = 11}, soul_pos = {x = 5, y = 11}},gen_atlas = 6},
{name = "diancie", base = {pos = {x = 26, y = 47}, soul_pos = {x = 27, y = 47}},},
{name = "mega_diancie", base = {pos = {x = 10, y = 11}, soul_pos = {x = 11, y = 11}},gen_atlas = 6},
{name = "hoopa", base = {pos = {x = 6, y = 11}, soul_pos = {x = 7, y = 11}},gen_atlas = 6},
{name = "hoopa_unbound", base = {pos = {x = 8, y = 11}, soul_pos = {x = 9, y = 11}},gen_atlas = 6},
{name = "volcanion", base = {pos = {x = 0, y = 48}, soul_pos = {x = 1, y = 48}},},
{name = "rowlet", base = {pos = {x = 2, y = 48}},},
{name = "dartrix", base = {pos = {x = 4, y = 48}},},
{name = "decidueye", base = {pos = {x = 6, y = 48}},},
{name = "hisuian_decidueye", base = {pos = {x = 6, y = 5}},gen_atlas = 7},
{name = "litten", base = {pos = {x = 8, y = 48}},},
{name = "torracat", base = {pos = {x = 10, y = 48}},},
{name = "incineroar", base = {pos = {x = 12, y = 48}},},
{name = "popplio", base = {pos = {x = 14, y = 48}},},
{name = "brionne", base = {pos = {x = 16, y = 48}},},
{name = "primarina", base = {pos = {x = 18, y = 48}},},
{name = "pikipek", base = {pos = {x = 20, y = 48}},},
{name = "trumbeak", base = {pos = {x = 22, y = 48}},},
{name = "toucannon", base = {pos = {x = 24, y = 48}},},
{name = "yungoos", base = {pos = {x = 26, y = 48}},},
{name = "gumshoos", base = {pos = {x = 28, y = 48}},},
{name = "grubbin", base = {pos = {x = 0, y = 49}}, alts= {AtlasJokersSeriesA = {artist = 'Gappie'}}},
{name = "charjabug", base = {pos = {x = 2, y = 49}}, alts= {AtlasJokersSeriesA = {artist = 'Gappie'}}},
{name = "vikavolt", base = {pos = {x = 4, y = 49}},},
{name = "crabrawler", base = {pos = {x = 6, y = 49}},},
{name = "crabominable", base = {pos = {x = 8, y = 49}},},
{name = "oricorio", base = {pos = {x = 10, y = 49}},},
{name = "cutiefly", base = {pos = {x = 12, y = 49}},},
{name = "ribombee", base = {pos = {x = 14, y = 49}},},
{name = "rockruff", base = {pos = {x = 16, y = 49}},},
{name = "lycanroc_day", base = {pos = {x = 8, y = 0}},gen_atlas = 7},
{name = "lycanroc_night", base = {pos = {x = 10, y = 0}},gen_atlas = 7},
{name = "lycanroc_dusk", base = {pos = {x = 0, y = 1}},gen_atlas = 7},
{name = "wishiwashi", base = {pos = {x = 20, y = 49}},},
{name = "mareanie", base = {pos = {x = 22, y = 49}},},
{name = "toxapex", base = {pos = {x = 24, y = 49}},},
{name = "mudbray", base = {pos = {x = 26, y = 49}},},
{name = "mudsdale", base = {pos = {x = 28, y = 49}},},
{name = "dewpider", base = {pos = {x = 0, y = 50}},alts= {AtlasJokersSeriesA = {artist = 'Gappie'}}},
{name = "araquanid", base = {pos = {x = 2, y = 50}},},
{name = "fomantis", base = {pos = {x = 4, y = 50}},},
{name = "lurantis", base = {pos = {x = 6, y = 50}},},
{name = "morelull", base = {pos = {x = 8, y = 50}},},
{name = "shiinotic", base = {pos = {x = 10, y = 50}},},
{name = "salandit", base = {pos = {x = 12, y = 50}},},
{name = "salazzle", base = {pos = {x = 14, y = 50}},},
{name = "stufful", base = {pos = {x = 16, y = 50}},},
{name = "bewear", base = {pos = {x = 18, y = 50}},},
{name = "bounsweet", base = {pos = {x = 20, y = 50}},},
{name = "steenee", base = {pos = {x = 22, y = 50}},},
{name = "tsareena", base = {pos = {x = 24, y = 50}},},
{name = "comfey", base = {pos = {x = 26, y = 50}},},
{name = "oranguru", base = {pos = {x = 28, y = 50}},},
{name = "passimian", base = {pos = {x = 0, y = 51}},},
{name = "wimpod", base = {pos = {x = 2, y = 51}},},
{name = "golisopod", base = {pos = {x = 4, y = 51}},},
{name = "sandygast", base = {pos = {x = 6, y = 51}},alts = {AtlasJokersSeriesA = {artist = 'Gappie'}}},
{name = "palossand", base = {pos = {x = 8, y = 51}},alts = {AtlasJokersSeriesA = {artist = 'Gappie'}}},
{name = "pyukumuku", base = {pos = {x = 10, y = 51}}, alts = {AtlasJokersSeriesA = {artist = 'Gappie'}}},
{name = "typenull", base = {pos = {x = 12, y = 51}, soul_pos =  {x = 13, y = 51}},},
{name = "silvally", base = {pos = {x = 6, y = 1}, soul_pos =  {x = 7, y = 1}},gen_atlas = 7},
{name = "minior", base = {pos = {x = 16, y = 51}, soul_pos =  {x = 17, y = 51}},},
{name = "komala", base = {pos = {x = 18, y = 51}},},
{name = "turtonator", base = {pos = {x = 20, y = 51}},},
{name = "togedemaru", base = {pos = {x = 22, y = 51}},},
{name = "mimikyu", base = {pos = {x = 24, y = 51}},lookup_gen_atlas = 7},
{name = "bruxish", base = {pos = {x = 26, y = 51}},},
{name = "drampa", base = {pos = {x = 28, y = 51}},},
{name = "dhelmise", base = {pos = {x = 0, y = 52}},},
{name = "jangmoo", base = {pos = {x = 2, y = 52}},},
{name = "hakamoo", base = {pos = {x = 4, y = 52}},},
{name = "kommoo", base = {pos = {x = 6, y = 52}},},
{name = "tapu_koko", base = {pos = {x = 8, y = 52}, soul_pos =  {x = 9, y = 52}},},
{name = "tapu_lele", base = {pos = {x = 10, y = 52}, soul_pos =  {x = 11, y = 52}},},
{name = "tapu_bulu", base = {pos = {x = 12, y = 52}, soul_pos =  {x = 13, y = 52}},},
{name = "tapu_fini", base = {pos = {x = 14, y = 52}, soul_pos =  {x = 15, y = 52}},},
{name = "cosmog", base = {pos = {x = 16, y = 52}, soul_pos =  {x = 17, y = 52}},},
{name = "cosmoem", base = {pos = {x = 18, y = 52}, soul_pos =  {x = 19, y = 52}},},
{name = "solgaleo", base = {pos = {x = 20, y = 52}, soul_pos =  {x = 21, y = 52}},},
{name = "lunala", base = {pos = {x = 22, y = 52}, soul_pos =  {x = 23, y = 52}},},
{name = "nihilego", base = {pos = {x = 24, y = 52}, soul_pos =  {x = 25, y = 52}},},
{name = "buzzwole", base = {pos = {x = 26, y = 52}, soul_pos =  {x = 27, y = 52}},},
{name = "pheromosa", base = {pos = {x = 28, y = 52}, soul_pos =  {x = 29, y = 52}},},
{name = "xurkitree", base = {pos = {x = 0, y = 53}, soul_pos =  {x = 1, y = 53}},},
{name = "celesteela", base = {pos = {x = 2, y = 53}, soul_pos =  {x = 3, y = 53}},},
{name = "kartana", base = {pos = {x = 4, y = 53}, soul_pos =  {x = 5, y = 53}},},
{name = "guzzlord", base = {pos = {x = 6, y = 53}, soul_pos =  {x = 7, y = 53}},},
{name = "necrozma", base = {pos = {x = 6, y = 4}, soul_pos =  {x = 7, y = 4}},gen_atlas = 7},
{name = "necrozma_dusk_mane", base = {pos = {x = 8, y = 4}, soul_pos =  {x = 9, y = 4}},gen_atlas = 7},
{name = "necrozma_dawn_wings", base = {pos = {x = 10, y = 4}, soul_pos =  {x = 11, y = 4}},gen_atlas = 7},
{name = "ultra_necrozma", base = {pos = {x = 0, y = 5}, soul_pos =  {x = 1, y = 5}},gen_atlas = 7},
{name = "magearna", base = {pos = {x = 10, y = 53}, soul_pos =  {x = 11, y = 53}},},
{name = "marshadow", base = {pos = {x = 2, y = 5}, soul_pos =  {x = 3, y = 5}},gen_atlas = 7},
{name = "poipole", base = {pos = {x = 14, y = 53}, soul_pos =  {x = 15, y = 53}},},
{name = "naganadel", base = {pos = {x = 16, y = 53}, soul_pos =  {x = 17, y = 53}},},
{name = "stakataka", base = {pos = {x = 18, y = 53}, soul_pos =  {x = 19, y = 53}},},
{name = "blacephalon", base = {pos = {x = 20, y = 53}, soul_pos =  {x = 21, y = 53}},},
{name = "zeraora", base = {pos = {x = 22, y = 53}, soul_pos =  {x = 23, y = 53}},},
{name = "meltan", base = {pos = {x = 24, y = 53}, soul_pos =  {x = 25, y = 53}},},
{name = "melmetal", base = {pos = {x = 26, y = 53}, soul_pos =  {x = 27, y = 53}},},
{name = "gmax_melmetal", base = {pos = {x = 8, y = 5}, soul_pos =  {x = 9, y = 5}},gen_atlas = 7},
{name = "grookey", base = {pos = {x = 28, y = 53}},},
{name = "thwackey", base = {pos = {x = 0, y = 54}},},
{name = "rillaboom", base = {pos = {x = 2, y = 54}},},
{name = "gmax_rillaboom", base = {pos = {x = 10, y = 11}, soul_pos = {x = 11, y = 11}},gen_atlas = 8},
{name = "scorbunny", base = {pos = {x = 4, y = 54}},},
{name = "raboot", base = {pos = {x = 6, y = 54}},},
{name = "cinderace", base = {pos = {x = 8, y = 54}},},
{name = "gmax_cinderace", base = {pos = {x = 12, y = 11}, soul_pos = {x = 13, y = 11}},gen_atlas = 8},
{name = "sobble", base = {pos = {x = 10, y = 54}},},
{name = "drizzile", base = {pos = {x = 12, y = 54}},},
{name = "inteleon", base = {pos = {x = 14, y = 54}},},
{name = "gmax_inteleon", base = {pos = {x = 14, y = 11}, soul_pos = {x = 15, y = 11}},gen_atlas = 8},
{name = "skwovet", base = {pos = {x = 16, y = 54}},},
{name = "greedent", base = {pos = {x = 18, y = 54}},},
{name = "rookidee", base = {pos = {x = 20, y = 54}},},
{name = "corvisquire", base = {pos = {x = 22, y = 54}},},
{name = "corviknight", base = {pos = {x = 24, y = 54}},},
{name = "gmax_corviknight", base = {pos = {x = 0, y = 12}, soul_pos = {x = 1, y = 12}},gen_atlas = 8},
{name = "blipbug", base = {pos = {x = 26, y = 54}},},
{name = "dottler", base = {pos = {x = 28, y = 54}},},
{name = "orbeetle", base = {pos = {x = 0, y = 55}},},
{name = "gmax_orbeetle", base = {pos = {x = 2, y = 12}, soul_pos = {x = 3, y = 12}},gen_atlas = 8},
{name = "nickit", base = {pos = {x = 2, y = 55}},},
{name = "thievul", base = {pos = {x = 4, y = 55}},},
{name = "gossifleur", base = {pos = {x = 6, y = 55}},},
{name = "eldegoss", base = {pos = {x = 8, y = 55}},},
{name = "wooloo", base = {pos = {x = 10, y = 55}},},
{name = "dubwool", base = {pos = {x = 12, y = 55}},},
{name = "chewtle", base = {pos = {x = 14, y = 55}},},
{name = "drednaw", base = {pos = {x = 16, y = 55}},},
{name = "gmax_drednaw", base = {pos = {x = 4, y = 12}, soul_pos = {x = 5, y = 12}},gen_atlas = 8},
{name = "yamper", base = {pos = {x = 18, y = 55}},},
{name = "boltund", base = {pos = {x = 20, y = 55}},},
{name = "rolycoly", base = {pos = {x = 22, y = 55}},},
{name = "carkol", base = {pos = {x = 24, y = 55}},},
{name = "coalossal", base = {pos = {x = 26, y = 55}},},
{name = "gmax_coalossal", base = {pos = {x = 6, y = 12}, soul_pos = {x = 7, y = 12}},gen_atlas = 8},
{name = "applin", base = {pos = {x = 28, y = 55}},},
{name = "flapple", base = {pos = {x = 0, y = 56}},alts = {AtlasJokersSeriesA = {artist = 'Celsie_RS'}}},
{name = "gmax_flapple", base = {pos = {x = 8, y = 12}, soul_pos = {x = 9, y = 12}},gen_atlas = 8},
{name = "appletun", base = {pos = {x = 2, y = 56}},},
{name = "gmax_appletun", base = {pos = {x = 10, y = 12}, soul_pos = {x = 11, y = 12}},gen_atlas = 8},
{name = "silicobra", base = {pos = {x = 4, y = 56}},},
{name = "sandaconda", base = {pos = {x = 6, y = 56}},},
{name = "gmax_sandaconda", base = {pos = {x = 12, y = 12}, soul_pos = {x = 13, y = 12}},gen_atlas = 8},
{name = "cramorant", base = {pos = {x = 0, y = 0}},gen_atlas = 8},
{name = "arrokuda", base = {pos = {x = 10, y = 56}},},
{name = "barraskewda", base = {pos = {x = 12, y = 56}},},
{name = "toxel", base = {pos = {x = 14, y = 56}},},
{name = "toxtricity", base = {pos = {x = 16, y = 56}},},
{name = "gmax_toxtricity", base = {pos = {x = 14, y = 12}, soul_pos = {x = 15, y = 12}},gen_atlas = 8},
{name = "sizzlipede", base = {pos = {x = 18, y = 56}},},
{name = "centiskorch", base = {pos = {x = 20, y = 56}},},
{name = "gmax_centiskorch", base = {pos = {x = 0, y = 13}, soul_pos = {x = 1, y = 13}},gen_atlas = 8},
{name = "clobbopus", base = {pos = {x = 22, y = 56}},},
{name = "grapploct", base = {pos = {x = 24, y = 56}},},
{name = "sinistea", base = {pos = {x = 26, y = 56}},},
{name = "polteageist", base = {pos = {x = 28, y = 56}},},
{name = "hatenna", base = {pos = {x = 0, y = 57}},},
{name = "hattrem", base = {pos = {x = 2, y = 57}},},
{name = "hatterene", base = {pos = {x = 4, y = 57}},},
{name = "gmax_hatterene", base = {pos = {x = 2, y = 13}, soul_pos = {x = 3, y = 13}},gen_atlas = 8},
{name = "impidimp", base = {pos = {x = 6, y = 57}},},
{name = "morgrem", base = {pos = {x = 8, y = 57}},},
{name = "grimmsnarl", base = {pos = {x = 10, y = 57}},},
{name = "gmax_grimmsnarl", base = {pos = {x = 4, y = 13}, soul_pos = {x = 5, y = 13}},gen_atlas = 8},
{name = "obstagoon", base = {pos = {x = 12, y = 57}},},
{name = "perrserker", base = {pos = {x = 14, y = 57}},},
{name = "cursola", base = {pos = {x = 16, y = 57}},},
{name = "sirfetchd", base = {pos = {x = 18, y = 57}},},
{name = "mrrime", base = {pos = {x = 20, y = 57}},},
{name = "runerigus", base = {pos = {x = 22, y = 57}},},
{name = "milcery", base = {pos = {x = 24, y = 57}},},
{name = "alcremie", base = {pos = {x = 26, y = 57}},},
{name = "gmax_alcremie", base = {pos = {x = 6, y = 13}, soul_pos = {x = 7, y = 13}},gen_atlas = 8},
{name = "falinks", base = {pos = {x = 28, y = 57}},},
{name = "pincurchin", base = {pos = {x = 0, y = 58}},},
{name = "snom", base = {pos = {x = 2, y = 58}},},
{name = "frosmoth", base = {pos = {x = 4, y = 58}},},
{name = "stonjourner", base = {pos = {x = 6, y = 58}},},
{name = "eiscue", base = {pos = {x = 8, y = 58}},},
{name = "indeedee", base = {pos = {x = 10, y = 58}},},
{name = "morpeko", base = {pos = {x = 12, y = 58}},},
{name = "cufant", base = {pos = {x = 14, y = 58}},},
{name = "copperajah", base = {pos = {x = 16, y = 58}},},
{name = "gmax_copperajah", base = {pos = {x = 8, y = 13}, soul_pos = {x = 9, y = 13}},gen_atlas = 8},
{name = "dracozolt", base = {pos = {x = 18, y = 58}},},
{name = "arctozolt", base = {pos = {x = 20, y = 58}},},
{name = "dracovish", base = {pos = {x = 22, y = 58}},},
{name = "arctovish", base = {pos = {x = 24, y = 58}},},
{name = "duraludon", base = {pos = {x = 26, y = 58}},},
{name = "gmax_duraludon", base = {pos = {x = 10, y = 13}, soul_pos = {x = 11, y = 13}},gen_atlas = 8},
{name = "dreepy", base = {pos = {x = 28, y = 58}},},
{name = "dreepy_dart", base = {pos = {x = 4, y = 9}},gen_atlas = 8},
{name = "drakloak", base = {pos = {x = 0, y = 59}},},
{name = "dragapult", base = {pos = {x = 2, y = 59}},},
{name = "zacian", base = {pos = {x = 6, y = 9}, soul_pos =  {x = 7, y = 9}},gen_atlas = 8},
{name = "zacian_crowned", base = {pos = {x = 8, y = 9}, soul_pos =  {x = 9, y = 9}},gen_atlas = 8},
{name = "zamazenta", base = {pos = {x = 10, y = 9}, soul_pos =  {x = 11, y = 9}},gen_atlas = 8},
{name = "zamazenta_crowned", base = {pos = {x = 12, y = 9}, soul_pos =  {x = 13, y = 9}},gen_atlas = 8},
{name = "eternatus", base = {pos = {x = 8, y = 59}, soul_pos =  {x = 9, y = 59}},},
{name = "eternamax_eternatus", base = {pos = {x = 0, y = 10}, soul_pos = {x = 1, y = 10}},gen_atlas = 8},
{name = "kubfu", base = {pos = {x = 10, y = 59}, soul_pos =  {x = 11, y = 59}},},
{name = "urshifu_single_strike", base = {pos = {x = 2, y = 10}, soul_pos = {x = 3, y = 10}},gen_atlas = 8},
{name = "urshifu_rapid_strike", base = {pos = {x = 4, y = 10}, soul_pos = {x = 5, y = 10}},gen_atlas = 8},
{name = "gmax_urshifu_single_strike", base = {pos = {x = 12, y = 13}, soul_pos = {x = 13, y = 13}},gen_atlas = 8},
{name = "gmax_urshifu_rapid_strike", base = {pos = {x = 14, y = 13}, soul_pos = {x = 15, y = 13}},gen_atlas = 8},
{name = "zarude", base = {pos = {x = 6, y = 10}, soul_pos =  {x = 7, y = 10}},gen_atlas = 8},
{name = "regieleki", base = {pos = {x = 16, y = 59}, soul_pos =  {x = 17, y = 59}},},
{name = "regidrago", base = {pos = {x = 18, y = 59}, soul_pos =  {x = 19, y = 59}},},
{name = "glastrier", base = {pos = {x = 20, y = 59}, soul_pos =  {x = 21, y = 59}},},
{name = "spectrier", base = {pos = {x = 22, y = 59}, soul_pos =  {x = 23, y = 59}},},
{name = "calyrex", base = {pos = {x = 10, y = 10}, soul_pos =  {x = 11, y = 10}},gen_atlas = 8},
{name = "calyrex_ice", base = {pos = {x = 12, y = 10}, soul_pos =  {x = 13, y = 10}},gen_atlas = 8},
{name = "calyrex_shadow", base = {pos = {x = 14, y = 10}, soul_pos =  {x = 15, y = 10}},gen_atlas = 8},
{name = "wyrdeer", base = {pos = {x = 26, y = 59}},},
{name = "kleavor", base = {pos = {x = 28, y = 59}},},
{name = "ursaluna", base = {pos = {x = 0, y = 60}},},
{name = "bloodmoon_ursaluna", base = {pos = {x = 0, y = 11}},gen_atlas = 8},
{name = "basculegion", base = {pos = {x = 2, y = 60}},},
{name = "sneasler", base = {pos = {x = 4, y = 60}},},
{name = "overqwil", base = {pos = {x = 6, y = 60}},},
{name = "enamorus", base = {pos = {x = 6, y = 11}, soul_pos =  {x = 7, y = 11}},gen_atlas = 8},
{name = "enamorus_therian", base = {pos = {x = 8, y = 11}, soul_pos =  {x = 9, y = 11}},gen_atlas = 8},
{name = "sprigatito", base = {pos = {x = 10, y = 60}},},
{name = "floragato", base = {pos = {x = 12, y = 60}},},
{name = "meowscarada", base = {pos = {x = 14, y = 60}},},
{name = "fuecoco", base = {pos = {x = 16, y = 60}},},
{name = "crocalor", base = {pos = {x = 18, y = 60}},},
{name = "skeledirge", base = {pos = {x = 20, y = 60}},},
{name = "quaxly", base = {pos = {x = 22, y = 60}},},
{name = "quaxwell", base = {pos = {x = 24, y = 60}},},
{name = "quaquaval", base = {pos = {x = 26, y = 60}},},
{name = "lechonk", base = {pos = {x = 28, y = 60}},alts = {AtlasJokersSeriesA = {artist = 'Sonfive'}}},
{name = "oinkologne", base = {pos = {x = 0, y = 61}},},
{name = "tarountula", base = {pos = {x = 2, y = 61}},},
{name = "spidops", base = {pos = {x = 4, y = 61}},},
{name = "nymble", base = {pos = {x = 6, y = 61}},},
{name = "lokix", base = {pos = {x = 8, y = 61}},},
{name = "pawmi", base = {pos = {x = 10, y = 61}},},
{name = "pawmo", base = {pos = {x = 12, y = 61}},},
{name = "pawmot", base = {pos = {x = 14, y = 61}},},
{name = "tandemaus", base = {pos = {x = 16, y = 61}},},
{name = "maushold", base = {pos = {x = 18, y = 61}},},
{name = "fidough", base = {pos = {x = 20, y = 61}},},
{name = "dachsbun", base = {pos = {x = 22, y = 61}},},
{name = "smoliv", base = {pos = {x = 24, y = 61}},},
{name = "dolliv", base = {pos = {x = 26, y = 61}},},
{name = "arboliva", base = {pos = {x = 28, y = 61}},},
{name = "squawkabilly", base = {pos = {x = 0, y = 62}},},
{name = "nacli", base = {pos = {x = 2, y = 62}},},
{name = "naclstack", base = {pos = {x = 4, y = 62}},},
{name = "garganacl", base = {pos = {x = 6, y = 62}},},
{name = "charcadet", base = {pos = {x = 8, y = 62}},},
{name = "armarouge", base = {pos = {x = 10, y = 62}},},
{name = "ceruledge", base = {pos = {x = 12, y = 62}},},
{name = "tadbulb", base = {pos = {x = 14, y = 62}},},
{name = "bellibolt", base = {pos = {x = 16, y = 62}},},
{name = "wattrel", base = {pos = {x = 18, y = 62}},},
{name = "kilowattrel", base = {pos = {x = 20, y = 62}},},
{name = "maschiff", base = {pos = {x = 22, y = 62}},},
{name = "mabosstiff", base = {pos = {x = 24, y = 62}},},
{name = "shroodle", base = {pos = {x = 26, y = 62}},},
{name = "grafaiai", base = {pos = {x = 28, y = 62}},},
{name = "bramblin", base = {pos = {x = 0, y = 63}},},
{name = "brambleghast", base = {pos = {x = 2, y = 63}},},
{name = "toedscool", base = {pos = {x = 4, y = 63}},},
{name = "toedscruel", base = {pos = {x = 6, y = 63}},},
{name = "klawf", base = {pos = {x = 8, y = 63}},},
{name = "capsakid", base = {pos = {x = 10, y = 63}},},
{name = "scovillain", base = {pos = {x = 12, y = 63}},},
{name = "rellor", base = {pos = {x = 14, y = 63}},},
{name = "rabsca", base = {pos = {x = 16, y = 63}},},
{name = "flittle", base = {pos = {x = 18, y = 63}},},
{name = "espathra", base = {pos = {x = 20, y = 63}},},
{name = "tinkatink", base = {pos = {x = 22, y = 63}},},
{name = "tinkatuff", base = {pos = {x = 24, y = 63}},},
{name = "tinkaton", base = {pos = {x = 26, y = 63}},},
{name = "wiglett", base = {pos = {x = 28, y = 63}},},
{name = "wugtrio", base = {pos = {x = 0, y = 64}},},
{name = "bombirdier", base = {pos = {x = 2, y = 64}},},
{name = "finizen", base = {pos = {x = 4, y = 64}},},
{name = "palafin", base = {pos = {x = 6, y = 64}},},
{name = "varoom", base = {pos = {x = 8, y = 64}},},
{name = "revavroom", base = {pos = {x = 10, y = 64}},},
{name = "cyclizar", base = {pos = {x = 12, y = 64}},},
{name = "orthworm", base = {pos = {x = 14, y = 64}},},
{name = "glimmet", base = {pos = {x = 16, y = 64}},},
{name = "glimmora", base = {pos = {x = 18, y = 64}},},
{name = "greavard", base = {pos = {x = 20, y = 64}},},
{name = "houndstone", base = {pos = {x = 22, y = 64}},},
{name = "flamigo", base = {pos = {x = 24, y = 64}},},
{name = "cetoddle", base = {pos = {x = 26, y = 64}},alts = {AtlasJokersSeriesA = {artist = {'Sonfive', 'Ayako Ozaki'}}}},
{name = "cetitan", base = {pos = {x = 28, y = 64}},},
{name = "veluza", base = {pos = {x = 0, y = 65}},},
{name = "dondozo", base = {pos = {x = 2, y = 65}},},
{name = "tatsugiri", base = {pos = {x = 4, y = 65}},},
{name = "annihilape", base = {pos = {x = 6, y = 65}},},
{name = "clodsire", base = {pos = {x = 8, y = 65}},},
{name = "farigiraf", base = {pos = {x = 10, y = 65}},},
{name = "dudunsparce", base = {pos = {x = 6, y = 3}}, gen_atlas = 9,},
{name = "kingambit", base = {pos = {x = 14, y = 65}},},
{name = "great_tusk", base = {pos = {x = 16, y = 65}, soul_pos =  {x = 17, y = 65}},},
{name = "scream_tail", base = {pos = {x = 18, y = 65}, soul_pos =  {x = 19, y = 65}},},
{name = "brute_bonnet", base = {pos = {x = 20, y = 65}, soul_pos =  {x = 21, y = 65}},},
{name = "flutter_mane", base = {pos = {x = 22, y = 65}, soul_pos =  {x = 23, y = 65}},},
{name = "slither_wing", base = {pos = {x = 24, y = 65}, soul_pos =  {x = 25, y = 65}},},
{name = "sandy_shocks", base = {pos = {x = 26, y = 65}, soul_pos =  {x = 27, y = 65}},},
{name = "iron_treads", base = {pos = {x = 28, y = 65}, soul_pos =  {x = 29, y = 65}},},
{name = "iron_bundle", base = {pos = {x = 0, y = 66}, soul_pos =  {x = 1, y = 66}},},
{name = "iron_hands", base = {pos = {x = 2, y = 66}, soul_pos =  {x = 3, y = 66}},},
{name = "iron_jugulis", base = {pos = {x = 4, y = 66}, soul_pos =  {x = 5, y = 66}},},
{name = "iron_moth", base = {pos = {x = 6, y = 66}, soul_pos =  {x = 7, y = 66}},},
{name = "iron_thorns", base = {pos = {x = 8, y = 66}, soul_pos =  {x = 9, y = 66}},},
{name = "frigibax", base = {pos = {x = 10, y = 66}},},
{name = "arctibax", base = {pos = {x = 12, y = 66}},},
{name = "baxcalibur", base = {pos = {x = 14, y = 66}},},
{name = "gimmighoul", base = {pos = {x = 16, y = 66}},},
{name = "gimmighoulr", base = {pos = {x = 0, y = 4}}, gen_atlas = 9,},
{name = "gholdengo", base = {pos = {x = 18, y = 66}},},
{name = "wochien", base = {pos = {x = 20, y = 66}, soul_pos =  {x = 21, y = 66}},},
{name = "chienpao", base = {pos = {x = 22, y = 66}, soul_pos =  {x = 23, y = 66}},},
{name = "tinglu", base = {pos = {x = 24, y = 66}, soul_pos =  {x = 25, y = 66}},},
{name = "chiyu", base = {pos = {x = 26, y = 66}, soul_pos =  {x = 27, y = 66}},},
{name = "roaring_moon", base = {pos = {x = 28, y = 66}, soul_pos =  {x = 29, y = 66}},},
{name = "iron_valiant", base = {pos = {x = 0, y = 67}, soul_pos =  {x = 1, y = 67}},},
{name = "koraidon", base = {pos = {x = 2, y = 67}, soul_pos =  {x = 1, y = 67}},},
{name = "miraidon", base = {pos = {x = 4, y = 67}, soul_pos =  {x = 3, y = 67}},},
{name = "walking_wake", base = {pos = {x = 6, y = 67}, soul_pos =  {x = 5, y = 67}},},
{name = "iron_leaves", base = {pos = {x = 8, y = 67}, soul_pos =  {x = 7, y = 67}},},
{name = "dipplin", base = {pos = {x = 10, y = 67}},},
{name = "poltchageist", base = {pos = {x = 12, y = 67}},},
{name = "sinistcha", base = {pos = {x = 14, y = 67}},},
{name = "okidogi", base = {pos = {x = 16, y = 67}, soul_pos =  {x = 17, y = 67}},},
{name = "munkidori", base = {pos = {x = 18, y = 67}, soul_pos =  {x = 19, y = 67}},},
{name = "fezandipiti", base = {pos = {x = 20, y = 67}, soul_pos =  {x = 21, y = 67}},},
{name = "ogerpon", base = {pos = {x = 4, y = 4}, soul_pos =  {x = 5, y = 4}},gen_atlas = 9},
{name = "ogerpon_wellspring", base = {pos = {x = 2, y = 5}, soul_pos =  {x = 3, y = 5}},gen_atlas = 9},
{name = "ogerpon_hearthflame", base = {pos = {x = 8, y = 4}, soul_pos =  {x = 9, y = 4}},gen_atlas = 9},
{name = "ogerpon_cornerstone", base = {pos = {x = 6, y = 5}, soul_pos =  {x = 7, y = 5}},gen_atlas = 9},
{name = "archaludon", base = {pos = {x = 24, y = 67}},},
{name = "hydrapple", base = {pos = {x = 26, y = 67}},},
{name = "gouging_fire", base = {pos = {x = 28, y = 67}, soul_pos =  {x = 29, y = 67}},},
{name = "raging_bolt", base = {pos = {x = 0, y = 68}, soul_pos =  {x = 1, y = 68}},},
{name = "iron_boulder", base = {pos = {x = 2, y = 68}, soul_pos =  {x = 3, y = 68}},},
{name = "iron_crown", base = {pos = {x = 4, y = 68}, soul_pos =  {x = 5, y = 68}},},
{name = "terapagos", base = {pos = {x = 0, y = 6}, soul_pos =  {x = 1, y = 6}},gen_atlas = 9},
{name = "terapagos_terastal", base = {pos = {x = 2, y = 6}, soul_pos =  {x = 3, y = 6}},gen_atlas = 9},
{name = "terapagos_stellar", base = {pos = {x = 4, y = 6}, soul_pos =  {x = 5, y = 6}},gen_atlas = 9},
{name = "pecharunt", base = {pos = {x = 8, y = 68}, soul_pos =  {x = 9, y = 68}},},
{name = "pokedex", base = {pos = {x = 0, y = 0}}, others_atlas = true,},
{name = "rotomdex", base = {pos = {x = 0, y = 4}}, others_atlas = true,},
{name = "everstone", base = {pos = {x = 2, y = 0}}, others_atlas = true,},
{name = "tall_grass", base = {pos = {x = 4, y = 0}}, others_atlas = true,},
{name = "jelly_donut", base = {pos = {x = 6, y = 0}}, others_atlas = true,},
{name = "treasure_eatery", base = {pos = {x = 6, y = 2}}, others_atlas = true,},
{name = "mystery_egg", base = {pos = {x = 0, y = 1}}, others_atlas = true,},
{name = "rival", base = {pos = {x = 0, y = 2}}, others_atlas = true,},
{name = "ruins_of_alph", base = {pos = {x = 0, y = 3}}, others_atlas = true,},
{name = "professor", base = {pos = {x = 4, y = 1}}, others_atlas = true,},
{name = "billion_lions", base = {pos = {x = 4, y = 3}, soul_pos = {x = 5, y = 3}}, others_atlas = true,},
  }
}

for i, sprite in ipairs(PokemonSprites.list) do
  PokemonSprites.lookup[sprite.name] = i
end

setmetatable(PokemonSprites, {
  __index = function(_, key)
    return PokemonSprites.list[PokemonSprites.lookup[key]]
  end
})

local poke_artist_info = {
  Alber_Pro = {display_name = 'Alber_Pro', artist_colour = HEX('FFAE00'), links = {
    {url = 'https://discord.com/users/348471005704093697', account = 'alber_propoke'}
  }},
  bt = {display_name = 'bt', artist_colour = HEX("2C4522"), highlight_colour = HEX("efead8")},
  Captain_Slime = {display_name = 'Captain Slime', artist_colour = HEX("F7C429")},
  Catzzadilla = {display_name = 'Catzzadilla', artist_colour = HEX("F3CC3C"), highlight_colour = HEX("A400FF")},
  CBMX = {display_name = 'CBMX', artist_colour = HEX("FFFFFF"), highlight_colour = HEX("27BBF5")},
  Celsie_RS = {display_name = 'Celsie_RS', artist_colour = HEX("FA8F0B")},
  Chartreuse_Chamber = {display_name = 'Chartreuse Chamber', artist_colour = HEX("B0D820")},
  Desnik = {display_name = 'Desnik', artist_colour = HEX("FDDF00")},
  Dudelings = {display_name = 'Dudelings', artist_colour = HEX("F0493A"), links = {
    {url = 'https://dudelings.carrd.co/', account = 'Dudelings'}
  }},
  Gappie = {display_name = 'Gappie', artist_colour = HEX('FFE062')},
  InertSteak = {display_name = 'InertSteak', artist_colour = HEX('77A5BC'), highlight_colour = HEX('C1C3C2')},
  Maelmc = {display_name = 'Maelmc', artist_colour = HEX("EA6F22")},
  MyDude_YT = {display_name = 'MyDude YT', artist_colour = HEX("FFFFFF"), highlight_colour = HEX("4428BC"), links = {
  {url = 'https://www.youtube.com/@mydudestudios6244', account = 'MyDude Studios'},
  {url = 'https://www.reddit.com/user/My_Dude_CBC/', account = 'My_Dude_CBC'},
  {url = 'https://x.com/MyDude81058128'},
  {url = 'https://steamcommunity.com/profiles/76561198905899441',site = 'Steam', account = 'MyDude'},
  {url = 'https://pacmanforever.itch.io/', account = 'My Dude Studios', site = 'Itch.io', colour = HEX("FA5C5C")}

  }},
  PrincessRoxie = {display_name = 'PrincessRoxie', artist_colour = HEX("FF88FF")},
  RedHaering = {display_name = 'RedHaering', artist_colour = HEX("D44540"), links = {
    {url = 'https://redhaering.carrd.co/', account = 'RedHaering'}
  }},
  RibbonOnline = {display_name = 'RibbonOnline', artist_colour = HEX("F11250")},
  Sonfive = {display_name = 'Sonfive', artist_colour = HEX("87DEFF")},
  Silverfish07 = {display_name = 'Silverfish07', artist_colour = HEX('FFAE00')},
  Sunny = {display_name = 'Sunny', artist_colour = HEX("078D70"), highlight_colour = HEX("98E8C1"), links = {
    {url = 'https://x.com/sunnydasun1'},
    {url = 'https://discord.com/users/997552363940368426', account = 'sunny_draws'}
  }},
  Tovivi = {display_name = 'Tovivi', artist_colour = HEX("FFF700")},
  TunaBear = {display_name = 'TunaBear', artist_colour = HEX("5FEDED")},
  Xenellia = {display_name = 'Xenellia', artist_colour = HEX("9B0000")}
}

poke_load_sprites = function(item)
  local sprite_info = PokemonSprites[item.name]
  local sprite = nil
  local new_pos = {}
  if sprite_info then
    sprite = pokermon_config.pokemon_altart and sprite_info.alt or sprite_info.base
    local position = sprite.pos.x and sprite.pos or nil
    if not position then
      position = sprite.pos[math.random(#sprite.pos)]
      new_pos.x = position.x
      new_pos.y = position.y
      item.poke_multi_sprite = true
    else
      new_pos.x = position.x
      new_pos.y = position.y
    end
    local soul_position = sprite.soul_pos
    
    if position then item.pos = new_pos end
    if soul_position then item.soul_pos = soul_position end
  end
end

poke_get_atlas_prefix = function(name, sprite_info)
  local atlas_prefix = nil
  if pokermon_config.pokemon_spritesheet_overrides[name] then return pokermon_config.pokemon_spritesheet_overrides[name] end
  if sprite_info.alts and sprite_info.alts[pokermon_config.pokemon_spritesheet_atlas] then
    atlas_prefix = pokermon_config.pokemon_spritesheet_atlas
  else
    atlas_prefix = "AtlasJokersBasic"
  end
  return atlas_prefix
end

poke_get_atlas_string = function(atlas_prefix, gen_atlas, others_atlas)
  if gen_atlas then
    local gen_string
    if gen_atlas < 10 then
      gen_string = 'Gen0'..gen_atlas
    else
      gen_string = 'Gen'..gen_atlas
    end
    return atlas_prefix..gen_string
  elseif others_atlas then
    return atlas_prefix.."Others"
  else
    return atlas_prefix.."Natdex"
  end
end

poke_load_atlas = function(item)
  if not item.poke_custom_atlas and PokemonSprites[item.name] then
    local sprite_info = PokemonSprites[item.name]
    local atlas_prefix = poke_get_atlas_prefix(item.name, sprite_info)
    if sprite_info.alts and sprite_info.alts[atlas_prefix] and sprite_info.alts[atlas_prefix].artist then
      item.artist = sprite_info.alts[atlas_prefix].artist
      if sprite_info.alts[atlas_prefix].soul_pos then
        item.soul_pos = sprite_info.alts[atlas_prefix].soul_pos
      end
      if sprite_info.alts[atlas_prefix].anim_atlas then
        item.animated = true
        item.atlas = sprite_info.alts[atlas_prefix].anim_atlas
        item.pos = {x = 0, y = 0}
      end
    end
    if not item.animated then
      item.atlas = poke_get_atlas_string(atlas_prefix, sprite_info.gen_atlas, sprite_info.others_atlas)
      if sprite_info.lookup_gen_atlas then
        item.poke_lookup_atlas = poke_get_atlas_string(atlas_prefix, sprite_info.lookup_gen_atlas)
      end
    end
  end
end

poke_get_artist_info = function(name)
  return poke_artist_info[name]
end

poke_get_artist_list = function()
  local list = {}
  for artist, _ in pairs(poke_artist_info) do
    list[#list+1] = artist
  end
  table.sort(list, function(a,b) return a:lower() < b:lower() end)
  return list
end

function poke_get_artist_layer(obj, by_artist)
  local artists = (type(obj.artist) == 'table' and not obj.artist.name)
      and obj.artist
      or { obj.artist }

  for _, _artist in ipairs(artists) do
    local artist_name = type(_artist) == 'table' and _artist.name or _artist
    if by_artist == artist_name then
      return _artist.layer or 'both'
    end
  end
end

poke_get_artist_sprites = function(artist)
  local sprites = {}

  for _, sprite in ipairs(PokemonSprites.list) do

    if sprite.alts then
      for atlas_prefix, alt in pairs(sprite.alts) do
        local layer = poke_get_artist_layer(alt, artist)

        if layer then
          table.insert(sprites, {
            name = sprite.name,
            pos = sprite.base.pos,
            soul_pos = alt.soul_pos or sprite.base.soul_pos,
            atlas_prefix = atlas_prefix,
            gen_atlas = sprite.gen_atlas,
            others_atlas = sprite.others_atlas,
            anim_atlas = alt.anim_atlas,
            layer = layer
          })
        end
      end
    end
  end

  return sprites
end
