PokemonSprites = {
bulbasaur = {base = {pos = {x = 0, y = 0}},},
ivysaur = {base = {pos = {x = 2, y = 0}},},
venusaur = {base = {pos = {x = 4, y = 0}},},
mega_venusaur = {base = {pos = {x = 4, y = 0}, soul_pos = {x = 5, y = 0}},gen_atlas = true},
charmander = {base = {pos = {x = 6, y = 0}},},
charmeleon = {base = {pos = {x = 8, y = 0}},},
charizard = {base = {pos = {x = 10, y = 0}},},
mega_charizard_x = {base = {pos = {x = 6, y = 0}, soul_pos = {x = 7, y = 0}},gen_atlas = true},
mega_charizard_y = {base = {pos = {x = 8, y = 0}, soul_pos = {x = 9, y = 0}},gen_atlas = true},
squirtle = {base = {pos = {x = 12, y = 0}},},
wartortle = {base = {pos = {x = 14, y = 0}},},
blastoise = {base = {pos = {x = 16, y = 0}},},
mega_blastoise = {base = {pos = {x = 10, y = 0}, soul_pos = {x = 11, y = 0}},gen_atlas = true},
caterpie = {base = {pos = {x = 18, y = 0}}, alts = {AtlasJokersSeriesA = {artist = 'RedHaering'}}},
metapod = {base = {pos = {x = 20, y = 0}},},
butterfree = {base = {pos = {x = 22, y = 0}},},
weedle = {base = {pos = {x = 24, y = 0}},},
kakuna = {base = {pos = {x = 26, y = 0}},},
beedrill = {base = {pos = {x = 28, y = 0}},},
mega_beedrill = {base = {pos = {x = 12, y = 0}, soul_pos = {x = 13, y = 0}},gen_atlas = true},
pidgey = {base = {pos = {x = 0, y = 1}},},
pidgeotto = {base = {pos = {x = 2, y = 1}},},
pidgeot = {base = {pos = {x = 4, y = 1}},},
mega_pidgeot = {base = {pos = {x = 14, y = 0}, soul_pos = {x = 15, y = 0}},gen_atlas = true},
rattata = {base = {pos = {x = 6, y = 1}},},
raticate = {base = {pos = {x = 8, y = 1}},},
spearow = {base = {pos = {x = 10, y = 1}},},
fearow = {base = {pos = {x = 12, y = 1}},},
ekans = {base = {pos = {x = 14, y = 1}},},
arbok = {base = {pos = {x = 16, y = 1}},},
pikachu = {base = {pos = {x = 18, y = 1}}, alts = {AtlasJokersSeriesA = {artist = 'MyDude_YT'}}},
raichu = {base = {pos = {x = 20, y = 1}}, alts = {AtlasJokersSeriesA = {artist = 'MyDude_YT'}}},
sandshrew = {base = {pos = {x = 22, y = 1}},},
sandslash = {base = {pos = {x = 24, y = 1}},},
nidoranf = {base = {pos = {x = 26, y = 1}},},
nidorina = {base = {pos = {x = 28, y = 1}},},
nidoqueen = {base = {pos = {x = 0, y = 2}},},
nidoranm = {base = {pos = {x = 2, y = 2}},},
nidorino = {base = {pos = {x = 4, y = 2}},},
nidoking = {base = {pos = {x = 6, y = 2}},},
clefairy = {base = {pos = {x = 8, y = 2}}, alts = {AtlasJokersSeriesA = {artist = 'RibbonOnline'}}},
clefable = {base = {pos = {x = 10, y = 2}},alts = {AtlasJokersSeriesA = {artist = 'RibbonOnline'}}},
vulpix = {base = {pos = {x = 12, y = 2}},},
ninetales = {base = {pos = {x = 14, y = 2}},alts = {AtlasJokersSeriesA = {artist = 'Celsie_RS'}}},
jigglypuff = {base = {pos = {x = 16, y = 2}},alts = {AtlasJokersSeriesA = {artist = 'RibbonOnline'}}},
wigglytuff = {base = {pos = {x = 18, y = 2}},alts = {AtlasJokersSeriesA = {artist = 'RibbonOnline'}}},
zubat = {base = {pos = {x = 20, y = 2}},},
golbat = {base = {pos = {x = 22, y = 2}},alts = {AtlasJokersSeriesA = {artist = 'MyDude_YT'}}},
oddish = {base = {pos = {x = 24, y = 2}},alts = {AtlasJokersSeriesA = {artist = 'RedHaering'}}},
gloom = {base = {pos = {x = 26, y = 2}},},
vileplume = {base = {pos = {x = 28, y = 2}},},
paras = {base = {pos = {x = 0, y = 3}},},
parasect = {base = {pos = {x = 2, y = 3}},},
venonat = {base = {pos = {x = 4, y = 3}},},
venomoth = {base = {pos = {x = 6, y = 3}},},
diglett = {base = {pos = {x = 8, y = 3}},},
dugtrio = {base = {pos = {x = 10, y = 3}},},
meowth = {base = {pos = {x = 12, y = 3}},},
persian = {base = {pos = {x = 14, y = 3}},},
psyduck = {base = {pos = {x = 16, y = 3}},},
golduck = {base = {pos = {x = 18, y = 3}},},
mankey = {base = {pos = {x = 20, y = 3}},},
primeape = {base = {pos = {x = 22, y = 3}},},
growlithe = {base = {pos = {x = 24, y = 3}},alts = {AtlasJokersSeriesA = {artist = 'Xenellia'}}},
arcanine = {base = {pos = {x = 26, y = 3}},alts = {AtlasJokersSeriesA = {artist = 'Xenellia'}}},
poliwag = {base = {pos = {x = 28, y = 3}},},
poliwhirl = {base = {pos = {x = 0, y = 4}},},
poliwrath = {base = {pos = {x = 2, y = 4}},},
abra = {base = {pos = {x = 4, y = 4}},},
kadabra = {base = {pos = {x = 6, y = 4}},},
alakazam = {base = {pos = {x = 8, y = 4}},},
mega_alakazam = {base = {pos = {x = 0, y = 1}, soul_pos = {x = 1, y = 1}},gen_atlas = true},
machop = {base = {pos = {x = 10, y = 4}},},
machoke = {base = {pos = {x = 12, y = 4}},},
machamp = {base = {pos = {x = 14, y = 4}},},
bellsprout = {base = {pos = {x = 16, y = 4}},},
weepinbell = {base = {pos = {x = 18, y = 4}},},
victreebel = {base = {pos = {x = 20, y = 4}},},
tentacool = {base = {pos = {x = 22, y = 4}},},
tentacruel = {base = {pos = {x = 24, y = 4}},},
geodude = {base = {pos = {x = 26, y = 4}},},
graveler = {base = {pos = {x = 28, y = 4}},},
golem = {base = {pos = {x = 0, y = 5}},},
ponyta = {base = {pos = {x = 2, y = 5}},alts = {AtlasJokersSeriesA = {artist = 'Xenellia'}}},
rapidash = {base = {pos = {x = 4, y = 5}},alts = {AtlasJokersSeriesA = {artist = 'Xenellia'}}},
slowpoke = {base = {pos = {x = 6, y = 5}},},
slowbro = {base = {pos = {x = 8, y = 5}},},
mega_slowbro = {base = {pos = {x = 2, y = 1}, soul_pos = {x = 3, y = 1}},gen_atlas = true},
shell = {base = {pos = {x = 4, y = 8}}, gen_atlas = true,},
magnemite = {base = {pos = {x = 10, y = 5}},alts = {AtlasJokersSeriesA = {artist = 'MyDude_YT'}}},
magneton = {base = {pos = {x = 12, y = 5}},},
farfetchd = {base = {pos = {x = 14, y = 5}},},
doduo = {base = {pos = {x = 16, y = 5}},},
dodrio = {base = {pos = {x = 18, y = 5}},},
seel = {base = {pos = {x = 20, y = 5}},},
dewgong = {base = {pos = {x = 22, y = 5}},},
grimer = {base = {pos = {x = 24, y = 5}},},
muk = {base = {pos = {x = 26, y = 5}},alts = {AtlasJokersSeriesA = {artist = 'MyDude_YT'}}},
shellder = {base = {pos = {x = 28, y = 5}},},
cloyster = {base = {pos = {x = 0, y = 6}},},
gastly = {base = {pos = {x = 2, y = 6}},alts = {AtlasJokersSeriesA = {artist = 'MyDude_YT'}}},
haunter = {base = {pos = {x = 4, y = 6}},alts = {AtlasJokersSeriesA = {artist = 'MyDude_YT', soul_pos = {x = 5, y = 6}}}},
gengar = {base = {pos = {x = 6, y = 6}},alts = {AtlasJokersSeriesA = {artist = 'MyDude_YT', soul_pos = {x = 7, y = 6}}}},
mega_gengar = {base = {pos = {x = 4, y = 1}, soul_pos = {x = 5, y = 1}},gen_atlas = true, alts = {AtlasJokersSeriesA = {artist = 'MyDude_YT'}}},
onix = {base = {pos = {x = 8, y = 6}},},
drowzee = {base = {pos = {x = 10, y = 6}},},
hypno = {base = {pos = {x = 12, y = 6}},},
krabby = {base = {pos = {x = 14, y = 6}},},
kingler = {base = {pos = {x = 16, y = 6}},},
voltorb = {base = {pos = {x = 18, y = 6}},alts = {
    AtlasJokersSeriesA = {artist = 'Maelmc', anim_atlas = "AtlasJokersSeriesAVoltorb"},
    AtlasJokersSeriesB = {artist = 'MyDude_YT'}
}},
electrode = {base = {pos = {x = 20, y = 6}},alts = {AtlasJokersSeriesA = {artist = 'Maelmc',anim_atlas = "AtlasJokersSeriesAElectrode"}}},
exeggcute = {base = {pos = {x = 22, y = 6}},},
exeggutor = {base = {pos = {x = 24, y = 6}},alts = {AtlasJokersSeriesA = {artist = 'MyDude_YT'}}},
cubone = {base = {pos = {x = 26, y = 6}},},
marowak = {base = {pos = {x = 28, y = 6}},},
hitmonlee = {base = {pos = {x = 0, y = 7}},alts = {AtlasJokersSeriesA = {artist = 'MyDude_YT'}}},
hitmonchan = {base = {pos = {x = 2, y = 7}},alts = {AtlasJokersSeriesA = {artist = 'MyDude_YT'}}},
lickitung = {base = {pos = {x = 4, y = 7}},},
koffing = {base = {pos = {x = 6, y = 7}},},
weezing = {base = {pos = {x = 8, y = 7}},},
rhyhorn = {base = {pos = {x = 10, y = 7}},},
rhydon = {base = {pos = {x = 12, y = 7}},},
chansey = {base = {pos = {x = 14, y = 7}},},
tangela = {base = {pos = {x = 16, y = 7}},alts = {AtlasJokersSeriesA = {artist = 'MyDude_YT'}}},
kangaskhan = {base = {pos = {x = 18, y = 7}},},
mega_kangaskhan = {base = {pos = {x = 6, y = 1}, soul_pos = {x = 7, y = 1}},gen_atlas = true},
horsea = {base = {pos = {x = 20, y = 7}},},
seadra = {base = {pos = {x = 22, y = 7}},},
goldeen = {base = {pos = {x = 24, y = 7}},},
seaking = {base = {pos = {x = 26, y = 7}},},
staryu = {base = {pos = {x = 28, y = 7}},alts = {AtlasJokersSeriesA = {artist = {'Chartreuse_Chamber', 'Xenellia'}}}},
starmie = {base = {pos = {x = 0, y = 8}},alts = {AtlasJokersSeriesA = {artist = {'MyDude_YT', 'Chartreuse_Chamber'}}}},
mrmime = {base = {pos = {x = 2, y = 8}},alts = {AtlasJokersSeriesA = {artist = 'RedHaering', soul_pos = {x = 3, y = 8}}}},
scyther = {base = {pos = {x = 4, y = 8}},},
jynx = {base = {pos = {x = 6, y = 8}},},
electabuzz = {base = {pos = {x = 8, y = 8}},},
magmar = {base = {pos = {x = 10, y = 8}},},
pinsir = {base = {pos = {x = 12, y = 8}},},
mega_pinsir = {base = {pos = {x = 8, y = 1}, soul_pos = {x = 9, y = 1}},gen_atlas = true},
tauros = {base = {pos = {x = 14, y = 8}},},
taurosh = {base = {pos = {x = 0, y = 0}}, gen_atlas = true,},
magikarp = {base = {pos = {x = 16, y = 8}},},
gyarados = {base = {pos = {x = 18, y = 8}},},
mega_gyarados = {base = {pos = {x = 10, y = 1}, soul_pos = {x = 11, y = 1}},gen_atlas = true},
lapras = {base = {pos = {x = 20, y = 8}},alts = {AtlasJokersSeriesA = {artist = 'Celsie_RS'}}},
ditto = {base = {pos = {x = 22, y = 8}},},
eevee = {base = {pos = {x = 24, y = 8}},alts = {AtlasJokersSeriesA = {artist = 'Desnik'}}},
vaporeon = {base = {pos = {x = 26, y = 8}},},
jolteon = {base = {pos = {x = 28, y = 8}},},
flareon = {base = {pos = {x = 0, y = 9}},alts = {AtlasJokersSeriesA = {artist = 'Dudelings'}}},
porygon = {base = {pos = {x = 2, y = 9}},alts = {
    AtlasJokersSeriesA = {artist = 'Captain_Slime'}, 
    AtlasJokersSeriesB = {artist = 'MyDude_YT'}
}},
omanyte = {base = {pos = {x = 4, y = 9}},},
omastar = {base = {pos = {x = 6, y = 9}},},
kabuto = {base = {pos = {x = 8, y = 9}},},
kabutops = {base = {pos = {x = 10, y = 9}},},
aerodactyl = {base = {pos = {x = 12, y = 9}},},
mega_aerodactyl = {base = {pos = {x = 12, y = 1}, soul_pos = {x = 13, y = 1}},gen_atlas = true},
snorlax = {base = {pos = {x = 14, y = 9}},},
articuno = {base = {pos = {x = 16, y = 9}, soul_pos = {x = 17, y = 9}},alts = {AtlasJokersSeriesA = {artist = 'bt'}}},
zapdos = {base = {pos = {x = 18, y = 9}, soul_pos = {x = 19, y = 9}},alts = {AtlasJokersSeriesA = {artist = 'Sonfive'}}},
moltres = {base = {pos = {x = 20, y = 9}, soul_pos = {x = 21, y = 9}},alts = {AtlasJokersSeriesA = {}}},
dratini = {base = {pos = {x = 22, y = 9}},alts = {AtlasJokersSeriesA = {artist = 'Desnik'}}},
dragonair = {base = {pos = {x = 24, y = 9}},},
dragonite = {base = {pos = {x = 26, y = 9}},},
mewtwo = {base = {pos = {x = 28, y = 9}, soul_pos = {x = 29, y = 9}},alts = {AtlasJokersSeriesA = {artist = 'Catzzadilla'}}},
mega_mewtwo_x = {base = {pos = {x = 14, y = 1}, soul_pos = {x = 15, y = 1}},gen_atlas = true},
mega_mewtwo_y = {base = {pos = {x = 0, y = 2}, soul_pos = {x = 1, y = 2}},gen_atlas = true},
mew = {base = {pos = {x = 0, y = 10}, soul_pos = {x = 1, y = 10}},alts = {AtlasJokersSeriesA = {artist = 'Catzzadilla'}}},
missingno = {base = {pos = {x = 2, y = 0}, soul_pos = {x = 3, y = 0}}, gen_atlas = true, alts = {AtlasJokersSeriesA = {artist = 'Catzzadilla'}}},
chikorita = {base = {pos = {x = 2, y = 10}},},
bayleef = {base = {pos = {x = 4, y = 10}},},
meganium = {base = {pos = {x = 6, y = 10}},},
cyndaquil = {base = {pos = {x = 8, y = 10}},},
quilava = {base = {pos = {x = 10, y = 10}},},
typhlosion = {base = {pos = {x = 12, y = 10}},},
totodile = {base = {pos = {x = 14, y = 10}},},
croconaw = {base = {pos = {x = 16, y = 10}},},
feraligatr = {base = {pos = {x = 18, y = 10}},},
sentret = {base = {pos = {x = 20, y = 10}},},
furret = {base = {pos = {x = 22, y = 10}},},
hoothoot = {base = {pos = {x = 24, y = 10}},},
noctowl = {base = {pos = {x = 26, y = 10}},},
ledyba = {base = {pos = {x = 28, y = 10}},},
ledian = {base = {pos = {x = 0, y = 11}},},
spinarak = {base = {pos = {x = 2, y = 11}},},
ariados = {base = {pos = {x = 4, y = 11}},},
crobat = {base = {pos = {x = 6, y = 11}},},
chinchou = {base = {pos = {x = 8, y = 11}},},
lanturn = {base = {pos = {x = 10, y = 11}},},
pichu = {base = {pos = {x = 12, y = 11}},alts = {AtlasJokersSeriesA = {artist = 'MyDude_YT'}}},
cleffa = {base = {pos = {x = 14, y = 11}},alts = {AtlasJokersSeriesA = {artist = 'RibbonOnline'}}},
igglybuff = {base = {pos = {x = 16, y = 11}},alts = {AtlasJokersSeriesA = {artist = 'RibbonOnline'}}},
togepi = {base = {pos = {x = 18, y = 11}},},
togetic = {base = {pos = {x = 20, y = 11}},},
natu = {base = {pos = {x = 22, y = 11}},},
xatu = {base = {pos = {x = 24, y = 11}},},
mareep = {base = {pos = {x = 26, y = 11}},},
flaaffy = {base = {pos = {x = 28, y = 11}},},
ampharos = {base = {pos = {x = 0, y = 12}},},
mega_ampharos = {base = {pos = {x = 4, y = 3}, soul_pos = {x = 5, y = 3}},gen_atlas = true},
bellossom = {base = {pos = {x = 2, y = 12}},},
marill = {base = {pos = {x = 4, y = 12}},},
azumarill = {base = {pos = {x = 6, y = 12}},},
sudowoodo = {base = {pos = {x = 8, y = 12}},},
weird_tree = {base = {pos = {x = 0, y = 3}}, alts = {AtlasJokersSeriesA = {artist = 'RedHaering'}},gen_atlas = true},
politoed = {base = {pos = {x = 10, y = 12}},alts = {AtlasJokersSeriesA = {artist = 'Sonfive'}}},
hoppip = {base = {pos = {x = 12, y = 12}},},
skiploom = {base = {pos = {x = 14, y = 12}},},
jumpluff = {base = {pos = {x = 16, y = 12}},alts = {AtlasJokersSeriesA = {artist = 'Celsie_RS'}}},
aipom = {base = {pos = {x = 18, y = 12}},},
sunkern = {base = {pos = {x = 20, y = 12}},},
sunflora = {base = {pos = {x = 22, y = 12}},},
yanma = {base = {pos = {x = 24, y = 12}},},
wooper = {base = {pos = {x = 26, y = 12}},alts = {AtlasJokersSeriesA = {artist = 'Desnik'}}},
quagsire = {base = {pos = {x = 28, y = 12}},alts = {AtlasJokersSeriesA = {artist = 'Desnik'}}},
espeon = {base = {pos = {x = 0, y = 13}},},
umbreon = {base = {pos = {x = 2, y = 13}},},
murkrow = {base = {pos = {x = 4, y = 13}},},
slowking = {base = {pos = {x = 6, y = 13}},},
misdreavus = {base = {pos = {x = 8, y = 13}},},
unown = {base = {pos = {x = 0, y = 0}, soul_pos = {x = 1, y = 0}},gen_atlas = true},
wobbuffet = {base = {pos = {x = 12, y = 13}},},
girafarig = {base = {pos = {x = 14, y = 13}},},
pineco = {base = {pos = {x = 16, y = 13}},},
forretress = {base = {pos = {x = 18, y = 13}},},
dunsparce = {base = {pos = {x = 20, y = 13}},},
gligar = {base = {pos = {x = 22, y = 13}},},
steelix = {base = {pos = {x = 24, y = 13}},},
mega_steelix = {base = {pos = {x = 6, y = 3}, soul_pos = {x = 7, y = 3}},gen_atlas = true},
snubbull = {base = {pos = {x = 26, y = 13}},},
granbull = {base = {pos = {x = 28, y = 13}},},
qwilfish = {base = {pos = {x = 0, y = 14}},},
scizor = {base = {pos = {x = 2, y = 14}},},
mega_scizor = {base = {pos = {x = 8, y = 3}, soul_pos = {x = 9, y = 3}},gen_atlas = true},
shuckle = {base = {pos = {x = 4, y = 14}},},
heracross = {base = {pos = {x = 6, y = 14}},},
mega_heracross = {base = {pos = {x = 0, y = 4}, soul_pos = {x = 1, y = 4}},gen_atlas = true},
sneasel = {base = {pos = {x = 8, y = 14}},},
teddiursa = {base = {pos = {x = 10, y = 14}},},
ursaring = {base = {pos = {x = 12, y = 14}},},
slugma = {base = {pos = {x = 14, y = 14}},},
magcargo = {base = {pos = {x = 16, y = 14}},},
swinub = {base = {pos = {x = 18, y = 14}},},
piloswine = {base = {pos = {x = 20, y = 14}},},
corsola = {base = {pos = {x = 22, y = 14}},},
remoraid = {base = {pos = {x = 24, y = 14}},},
octillery = {base = {pos = {x = 26, y = 14}},},
delibird = {base = {pos = {x = 28, y = 14}},},
mantine = {base = {pos = {x = 0, y = 15}},},
skarmory = {base = {pos = {x = 2, y = 15}},},
houndour = {base = {pos = {x = 4, y = 15}},},
houndoom = {base = {pos = {x = 6, y = 15}},},
mega_houndoom = {base = {pos = {x = 2, y = 4}, soul_pos = {x = 3, y = 4}},gen_atlas = true},
kingdra = {base = {pos = {x = 8, y = 15}},},
phanpy = {base = {pos = {x = 10, y = 15}},},
donphan = {base = {pos = {x = 12, y = 15}},},
porygon2 = {base = {pos = {x = 14, y = 15}},alts = {AtlasJokersSeriesA = {artist = 'Captain_Slime'}}},
stantler = {base = {pos = {x = 16, y = 15}},},
smeargle = {base = {pos = {x = 18, y = 15}},},
tyrogue = {base = {pos = {x = 20, y = 15}},alts = {AtlasJokersSeriesA = {artist = 'MyDude_YT'}}},
hitmontop = {base = {pos = {x = 22, y = 15}},alts = {AtlasJokersSeriesA = {artist = 'MyDude_YT'}}},
smoochum = {base = {pos = {x = 24, y = 15}},},
elekid = {base = {pos = {x = 26, y = 15}},},
magby = {base = {pos = {x = 28, y = 15}},},
miltank = {base = {pos = {x = 0, y = 16}},},
blissey = {base = {pos = {x = 2, y = 16}},},
raikou = {base = {pos = {x = 4, y = 16}, soul_pos = {x = 5, y = 16}},alts = {AtlasJokersSeriesA = {artist = 'Tovivi'}}},
entei = {base = {pos = {x = 6, y = 16}, soul_pos = {x = 7, y = 16}},alts = {AtlasJokersSeriesA = {artist = 'bt'}}},
suicune = {base = {pos = {x = 8, y = 16}, soul_pos = {x = 9, y = 16}},},
larvitar = {base = {pos = {x = 10, y = 16}},alts = {AtlasJokersSeriesA = {artist = 'MyDude_YT'}}},
pupitar = {base = {pos = {x = 12, y = 16}},alts = {AtlasJokersSeriesA = {artist = 'MyDude_YT'}}},
tyranitar = {base = {pos = {x = 14, y = 16}},alts = {AtlasJokersSeriesA = {artist = 'MyDude_YT'}}},
mega_tyranitar = {base = {pos = {x = 4, y = 4}, soul_pos = {x = 5, y = 4}},gen_atlas = true, alts = {AtlasJokersSeriesA = {artist = {'MyDude_YT', 'Silverfish07'}}}},
lugia = {base = {pos = {x = 16, y = 16}, soul_pos = {x = 17, y = 16}},alts = {AtlasJokersSeriesA = {artist = 'Tovivi'}}},
ho_oh = {base = {pos = {x = 18, y = 16}, soul_pos = {x = 19, y = 16}},},
celebi = {base = {pos = {x = 20, y = 16}, soul_pos = {x = 21, y = 16}},},
treecko = {base = {pos = {x = 22, y = 16}},},
grovyle = {base = {pos = {x = 24, y = 16}},},
sceptile = {base = {pos = {x = 26, y = 16}},},
torchic = {base = {pos = {x = 28, y = 16}},},
combusken = {base = {pos = {x = 0, y = 17}},},
blaziken = {base = {pos = {x = 2, y = 17}},},
mudkip = {base = {pos = {x = 4, y = 17}},},
marshtomp = {base = {pos = {x = 6, y = 17}},},
swampert = {base = {pos = {x = 8, y = 17}},},
poochyena = {base = {pos = {x = 10, y = 17}},},
mightyena = {base = {pos = {x = 12, y = 17}},},
zigzagoon = {base = {pos = {x = 14, y = 17}},},
linoone = {base = {pos = {x = 16, y = 17}},},
wurmple = {base = {pos = {x = 18, y = 17}},},
silcoon = {base = {pos = {x = 20, y = 17}},},
beautifly = {base = {pos = {x = 22, y = 17}},},
cascoon = {base = {pos = {x = 24, y = 17}},},
dustox = {base = {pos = {x = 26, y = 17}},},
lotad = {base = {pos = {x = 28, y = 17}}, alts = {AtlasJokersSeriesA = {artist = 'RedHaering'}}},
lombre = {base = {pos = {x = 0, y = 18}},},
ludicolo = {base = {pos = {x = 2, y = 18}},},
seedot = {base = {pos = {x = 4, y = 18}},},
nuzleaf = {base = {pos = {x = 6, y = 18}},},
shiftry = {base = {pos = {x = 8, y = 18}},},
taillow = {base = {pos = {x = 10, y = 18}},},
swellow = {base = {pos = {x = 12, y = 18}},},
wingull = {base = {pos = {x = 14, y = 18}},},
pelipper = {base = {pos = {x = 16, y = 18}},},
ralts = {base = {pos = {x = 18, y = 18}},},
kirlia = {base = {pos = {x = 20, y = 18}},},
gardevoir = {base = {pos = {x = 22, y = 18}},},
surskit = {base = {pos = {x = 24, y = 18}},},
masquerain = {base = {pos = {x = 26, y = 18}},},
shroomish = {base = {pos = {x = 28, y = 18}},},
breloom = {base = {pos = {x = 0, y = 19}},},
slakoth = {base = {pos = {x = 2, y = 19}},},
vigoroth = {base = {pos = {x = 4, y = 19}},},
slaking = {base = {pos = {x = 6, y = 19}},},
nincada = {base = {pos = {x = 8, y = 19}},},
ninjask = {base = {pos = {x = 10, y = 19}},},
shedinja = {base = {pos = {x = 12, y = 19}},},
whismur = {base = {pos = {x = 14, y = 19}},},
loudred = {base = {pos = {x = 16, y = 19}},},
exploud = {base = {pos = {x = 18, y = 19}},},
makuhita = {base = {pos = {x = 20, y = 19}},},
hariyama = {base = {pos = {x = 22, y = 19}},},
azurill = {base = {pos = {x = 24, y = 19}},},
nosepass = {base = {pos = {x = 26, y = 19}},},
skitty = {base = {pos = {x = 28, y = 19}},},
delcatty = {base = {pos = {x = 0, y = 20}},},
sableye = {base = {pos = {x = 2, y = 20}},},
mawile = {base = {pos = {x = 4, y = 20}},},
aron = {base = {pos = {x = 6, y = 20}},},
lairon = {base = {pos = {x = 8, y = 20}},},
aggron = {base = {pos = {x = 10, y = 20}},},
meditite = {base = {pos = {x = 12, y = 20}},},
medicham = {base = {pos = {x = 14, y = 20}},},
electrike = {base = {pos = {x = 16, y = 20}},},
manectric = {base = {pos = {x = 18, y = 20}},},
plusle = {base = {pos = {x = 20, y = 20}},},
minun = {base = {pos = {x = 22, y = 20}},},
volbeat = {base = {pos = {x = 24, y = 20}},},
illumise = {base = {pos = {x = 26, y = 20}},},
roselia = {base = {pos = {x = 28, y = 20}},},
gulpin = {base = {pos = {x = 0, y = 21}},},
swalot = {base = {pos = {x = 2, y = 21}},},
carvanha = {base = {pos = {x = 4, y = 21}},},
sharpedo = {base = {pos = {x = 6, y = 21}},},
wailmer = {base = {pos = {x = 8, y = 21}},},
wailord = {base = {pos = {x = 10, y = 21}},},
numel = {base = {pos = {x = 12, y = 21}},},
camerupt = {base = {pos = {x = 14, y = 21}},},
mega_camerupt = {base = {pos = {x = 0, y = 6}, soul_pos = {x = 1, y = 6}},gen_atlas = true},
torkoal = {base = {pos = {x = 16, y = 21}},},
spoink = {base = {pos = {x = 18, y = 21}},},
grumpig = {base = {pos = {x = 20, y = 21}},},
spinda = {base = {pos = {x = 22, y = 21}},},
trapinch = {base = {pos = {x = 24, y = 21}},},
vibrava = {base = {pos = {x = 26, y = 21}},},
flygon = {base = {pos = {x = 28, y = 21}},},
cacnea = {base = {pos = {x = 0, y = 22}},},
cacturne = {base = {pos = {x = 2, y = 22}},},
swablu = {base = {pos = {x = 4, y = 22}},},
altaria = {base = {pos = {x = 6, y = 22}},},
zangoose = {base = {pos = {x = 8, y = 22}}, alts = {AtlasJokersSeriesA = {artist = 'CBMX'}}},
seviper = {base = {pos = {x = 10, y = 22}}, alts = {AtlasJokersSeriesA = {artist = 'CBMX'}}},
lunatone = {base = {pos = {x = 12, y = 22}},},
solrock = {base = {pos = {x = 14, y = 22}},},
barboach = {base = {pos = {x = 16, y = 22}},},
whiscash = {base = {pos = {x = 18, y = 22}},},
corphish = {base = {pos = {x = 20, y = 22}},},
crawdaunt = {base = {pos = {x = 22, y = 22}},},
baltoy = {base = {pos = {x = 24, y = 22}},},
claydol = {base = {pos = {x = 26, y = 22}},},
lileep = {base = {pos = {x = 28, y = 22}},},
cradily = {base = {pos = {x = 0, y = 23}},},
anorith = {base = {pos = {x = 2, y = 23}},},
armaldo = {base = {pos = {x = 4, y = 23}},},
feebas = {base = {pos = {x = 6, y = 23}},},
milotic = {base = {pos = {x = 8, y = 23}},},
castform = {base = {pos = {x = 10, y = 23}},},
kecleon = {base = {pos = {x = 12, y = 23}},},
shuppet = {base = {pos = {x = 14, y = 23}},},
banette = {base = {pos = {x = 16, y = 23}},},
duskull = {base = {pos = {x = 18, y = 23}},},
dusclops = {base = {pos = {x = 20, y = 23}},},
tropius = {base = {pos = {x = 22, y = 23}},},
chimecho = {base = {pos = {x = 24, y = 23}},},
absol = {base = {pos = {x = 26, y = 23}},},
wynaut = {base = {pos = {x = 28, y = 23}},},
snorunt = {base = {pos = {x = 0, y = 24}},},
glalie = {base = {pos = {x = 2, y = 24}},},
spheal = {base = {pos = {x = 4, y = 24}},},
sealeo = {base = {pos = {x = 6, y = 24}},},
walrein = {base = {pos = {x = 8, y = 24}},},
clamperl = {base = {pos = {x = 10, y = 24}},},
huntail = {base = {pos = {x = 12, y = 24}},},
gorebyss = {base = {pos = {x = 14, y = 24}},},
relicanth = {base = {pos = {x = 16, y = 24}},},
luvdisc = {base = {pos = {x = 18, y = 24}},},
bagon = {base = {pos = {x = 20, y = 24}},},
shelgon = {base = {pos = {x = 22, y = 24}},},
salamence = {base = {pos = {x = 24, y = 24}},},
beldum = {base = {pos = {x = 26, y = 24}},},
metang = {base = {pos = {x = 28, y = 24}},},
metagross = {base = {pos = {x = 0, y = 25}},},
regirock = {base = {pos = {x = 2, y = 25}},},
regice = {base = {pos = {x = 4, y = 25}},},
registeel = {base = {pos = {x = 6, y = 25}},},
latias = {base = {pos = {x = 8, y = 25}},},
latios = {base = {pos = {x = 10, y = 25}},},
kyogre = {base = {pos = {x = 12, y = 25}},},
groudon = {base = {pos = {x = 14, y = 25}},},
rayquaza = {base = {pos = {x = 16, y = 25}, soul_pos = {x = 17, y = 25}},},
jirachi = {base = {pos = {x = 18, y = 25}, soul_pos = {x = 19, y = 25}},},
jirachi_banker = {base = {pos = {x = 4, y = 2}, soul_pos =  {x = 5, y = 2}}, gen_atlas = true, alts = {AtlasJokersSeriesA = {artist = 'PrincessRoxie'}}},
jirachi_booster = {base = {pos = {x = 6, y = 2}, soul_pos =  {x = 7, y = 2}}, gen_atlas = true, alts = {AtlasJokersSeriesA = {artist = 'PrincessRoxie'}}},
jirachi_power = {base = {pos = {x = 8, y = 2}, soul_pos =  {x = 9, y = 2}}, gen_atlas = true, alts = {AtlasJokersSeriesA = {artist = 'PrincessRoxie'}}},
jirachi_invis = {base = {pos = {x = 10, y = 2}, soul_pos =  {x = 11, y = 2}}, gen_atlas = true, alts = {AtlasJokersSeriesA = {artist = 'PrincessRoxie'}}},
jirachi_fixer = {base = {pos = {x = 0, y = 3}, soul_pos =  {x = 1, y = 3}}, gen_atlas = true, alts = {AtlasJokersSeriesA = {artist = 'PrincessRoxie'}}},
deoxys = {base = {pos = {x = 20, y = 25}}, soul_pos = {x = 21, y = 25},},
turtwig = {base = {pos = {x = 22, y = 25}},},
grotle = {base = {pos = {x = 24, y = 25}},},
torterra = {base = {pos = {x = 26, y = 25}},},
chimchar = {base = {pos = {x = 28, y = 25}},},
monferno = {base = {pos = {x = 0, y = 26}},},
infernape = {base = {pos = {x = 2, y = 26}},},
piplup = {base = {pos = {x = 4, y = 26}},},
prinplup = {base = {pos = {x = 6, y = 26}},},
empoleon = {base = {pos = {x = 8, y = 26}},},
starly = {base = {pos = {x = 10, y = 26}},},
staravia = {base = {pos = {x = 12, y = 26}},},
staraptor = {base = {pos = {x = 14, y = 26}},},
bidoof = {base = {pos = {x = 16, y = 26}},},
bibarel = {base = {pos = {x = 18, y = 26}},},
kricketot = {base = {pos = {x = 20, y = 26}},},
kricketune = {base = {pos = {x = 22, y = 26}},},
shinx = {base = {pos = {x = 24, y = 26}},},
luxio = {base = {pos = {x = 26, y = 26}},},
luxray = {base = {pos = {x = 28, y = 26}},},
budew = {base = {pos = {x = 0, y = 27}},},
roserade = {base = {pos = {x = 2, y = 27}},},
cranidos = {base = {pos = {x = 4, y = 27}},},
rampardos = {base = {pos = {x = 6, y = 27}},},
shieldon = {base = {pos = {x = 8, y = 27}},},
bastiodon = {base = {pos = {x = 10, y = 27}},},
burmy = {base = {pos = {x = 12, y = 27}},},
wormadam = {base = {pos = {x = 14, y = 27}},},
mothim = {base = {pos = {x = 16, y = 27}},},
combee = {base = {pos = {x = 18, y = 27}},},
vespiquen = {base = {pos = {x = 20, y = 27}},},
pachirisu = {base = {pos = {x = 22, y = 27}},},
buizel = {base = {pos = {x = 24, y = 27}},},
floatzel = {base = {pos = {x = 26, y = 27}},},
cherubi = {base = {pos = {x = 28, y = 27}},},
cherrim = {base = {pos = {x = 0, y = 28}},},
shellos = {base = {pos = {x = 2, y = 28}},},
gastrodon = {base = {pos = {x = 4, y = 28}},},
ambipom = {base = {pos = {x = 6, y = 28}},},
drifloon = {base = {pos = {x = 8, y = 28}},},
drifblim = {base = {pos = {x = 10, y = 28}},},
buneary = {base = {pos = {x = 12, y = 28}},},
lopunny = {base = {pos = {x = 14, y = 28}},},
mega_lopunny = {base = {pos = {x = 8, y = 6}, soul_pos = {x = 9, y = 6}},gen_atlas = true},
mismagius = {base = {pos = {x = 16, y = 28}},},
honchkrow = {base = {pos = {x = 18, y = 28}},},
glameow = {base = {pos = {x = 20, y = 28}},},
purugly = {base = {pos = {x = 22, y = 28}},},
chingling = {base = {pos = {x = 24, y = 28}},},
stunky = {base = {pos = {x = 26, y = 28}},},
skuntank = {base = {pos = {x = 28, y = 28}},},
bronzor = {base = {pos = {x = 0, y = 29}},},
bronzong = {base = {pos = {x = 2, y = 29}},},
bonsly = {base = {pos = {x = 4, y = 29}},alts = {AtlasJokersSeriesA = {artist = 'RedHaering'}}},
mimejr = {base = {pos = {x = 6, y = 29}},alts = {AtlasJokersSeriesA = {artist = 'RedHaering'}}},
happiny = {base = {pos = {x = 8, y = 29}},},
chatot = {base = {pos = {x = 10, y = 29}},},
spiritomb = {base = {pos = {x = 12, y = 29}},},
gible = {base = {pos = {x = 14, y = 29}},},
gabite = {base = {pos = {x = 16, y = 29}},},
garchomp = {base = {pos = {x = 18, y = 29}},},
munchlax = {base = {pos = {x = 20, y = 29}},},
riolu = {base = {pos = {x = 22, y = 29}},},
lucario = {base = {pos = {x = 24, y = 29}},},
hippopotas = {base = {pos = {x = 26, y = 29}},},
hippowdon = {base = {pos = {x = 28, y = 29}},},
skorupi = {base = {pos = {x = 0, y = 30}},},
drapion = {base = {pos = {x = 2, y = 30}},},
croagunk = {base = {pos = {x = 4, y = 30}},},
toxicroak = {base = {pos = {x = 6, y = 30}},},
carnivine = {base = {pos = {x = 8, y = 30}},},
finneon = {base = {pos = {x = 10, y = 30}},},
lumineon = {base = {pos = {x = 12, y = 30}},},
mantyke = {base = {pos = {x = 14, y = 30}},},
snover = {base = {pos = {x = 16, y = 30}},},
abomasnow = {base = {pos = {x = 18, y = 30}},},
weavile = {base = {pos = {x = 20, y = 30}},},
magnezone = {base = {pos = {x = 22, y = 30}},},
lickilicky = {base = {pos = {x = 24, y = 30}},},
rhyperior = {base = {pos = {x = 26, y = 30}},},
tangrowth = {base = {pos = {x = 28, y = 30}},},
electivire = {base = {pos = {x = 0, y = 31}},},
magmortar = {base = {pos = {x = 2, y = 31}},},
togekiss = {base = {pos = {x = 4, y = 31}},},
yanmega = {base = {pos = {x = 6, y = 31}},},
leafeon = {base = {pos = {x = 8, y = 31}},},
glaceon = {base = {pos = {x = 10, y = 31}},},
gliscor = {base = {pos = {x = 12, y = 31}},},
mamoswine = {base = {pos = {x = 14, y = 31}},},
porygonz = {base = {pos = {x = 16, y = 31}},alts = {AtlasJokersSeriesA = {artist = 'Captain_Slime'}}},
gallade = {base = {pos = {x = 18, y = 31}},},
probopass = {base = {pos = {x = 20, y = 31}},},
dusknoir = {base = {pos = {x = 22, y = 31}},},
froslass = {base = {pos = {x = 24, y = 31}},},
rotom = {base = {pos = {x = 26, y = 31}},},
rotomh = {base = {pos = {x = 0, y = 2}},gen_atlas = true},
rotomw = {base = {pos = {x = 8, y = 2}},gen_atlas = true},
rotomf = {base = {pos = {x = 6, y = 2}},gen_atlas = true},
rotomfan = {base = {pos = {x = 4, y = 2}},gen_atlas = true},
rotomm = {base = {pos = {x = 2, y = 2}},gen_atlas = true},
uxie = {base = {pos = {x = 28, y = 31}, soul_pos = {x = 29, y = 31}},},
mesprit = {base = {pos = {x = 0, y = 32}, soul_pos = {x = 1, y = 32}},},
azelf = {base = {pos = {x = 2, y = 32}, soul_pos = {x = 3, y = 32}},},
dialga = {base = {pos = {x = 4, y = 32}, soul_pos = {x = 5, y = 32}},},
palkia = {base = {pos = {x = 6, y = 32}, soul_pos = {x = 7, y = 32}},},
heatran = {base = {pos = {x = 8, y = 32}, soul_pos = {x = 9, y = 32}},},
regigigas = {base = {pos = {x = 10, y = 32}, soul_pos = {x = 11, y = 32}},},
giratina = {base = {pos = {x = 12, y = 32}, soul_pos = {x = 13, y = 32}},},
cresselia = {base = {pos = {x = 14, y = 32}, soul_pos = {x = 15, y = 32}},},
phione = {base = {pos = {x = 16, y = 32}, soul_pos = {x = 17, y = 32}},},
manaphy = {base = {pos = {x = 18, y = 32}, soul_pos = {x = 19, y = 32}},},
darkrai = {base = {pos = {x = 20, y = 32}, soul_pos = {x = 21, y = 32}},},
shaymin = {base = {pos = {x = 0, y = 4}, soul_pos = {x = 1, y = 4}},gen_atlas = true},
shaymin_sky = {base = {pos = {x = 2, y = 4}, soul_pos = {x = 3, y = 4}},gen_atlas = true},
arceus = {base = {pos = {x = 24, y = 32}, soul_pos = {x = 25, y = 32}},},
victini = {base = {pos = {x = 26, y = 32}, soul_pos = {x = 27, y = 32}},},
snivy = {base = {pos = {x = 28, y = 32}},},
servine = {base = {pos = {x = 0, y = 33}},},
serperior = {base = {pos = {x = 2, y = 33}},},
tepig = {base = {pos = {x = 4, y = 33}},},
pignite = {base = {pos = {x = 6, y = 33}},},
emboar = {base = {pos = {x = 8, y = 33}},},
oshawott = {base = {pos = {x = 10, y = 33}},},
dewott = {base = {pos = {x = 12, y = 33}},},
samurott = {base = {pos = {x = 14, y = 33}},},
patrat = {base = {pos = {x = 16, y = 33}},},
watchog = {base = {pos = {x = 18, y = 33}},},
lillipup = {base = {pos = {x = 20, y = 33}},},
herdier = {base = {pos = {x = 22, y = 33}},},
stoutland = {base = {pos = {x = 24, y = 33}},},
purrloin = {base = {pos = {x = 26, y = 33}},},
liepard = {base = {pos = {x = 28, y = 33}},},
pansage = {base = {pos = {x = 0, y = 34}},},
simisage = {base = {pos = {x = 2, y = 34}},},
pansear = {base = {pos = {x = 4, y = 34}},},
simisear = {base = {pos = {x = 6, y = 34}},},
panpour = {base = {pos = {x = 8, y = 34}},},
simipour = {base = {pos = {x = 10, y = 34}},},
munna = {base = {pos = {x = 12, y = 34}},},
musharna = {base = {pos = {x = 14, y = 34}},},
pidove = {base = {pos = {x = 16, y = 34}},},
tranquill = {base = {pos = {x = 18, y = 34}},},
unfezant = {base = {pos = {x = 20, y = 34}},},
blitzle = {base = {pos = {x = 22, y = 34}},},
zebstrika = {base = {pos = {x = 24, y = 34}},},
roggenrola = {base = {pos = {x = 26, y = 34}},},
boldore = {base = {pos = {x = 28, y = 34}},},
gigalith = {base = {pos = {x = 0, y = 35}},},
woobat = {base = {pos = {x = 2, y = 35}},},
swoobat = {base = {pos = {x = 4, y = 35}},},
drilbur = {base = {pos = {x = 6, y = 35}},},
excadrill = {base = {pos = {x = 8, y = 35}},},
audino = {base = {pos = {x = 10, y = 35}},},
timburr = {base = {pos = {x = 12, y = 35}},},
gurdurr = {base = {pos = {x = 14, y = 35}},},
conkeldurr = {base = {pos = {x = 16, y = 35}},},
tympole = {base = {pos = {x = 18, y = 35}},},
palpitoad = {base = {pos = {x = 20, y = 35}},},
seismitoad = {base = {pos = {x = 22, y = 35}},},
throh = {base = {pos = {x = 24, y = 35}},},
sawk = {base = {pos = {x = 26, y = 35}},},
sewaddle = {base = {pos = {x = 28, y = 35}},},
swadloon = {base = {pos = {x = 0, y = 36}},},
leavanny = {base = {pos = {x = 2, y = 36}},},
venipede = {base = {pos = {x = 4, y = 36}},},
whirlipede = {base = {pos = {x = 6, y = 36}}, alts = {AtlasJokersSeriesA = {artist = 'Maelmc'}}},
scolipede = {base = {pos = {x = 8, y = 36}},},
cottonee = {base = {pos = {x = 10, y = 36}},},
whimsicott = {base = {pos = {x = 12, y = 36}},},
petilil = {base = {pos = {x = 14, y = 36}},},
lilligant = {base = {pos = {x = 16, y = 36}},},
basculin = {base = {pos = {x = 18, y = 36}},},
sandile = {base = {pos = {x = 20, y = 36}},},
krokorok = {base = {pos = {x = 22, y = 36}},},
krookodile = {base = {pos = {x = 24, y = 36}},},
darumaka = {base = {pos = {x = 26, y = 36}},},
darmanitan = {base = {pos = {x = 28, y = 36}},},
maractus = {base = {pos = {x = 0, y = 37}},},
dwebble = {base = {pos = {x = 2, y = 37}},},
crustle = {base = {pos = {x = 4, y = 37}},},
scraggy = {base = {pos = {x = 6, y = 37}},},
scrafty = {base = {pos = {x = 8, y = 37}},},
sigilyph = {base = {pos = {x = 10, y = 37}},},
yamask = {base = {pos = {x = 12, y = 37}},},
cofagrigus = {base = {pos = {x = 14, y = 37}},},
tirtouga = {base = {pos = {x = 16, y = 37}},},
carracosta = {base = {pos = {x = 18, y = 37}},},
archen = {base = {pos = {x = 20, y = 37}},},
archeops = {base = {pos = {x = 22, y = 37}},},
trubbish = {base = {pos = {x = 24, y = 37}},alts = {AtlasJokersSeriesA = {artist = 'MyDude_YT'}}},
garbodor = {base = {pos = {x = 26, y = 37}},alts = {AtlasJokersSeriesA = {artist = 'MyDude_YT'}}},
zorua = {base = {pos = {x = 28, y = 37}},},
zoroark = {base = {pos = {x = 0, y = 38}},},
minccino = {base = {pos = {x = 2, y = 38}},},
cinccino = {base = {pos = {x = 4, y = 38}},},
gothita = {base = {pos = {x = 6, y = 38}}, alts = {AtlasJokersSeriesA = {artist = 'RedHaering'}}},
gothorita = {base = {pos = {x = 8, y = 38}}, alts = {AtlasJokersSeriesA = {artist = 'RedHaering'}}},
gothitelle = {base = {pos = {x = 10, y = 38}},},
solosis = {base = {pos = {x = 12, y = 38}},},
duosion = {base = {pos = {x = 14, y = 38}},},
reuniclus = {base = {pos = {x = 16, y = 38}},},
ducklett = {base = {pos = {x = 18, y = 38}},},
swanna = {base = {pos = {x = 20, y = 38}},},
vanillite = {base = {pos = {x = 22, y = 38}},},
vanillish = {base = {pos = {x = 24, y = 38}},},
vanilluxe = {base = {pos = {x = 26, y = 38}},},
deerling = {base = {pos = {x = 28, y = 38}},},
sawsbuck = {base = {pos = {x = 0, y = 39}},},
emolga = {base = {pos = {x = 2, y = 39}},},
karrablast = {base = {pos = {x = 4, y = 39}},},
escavalier = {base = {pos = {x = 6, y = 39}},},
foongus = {base = {pos = {x = 8, y = 39}},},
amoonguss = {base = {pos = {x = 10, y = 39}},},
frillish = {base = {pos = {{x = 6, y = 2}, {x= 8, y = 2}}}, gen_atlas = true,},
jellicent = {base = {pos = {{x = 10, y = 2}, {x= 0, y = 3}}}, gen_atlas = true,},
alomomola = {base = {pos = {x = 16, y = 39}},},
joltik = {base = {pos = {x = 18, y = 39}},alts = {AtlasJokersSeriesA = {artist = 'RedHaering'}}},
galvantula = {base = {pos = {x = 20, y = 39}},},
ferroseed = {base = {pos = {x = 22, y = 39}},},
ferrothorn = {base = {pos = {x = 24, y = 39}},},
klink = {base = {pos = {x = 26, y = 39}},},
klang = {base = {pos = {x = 28, y = 39}},},
klinklang = {base = {pos = {x = 0, y = 40}},},
tynamo = {base = {pos = {x = 2, y = 40}},},
eelektrik = {base = {pos = {x = 4, y = 40}},},
eelektross = {base = {pos = {x = 6, y = 40}},},
elgyem = {base = {pos = {x = 8, y = 40}},},
beheeyem = {base = {pos = {x = 10, y = 40}},},
litwick = {base = {pos = {x = 12, y = 40}}, alts = {AtlasJokersSeriesA = {artist = 'RedHaering'}}},
lampent = {base = {pos = {x = 14, y = 40}},},
chandelure = {base = {pos = {x = 16, y = 40}},},
axew = {base = {pos = {x = 18, y = 40}},},
fraxure = {base = {pos = {x = 20, y = 40}},},
haxorus = {base = {pos = {x = 22, y = 40}},},
cubchoo = {base = {pos = {x = 24, y = 40}},},
beartic = {base = {pos = {x = 26, y = 40}},alts = {AtlasJokersSeriesA = {artist = 'TunaBear'}}},
cryogonal = {base = {pos = {x = 28, y = 40}},},
shelmet = {base = {pos = {x = 0, y = 41}},},
accelgor = {base = {pos = {x = 2, y = 41}},},
stunfisk = {base = {pos = {x = 4, y = 41}},},
mienfoo = {base = {pos = {x = 6, y = 41}},},
mienshao = {base = {pos = {x = 8, y = 41}},},
druddigon = {base = {pos = {x = 10, y = 41}},},
golett = {base = {pos = {x = 12, y = 41}},},
golurk = {base = {pos = {x = 14, y = 41}},},
pawniard = {base = {pos = {x = 16, y = 41}},},
bisharp = {base = {pos = {x = 18, y = 41}},},
bouffalant = {base = {pos = {x = 20, y = 41}},},
rufflet = {base = {pos = {x = 22, y = 41}},},
braviary = {base = {pos = {x = 24, y = 41}},},
vullaby = {base = {pos = {x = 26, y = 41}},},
mandibuzz = {base = {pos = {x = 28, y = 41}},},
heatmor = {base = {pos = {x = 0, y = 42}},},
durant = {base = {pos = {x = 2, y = 42}},},
deino = {base = {pos = {x = 4, y = 42}},},
zweilous = {base = {pos = {x = 6, y = 42}},},
hydreigon = {base = {pos = {x = 8, y = 42}},},
larvesta = {base = {pos = {x = 10, y = 42}},},
volcarona = {base = {pos = {x = 12, y = 42}},},
cobalion = {base = {pos = {x = 14, y = 42}, soul_pos = {x = 15, y = 42}},},
terrakion = {base = {pos = {x = 16, y = 42}, soul_pos = {x = 17, y = 42}},},
virizion = {base = {pos = {x = 18, y = 42}, soul_pos = {x = 19, y = 42}},},
tornadus = {base = {pos = {x = 20, y = 42}, soul_pos = {x = 21, y = 42}},},
thundurus = {base = {pos = {x = 22, y = 42}, soul_pos = {x = 23, y = 42}},},
reshiram = {base = {pos = {x = 24, y = 42}, soul_pos = {x = 25, y = 42}},},
zekrom = {base = {pos = {x = 26, y = 42}, soul_pos = {x = 27, y = 42}},},
landorus = {base = {pos = {x = 28, y = 42}, soul_pos = {x = 29, y = 42}},},
kyurem = {base = {pos = {x = 0, y = 43}, soul_pos = {x = 1, y = 43}},},
keldeo = {base = {pos = {x = 2, y = 43}, soul_pos = {x = 3, y = 43}},},
meloetta = {base = {pos = {x = 4, y = 43}, soul_pos = {x = 5, y = 43}},},
genesect = {base = {pos = {x = 6, y = 43}, soul_pos = {x = 7, y = 43}},},
chespin = {base = {pos = {x = 8, y = 43}},},
quilladin = {base = {pos = {x = 10, y = 43}},},
chesnaught = {base = {pos = {x = 12, y = 43}},},
fennekin = {base = {pos = {x = 14, y = 43}},},
braixen = {base = {pos = {x = 16, y = 43}},},
delphox = {base = {pos = {x = 18, y = 43}},},
froakie = {base = {pos = {x = 20, y = 43}},},
frogadier = {base = {pos = {x = 22, y = 43}},},
greninja = {base = {pos = {x = 24, y = 43}},},
bunnelby = {base = {pos = {x = 26, y = 43}},},
diggersby = {base = {pos = {x = 28, y = 43}},},
fletchling = {base = {pos = {x = 0, y = 44}}, alts = {AtlasJokersSeriesA = {artist = 'Alber_Pro'}}},
fletchinder = {base = {pos = {x = 2, y = 44}},},
talonflame = {base = {pos = {x = 4, y = 44}}, alts = {AtlasJokersSeriesA = {artist = 'Alber_Pro'}}},
scatterbug = {base = {pos = {x = 6, y = 44}},},
spewpa = {base = {pos = {x = 8, y = 44}},},
vivillon = {base = {pos = {x = 10, y = 44}},},
litleo = {base = {pos = {x = 12, y = 44}},alts = {AtlasJokersSeriesA = {artist = 'Xenellia'}}},
pyroar = {base = {pos = {{x = 4, y = 3}, {x= 6, y = 3}}}, gen_atlas = true,},
flabebe = {base = {pos = {x = 16, y = 44}},},
floette = {base = {pos = {x = 18, y = 44}},},
florges = {base = {pos = {x = 20, y = 44}},},
skiddo = {base = {pos = {x = 22, y = 44}},},
gogoat = {base = {pos = {x = 24, y = 44}},},
pancham = {base = {pos = {x = 26, y = 44}},},
pangoro = {base = {pos = {x = 28, y = 44}},},
furfrou = {base = {pos = {x = 0, y = 45}},},
espurr = {base = {pos = {x = 2, y = 45}},},
meowstic = {base = {pos = {x = 4, y = 45}},},
honedge = {base = {pos = {x = 6, y = 45}},},
doublade = {base = {pos = {x = 8, y = 45}},},
aegislash = {base = {pos = {x = 10, y = 45}},},
spritzee = {base = {pos = {x = 12, y = 45}},},
aromatisse = {base = {pos = {x = 14, y = 45}},},
swirlix = {base = {pos = {x = 16, y = 45}},},
slurpuff = {base = {pos = {x = 18, y = 45}},},
inkay = {base = {pos = {x = 20, y = 45}},},
malamar = {base = {pos = {x = 22, y = 45}},},
binacle = {base = {pos = {x = 24, y = 45}},},
barbaracle = {base = {pos = {x = 26, y = 45}},},
skrelp = {base = {pos = {x = 28, y = 45}},},
dragalge = {base = {pos = {x = 0, y = 46}},},
clauncher = {base = {pos = {x = 2, y = 46}},},
clawitzer = {base = {pos = {x = 4, y = 46}},},
helioptile = {base = {pos = {x = 6, y = 46}},},
heliolisk = {base = {pos = {x = 8, y = 46}},},
tyrunt = {base = {pos = {x = 10, y = 46}},},
tyrantrum = {base = {pos = {x = 12, y = 46}},},
amaura = {base = {pos = {x = 14, y = 46}},},
aurorus = {base = {pos = {x = 16, y = 46}},},
sylveon = {base = {pos = {x = 18, y = 46}},},
hawlucha = {base = {pos = {x = 20, y = 46}},},
dedenne = {base = {pos = {x = 22, y = 46}},},
carbink = {base = {pos = {x = 24, y = 46}},alts = {AtlasJokersSeriesA = {artist = 'MyDude_YT'}}},
goomy = {base = {pos = {x = 26, y = 46}},},
sliggoo = {base = {pos = {x = 28, y = 46}},},
goodra = {base = {pos = {x = 0, y = 47}},},
klefki = {base = {pos = {x = 2, y = 47}},},
phantump = {base = {pos = {x = 4, y = 47}},},
trevenant = {base = {pos = {x = 6, y = 47}},},
pumpkaboo = {base = {pos = {x = 0, y = 9}},gen_atlas = true},
gourgeist = {base = {pos = {x = 8, y = 9}},gen_atlas = true},
bergmite = {base = {pos = {x = 12, y = 47}},},
avalugg = {base = {pos = {x = 14, y = 47}},},
noibat = {base = {pos = {x = 16, y = 47}},},
noivern = {base = {pos = {x = 18, y = 47}},},
xerneas = {base = {pos = {x = 20, y = 47}, soul_pos = {x = 21, y = 47}},},
yveltal = {base = {pos = {x = 22, y = 47}, soul_pos = {x = 3, y = 47}},},
zygarde = {base = {pos = {x = 24, y = 47}, soul_pos = {x = 25, y = 47}},},
diancie = {base = {pos = {x = 26, y = 47}, soul_pos = {x = 27, y = 47}},},
hoopa = {base = {pos = {x = 28, y = 47}, soul_pos = {x = 29, y = 47}},},
volcanion = {base = {pos = {x = 0, y = 48}, soul_pos = {x = 1, y = 48}},},
rowlet = {base = {pos = {x = 2, y = 48}},},
dartrix = {base = {pos = {x = 4, y = 48}},},
decidueye = {base = {pos = {x = 6, y = 48}},},
litten = {base = {pos = {x = 8, y = 48}},},
torracat = {base = {pos = {x = 10, y = 48}},},
incineroar = {base = {pos = {x = 12, y = 48}},},
popplio = {base = {pos = {x = 14, y = 48}},},
brionne = {base = {pos = {x = 16, y = 48}},},
primarina = {base = {pos = {x = 18, y = 48}},},
pikipek = {base = {pos = {x = 20, y = 48}},},
trumbeak = {base = {pos = {x = 22, y = 48}},},
toucannon = {base = {pos = {x = 24, y = 48}},},
yungoos = {base = {pos = {x = 26, y = 48}},},
gumshoos = {base = {pos = {x = 28, y = 48}},},
grubbin = {base = {pos = {x = 0, y = 49}}, alts= {AtlasJokersSeriesA = {artist = 'Gappie'}}},
charjabug = {base = {pos = {x = 2, y = 49}},},
vikavolt = {base = {pos = {x = 4, y = 49}},},
crabrawler = {base = {pos = {x = 6, y = 49}},},
crabominable = {base = {pos = {x = 8, y = 49}},},
oricorio = {base = {pos = {x = 10, y = 49}},},
cutiefly = {base = {pos = {x = 12, y = 49}},},
ribombee = {base = {pos = {x = 14, y = 49}},},
rockruff = {base = {pos = {x = 16, y = 49}},},
lycanroc_day = {base = {pos = {x = 8, y = 0}},gen_atlas = true},
lycanroc_night = {base = {pos = {x = 10, y = 0}},gen_atlas = true},
lycanroc_dusk = {base = {pos = {x = 0, y = 1}},gen_atlas = true},
wishiwashi = {base = {pos = {x = 20, y = 49}},},
mareanie = {base = {pos = {x = 22, y = 49}},},
toxapex = {base = {pos = {x = 24, y = 49}},},
mudbray = {base = {pos = {x = 26, y = 49}},},
mudsdale = {base = {pos = {x = 28, y = 49}},},
dewpider = {base = {pos = {x = 0, y = 50}},},
araquanid = {base = {pos = {x = 2, y = 50}},},
fomantis = {base = {pos = {x = 4, y = 50}},},
lurantis = {base = {pos = {x = 6, y = 50}},},
morelull = {base = {pos = {x = 8, y = 50}},},
shiinotic = {base = {pos = {x = 10, y = 50}},},
salandit = {base = {pos = {x = 12, y = 50}},},
salazzle = {base = {pos = {x = 14, y = 50}},},
stufful = {base = {pos = {x = 16, y = 50}},},
bewear = {base = {pos = {x = 18, y = 50}},},
bounsweet = {base = {pos = {x = 20, y = 50}},},
steenee = {base = {pos = {x = 22, y = 50}},},
tsareena = {base = {pos = {x = 24, y = 50}},},
comfey = {base = {pos = {x = 26, y = 50}},},
oranguru = {base = {pos = {x = 28, y = 50}},},
passimian = {base = {pos = {x = 0, y = 51}},},
wimpod = {base = {pos = {x = 2, y = 51}},},
golisopod = {base = {pos = {x = 4, y = 51}},},
sandygast = {base = {pos = {x = 6, y = 51}},alts = {AtlasJokersSeriesA = {artist = 'Gappie'}}},
palossand = {base = {pos = {x = 8, y = 51}},},
pyukumuku = {base = {pos = {x = 10, y = 51}}, alts = {AtlasJokersSeriesA = {artist = 'Gappie'}}},
typenull = {base = {pos = {x = 12, y = 51}, soul_pos =  {x = 13, y = 51}},},
silvally = {base = {pos = {x = 14, y = 51}, soul_pos =  {x = 15, y = 51}},},
minior = {base = {pos = {x = 16, y = 51}, soul_pos =  {x = 17, y = 51}},},
komala = {base = {pos = {x = 18, y = 51}},},
turtonator = {base = {pos = {x = 20, y = 51}},},
togedemaru = {base = {pos = {x = 22, y = 51}},},
mimikyu = {base = {pos = {x = 24, y = 51}},lookup_gen_atlas = true},
bruxish = {base = {pos = {x = 26, y = 51}},},
drampa = {base = {pos = {x = 28, y = 51}},},
dhelmise = {base = {pos = {x = 0, y = 52}},},
jangmoo = {base = {pos = {x = 2, y = 52}},},
hakamoo = {base = {pos = {x = 4, y = 52}},},
kommoo = {base = {pos = {x = 6, y = 52}},},
tapu_koko = {base = {pos = {x = 8, y = 52}, soul_pos =  {x = 9, y = 52}},},
tapu_lele = {base = {pos = {x = 10, y = 52}, soul_pos =  {x = 11, y = 52}},},
tapu_bulu = {base = {pos = {x = 12, y = 52}, soul_pos =  {x = 13, y = 52}},},
tapu_fini = {base = {pos = {x = 14, y = 52}, soul_pos =  {x = 15, y = 52}},},
cosmog = {base = {pos = {x = 16, y = 52}, soul_pos =  {x = 17, y = 52}},},
cosmoem = {base = {pos = {x = 18, y = 52}, soul_pos =  {x = 19, y = 52}},},
solgaleo = {base = {pos = {x = 20, y = 52}, soul_pos =  {x = 21, y = 52}},},
lunala = {base = {pos = {x = 22, y = 52}, soul_pos =  {x = 23, y = 52}},},
nihilego = {base = {pos = {x = 24, y = 52}, soul_pos =  {x = 25, y = 52}},},
buzzwole = {base = {pos = {x = 26, y = 52}, soul_pos =  {x = 27, y = 52}},},
pheromosa = {base = {pos = {x = 28, y = 52}, soul_pos =  {x = 29, y = 52}},},
xurkitree = {base = {pos = {x = 0, y = 53}, soul_pos =  {x = 1, y = 53}},},
celesteela = {base = {pos = {x = 2, y = 53}, soul_pos =  {x = 3, y = 53}},},
kartana = {base = {pos = {x = 4, y = 53}, soul_pos =  {x = 5, y = 53}},},
guzzlord = {base = {pos = {x = 6, y = 53}, soul_pos =  {x = 7, y = 53}},},
necrozma = {base = {pos = {x = 8, y = 53}, soul_pos =  {x = 9, y = 53}},},
magearna = {base = {pos = {x = 10, y = 53}, soul_pos =  {x = 11, y = 53}},},
marshadow = {base = {pos = {x = 12, y = 53}, soul_pos =  {x = 13, y = 53}},},
poipole = {base = {pos = {x = 14, y = 53}, soul_pos =  {x = 15, y = 53}},},
naganadel = {base = {pos = {x = 16, y = 53}, soul_pos =  {x = 17, y = 53}},},
stakataka = {base = {pos = {x = 18, y = 53}, soul_pos =  {x = 19, y = 53}},},
blacephalon = {base = {pos = {x = 20, y = 53}, soul_pos =  {x = 21, y = 53}},},
zeraora = {base = {pos = {x = 22, y = 53}, soul_pos =  {x = 23, y = 53}},},
meltan = {base = {pos = {x = 24, y = 53}, soul_pos =  {x = 25, y = 53}},},
melmetal = {base = {pos = {x = 26, y = 53}, soul_pos =  {x = 27, y = 53}},},
grookey = {base = {pos = {x = 28, y = 53}},},
thwackey = {base = {pos = {x = 0, y = 54}},},
rillaboom = {base = {pos = {x = 2, y = 54}},},
scorbunny = {base = {pos = {x = 4, y = 54}},},
raboot = {base = {pos = {x = 6, y = 54}},},
cinderace = {base = {pos = {x = 8, y = 54}},},
sobble = {base = {pos = {x = 10, y = 54}},},
drizzile = {base = {pos = {x = 12, y = 54}},},
inteleon = {base = {pos = {x = 14, y = 54}},},
skwovet = {base = {pos = {x = 16, y = 54}},},
greedent = {base = {pos = {x = 18, y = 54}},},
rookidee = {base = {pos = {x = 20, y = 54}},},
corvisquire = {base = {pos = {x = 22, y = 54}},},
corviknight = {base = {pos = {x = 24, y = 54}},},
blipbug = {base = {pos = {x = 26, y = 54}},},
dottler = {base = {pos = {x = 28, y = 54}},},
orbeetle = {base = {pos = {x = 0, y = 55}},},
nickit = {base = {pos = {x = 2, y = 55}},},
thievul = {base = {pos = {x = 4, y = 55}},},
gossifleur = {base = {pos = {x = 6, y = 55}},},
eldegoss = {base = {pos = {x = 8, y = 55}},},
wooloo = {base = {pos = {x = 10, y = 55}},},
dubwool = {base = {pos = {x = 12, y = 55}},},
chewtle = {base = {pos = {x = 14, y = 55}},},
drednaw = {base = {pos = {x = 16, y = 55}},},
yamper = {base = {pos = {x = 18, y = 55}},},
boltund = {base = {pos = {x = 20, y = 55}},},
rolycoly = {base = {pos = {x = 22, y = 55}},},
carkol = {base = {pos = {x = 24, y = 55}},},
coalossal = {base = {pos = {x = 26, y = 55}},},
applin = {base = {pos = {x = 28, y = 55}},},
flapple = {base = {pos = {x = 0, y = 56}},alts = {AtlasJokersSeriesA = {artist = 'Celsie_RS'}}},
appletun = {base = {pos = {x = 2, y = 56}},},
silicobra = {base = {pos = {x = 4, y = 56}},},
sandaconda = {base = {pos = {x = 6, y = 56}},},
cramorant = {base = {pos = {x = 8, y = 56}},},
arrokuda = {base = {pos = {x = 10, y = 56}},},
barraskewda = {base = {pos = {x = 12, y = 56}},},
toxel = {base = {pos = {x = 14, y = 56}},},
toxtricity = {base = {pos = {x = 16, y = 56}},},
sizzlipede = {base = {pos = {x = 18, y = 56}},},
centiskorch = {base = {pos = {x = 20, y = 56}},},
clobbopus = {base = {pos = {x = 22, y = 56}},},
grapploct = {base = {pos = {x = 24, y = 56}},},
sinistea = {base = {pos = {x = 26, y = 56}},},
polteageist = {base = {pos = {x = 28, y = 56}},},
hatenna = {base = {pos = {x = 0, y = 57}},},
hattrem = {base = {pos = {x = 2, y = 57}},},
hatterene = {base = {pos = {x = 4, y = 57}},},
impidimp = {base = {pos = {x = 6, y = 57}},},
morgrem = {base = {pos = {x = 8, y = 57}},},
grimmsnarl = {base = {pos = {x = 10, y = 57}},},
obstagoon = {base = {pos = {x = 12, y = 57}},},
perrserker = {base = {pos = {x = 14, y = 57}},},
cursola = {base = {pos = {x = 16, y = 57}},},
sirfetchd = {base = {pos = {x = 18, y = 57}},},
mrrime = {base = {pos = {x = 20, y = 57}},},
runerigus = {base = {pos = {x = 22, y = 57}},},
milcery = {base = {pos = {x = 24, y = 57}},},
alcremie = {base = {pos = {x = 26, y = 57}},},
falinks = {base = {pos = {x = 28, y = 57}},},
pincurchin = {base = {pos = {x = 0, y = 58}},},
snom = {base = {pos = {x = 2, y = 58}},},
frosmoth = {base = {pos = {x = 4, y = 58}},},
stonjourner = {base = {pos = {x = 6, y = 58}},},
eiscue = {base = {pos = {x = 8, y = 58}},},
indeedee = {base = {pos = {x = 10, y = 58}},},
morpeko = {base = {pos = {x = 12, y = 58}},},
cufant = {base = {pos = {x = 14, y = 58}},},
copperajah = {base = {pos = {x = 16, y = 58}},},
dracozolt = {base = {pos = {x = 18, y = 58}},},
arctozolt = {base = {pos = {x = 20, y = 58}},},
dracovish = {base = {pos = {x = 22, y = 58}},},
arctovish = {base = {pos = {x = 24, y = 58}},},
duraludon = {base = {pos = {x = 26, y = 58}},},
dreepy = {base = {pos = {x = 28, y = 58}},},
dreepy_dart = {base = {pos = {x = 4, y = 9}},gen_atlas = true},
drakloak = {base = {pos = {x = 0, y = 59}},},
dragapult = {base = {pos = {x = 2, y = 59}},},
zacian = {base = {pos = {x = 4, y = 59}, soul_pos =  {x = 5, y = 59}},},
zamazenta = {base = {pos = {x = 6, y = 59}, soul_pos =  {x = 7, y = 59}},},
eternatus = {base = {pos = {x = 8, y = 59}, soul_pos =  {x = 9, y = 59}},},
kubfu = {base = {pos = {x = 10, y = 59}, soul_pos =  {x = 11, y = 59}},},
urshifu = {base = {pos = {x = 12, y = 59}, soul_pos =  {x = 13, y = 59}},},
zarude = {base = {pos = {x = 14, y = 59}, soul_pos =  {x = 15, y = 59}},},
regieleki = {base = {pos = {x = 16, y = 59}, soul_pos =  {x = 17, y = 59}},},
regidrago = {base = {pos = {x = 18, y = 59}, soul_pos =  {x = 19, y = 59}},},
glastrier = {base = {pos = {x = 20, y = 59}, soul_pos =  {x = 21, y = 59}},},
spectrier = {base = {pos = {x = 22, y = 59}, soul_pos =  {x = 23, y = 59}},},
calyrex = {base = {pos = {x = 24, y = 59}, soul_pos =  {x = 25, y = 59}},},
wyrdeer = {base = {pos = {x = 26, y = 59}},},
kleavor = {base = {pos = {x = 28, y = 59}},},
ursaluna = {base = {pos = {x = 0, y = 60}},},
basculegion = {base = {pos = {x = 2, y = 60}},},
sneasler = {base = {pos = {x = 4, y = 60}},},
overqwil = {base = {pos = {x = 6, y = 60}},},
enamorus = {base = {pos = {x = 8, y = 60}, soul_pos =  {x = 9, y = 60}},},
sprigatito = {base = {pos = {x = 10, y = 60}},},
floragato = {base = {pos = {x = 12, y = 60}},},
meowscarada = {base = {pos = {x = 14, y = 60}},},
fuecoco = {base = {pos = {x = 16, y = 60}},},
crocalor = {base = {pos = {x = 18, y = 60}},},
skeledirge = {base = {pos = {x = 20, y = 60}},},
quaxly = {base = {pos = {x = 22, y = 60}},},
quaxwell = {base = {pos = {x = 24, y = 60}},},
quaquaval = {base = {pos = {x = 26, y = 60}},},
lechonk = {base = {pos = {x = 28, y = 60}},alts = {AtlasJokersSeriesA = {artist = 'Sonfive'}}},
oinkologne = {base = {pos = {x = 0, y = 61}},},
tarountula = {base = {pos = {x = 2, y = 61}},},
spidops = {base = {pos = {x = 4, y = 61}},},
nymble = {base = {pos = {x = 6, y = 61}},},
lokix = {base = {pos = {x = 8, y = 61}},},
pawmi = {base = {pos = {x = 10, y = 61}},},
pawmo = {base = {pos = {x = 12, y = 61}},},
pawmot = {base = {pos = {x = 14, y = 61}},},
tandemaus = {base = {pos = {x = 16, y = 61}},},
maushold = {base = {pos = {x = 18, y = 61}},},
fidough = {base = {pos = {x = 20, y = 61}},},
dachsbun = {base = {pos = {x = 22, y = 61}},},
smoliv = {base = {pos = {x = 24, y = 61}},},
dolliv = {base = {pos = {x = 26, y = 61}},},
arboliva = {base = {pos = {x = 28, y = 61}},},
squawkabilly = {base = {pos = {x = 0, y = 62}},},
nacli = {base = {pos = {x = 2, y = 62}},},
naclstack = {base = {pos = {x = 4, y = 62}},},
garganacl = {base = {pos = {x = 6, y = 62}},},
charcadet = {base = {pos = {x = 8, y = 62}},},
armarouge = {base = {pos = {x = 10, y = 62}},},
ceruledge = {base = {pos = {x = 12, y = 62}},},
tadbulb = {base = {pos = {x = 14, y = 62}},},
bellibolt = {base = {pos = {x = 16, y = 62}},},
wattrel = {base = {pos = {x = 18, y = 62}},},
kilowattrel = {base = {pos = {x = 20, y = 62}},},
maschiff = {base = {pos = {x = 22, y = 62}},},
mabosstiff = {base = {pos = {x = 24, y = 62}},},
shroodle = {base = {pos = {x = 26, y = 62}},},
grafaiai = {base = {pos = {x = 28, y = 62}},},
bramblin = {base = {pos = {x = 0, y = 63}},},
brambleghast = {base = {pos = {x = 2, y = 63}},},
toedscool = {base = {pos = {x = 4, y = 63}},},
toedscruel = {base = {pos = {x = 6, y = 63}},},
klawf = {base = {pos = {x = 8, y = 63}},},
capsakid = {base = {pos = {x = 10, y = 63}},},
scovillain = {base = {pos = {x = 12, y = 63}},},
rellor = {base = {pos = {x = 14, y = 63}},},
rabsca = {base = {pos = {x = 16, y = 63}},},
flittle = {base = {pos = {x = 18, y = 63}},},
espathra = {base = {pos = {x = 20, y = 63}},},
tinkatink = {base = {pos = {x = 22, y = 63}},},
tinkatuff = {base = {pos = {x = 24, y = 63}},},
tinkaton = {base = {pos = {x = 26, y = 63}},},
wiglett = {base = {pos = {x = 28, y = 63}},},
wugtrio = {base = {pos = {x = 0, y = 64}},},
bombirdier = {base = {pos = {x = 2, y = 64}},},
finizen = {base = {pos = {x = 4, y = 64}},},
palafin = {base = {pos = {x = 6, y = 64}},},
varoom = {base = {pos = {x = 8, y = 64}},},
revavroom = {base = {pos = {x = 10, y = 64}},},
cyclizar = {base = {pos = {x = 12, y = 64}},},
orthworm = {base = {pos = {x = 14, y = 64}},},
glimmet = {base = {pos = {x = 16, y = 64}},},
glimmora = {base = {pos = {x = 18, y = 64}},},
greavard = {base = {pos = {x = 20, y = 64}},},
houndstone = {base = {pos = {x = 22, y = 64}},},
flamigo = {base = {pos = {x = 24, y = 64}},},
cetoddle = {base = {pos = {x = 26, y = 64}},alts = {AtlasJokersSeriesA = {artist = 'Sonfive', 'Ayako Ozaki'}}},
cetitan = {base = {pos = {x = 28, y = 64}},},
veluza = {base = {pos = {x = 0, y = 65}},},
dondozo = {base = {pos = {x = 2, y = 65}},},
tatsugiri = {base = {pos = {x = 4, y = 65}},},
annihilape = {base = {pos = {x = 6, y = 65}},},
clodsire = {base = {pos = {x = 8, y = 65}},},
farigiraf = {base = {pos = {x = 10, y = 65}},},
dudunsparce = {base = {pos = {x = 6, y = 3}}, gen_atlas = true,},
kingambit = {base = {pos = {x = 14, y = 65}},},
great_tusk = {base = {pos = {x = 16, y = 65}, soul_pos =  {x = 17, y = 65}},},
scream_tail = {base = {pos = {x = 18, y = 65}, soul_pos =  {x = 19, y = 65}},},
brute_bonnet = {base = {pos = {x = 20, y = 65}, soul_pos =  {x = 21, y = 65}},},
flutter_mane = {base = {pos = {x = 22, y = 65}, soul_pos =  {x = 23, y = 65}},},
slither_wing = {base = {pos = {x = 24, y = 65}, soul_pos =  {x = 25, y = 65}},},
sandy_shocks = {base = {pos = {x = 26, y = 65}, soul_pos =  {x = 27, y = 65}},},
iron_treads = {base = {pos = {x = 28, y = 65}, soul_pos =  {x = 29, y = 65}},},
iron_bundle = {base = {pos = {x = 0, y = 66}, soul_pos =  {x = 1, y = 66}},},
iron_hands = {base = {pos = {x = 2, y = 66}, soul_pos =  {x = 3, y = 66}},},
iron_jugulis = {base = {pos = {x = 4, y = 66}, soul_pos =  {x = 5, y = 66}},},
iron_moth = {base = {pos = {x = 6, y = 66}, soul_pos =  {x = 7, y = 66}},},
iron_thorns = {base = {pos = {x = 8, y = 66}, soul_pos =  {x = 9, y = 66}},},
frigibax = {base = {pos = {x = 10, y = 66}},},
arctibax = {base = {pos = {x = 12, y = 66}},},
baxcalibur = {base = {pos = {x = 14, y = 66}},},
gimmighoul = {base = {pos = {x = 16, y = 66}},},
gimmighoulr = {base = {pos = {x = 0, y = 4}}, gen_atlas = true,},
gholdengo = {base = {pos = {x = 18, y = 66}},},
wochien = {base = {pos = {x = 20, y = 66}, soul_pos =  {x = 21, y = 66}},},
chienpao = {base = {pos = {x = 22, y = 66}, soul_pos =  {x = 23, y = 66}},},
tinglu = {base = {pos = {x = 24, y = 66}, soul_pos =  {x = 25, y = 66}},},
chiyu = {base = {pos = {x = 26, y = 66}, soul_pos =  {x = 27, y = 66}},},
roaring_moon = {base = {pos = {x = 28, y = 66}, soul_pos =  {x = 29, y = 66}},},
iron_valiant = {base = {pos = {x = 0, y = 67}, soul_pos =  {x = 1, y = 67}},},
koraidon = {base = {pos = {x = 2, y = 67}, soul_pos =  {x = 1, y = 67}},},
miraidon = {base = {pos = {x = 4, y = 67}, soul_pos =  {x = 3, y = 67}},},
walking_wake = {base = {pos = {x = 6, y = 67}, soul_pos =  {x = 5, y = 67}},},
iron_leaves = {base = {pos = {x = 8, y = 67}, soul_pos =  {x = 7, y = 67}},},
dipplin = {base = {pos = {x = 10, y = 67}},},
poltchageist = {base = {pos = {x = 12, y = 67}},},
sinistcha = {base = {pos = {x = 14, y = 67}},},
okidogi = {base = {pos = {x = 16, y = 67}, soul_pos =  {x = 17, y = 67}},},
munkidori = {base = {pos = {x = 18, y = 67}, soul_pos =  {x = 19, y = 67}},},
fezandipiti = {base = {pos = {x = 20, y = 67}, soul_pos =  {x = 21, y = 67}},},
ogerpon = {base = {pos = {x = 22, y = 67}, soul_pos =  {x = 23, y = 67}},},
archaludon = {base = {pos = {x = 24, y = 67}},},
hydrapple = {base = {pos = {x = 26, y = 67}},},
gouging_fire = {base = {pos = {x = 28, y = 67}, soul_pos =  {x = 29, y = 67}},},
raging_bolt = {base = {pos = {x = 0, y = 68}, soul_pos =  {x = 1, y = 68}},},
iron_boulder = {base = {pos = {x = 2, y = 68}, soul_pos =  {x = 3, y = 68}},},
iron_crown = {base = {pos = {x = 4, y = 68}, soul_pos =  {x = 5, y = 68}},},
terapagos = {base = {pos = {x = 6, y = 68}, soul_pos =  {x = 7, y = 68}},},
pecharunt = {base = {pos = {x = 8, y = 68}, soul_pos =  {x = 9, y = 68}},},
pokedex = {base = {pos = {x = 0, y = 0}}, others_atlas = true,},
--rotomdex = {base = {pos = {x = 0, y = 0}}, others_atlas = true,},
everstone = {base = {pos = {x = 2, y = 0}}, others_atlas = true,},
tall_grass = {base = {pos = {x = 4, y = 0}}, others_atlas = true,},
jelly_donut = {base = {pos = {x = 6, y = 0}}, others_atlas = true,},
treasure_eatery = {base = {pos = {x = 6, y = 2}}, others_atlas = true,},
mystery_egg = {base = {pos = {x = 0, y = 1}}, others_atlas = true,},
rival = {base = {pos = {x = 0, y = 2}}, others_atlas = true,},
ruins_of_alph = {base = {pos = {x = 0, y = 3}}, others_atlas = true,},
professor = {base = {pos = {x = 4, y = 1}}, others_atlas = true,},
billion_lions = {base = {pos = {x = 4, y = 3}, soul_pos = {x = 5, y = 3}}, others_atlas = true,},
} 

local poke_artist_info = {
  Alber_Pro = {display_name = 'Alber_Pro', artist_colour = HEX('FFAE00')},
  bt = {display_name = 'bt', artist_colour = HEX("2C4522"), highlight_colour = HEX("efead8")},
  Captain_Slime = {display_name = 'Captain Slime', artist_colour = HEX("F7C429")},
  Catzzadilla = {display_name = 'Catzzadilla', artist_colour = HEX("F3CC3C"), highlight_colour = HEX("A400FF")},
  CBMX = {display_name = 'CBMX', artist_colour = HEX("FFFFFF"), highlight_colour = HEX("27BBF5")},
  Celsie_RS = {display_name = 'Celsie_RS', artist_colour = HEX("FA8F0B")},
  Chartreuse_Chamber = {display_name = 'Chartreuse Chamber', artist_colour = HEX("B0D820")},
  Desnik = {display_name = 'Desnik', artist_colour = HEX("FDDF00")},
  Dudelings = {display_name = 'Dudelings', artist_colour = HEX("F0493A")},
  Gappie = {display_name = 'Gappie', artist_colour = HEX('FFE062')},
  Maelmc = {display_name = 'Maelmc', artist_colour = HEX("EA6F22")},
  MyDude_YT = {display_name = 'MyDude YT', artist_colour = HEX("FFFFFF"), highlight_colour = HEX("4428BC")},
  PrincessRoxie = {display_name = 'PrincessRoxie', artist_colour = HEX("FF88FF")},
  RedHaering = {display_name = 'RedHaering', artist_colour = HEX("D44540")},
  RibbonOnline = {display_name = 'RibbonOnline', artist_colour = HEX("F11250")},
  Sonfive = {display_name = 'Sonfive', artist_colour = HEX("87DEFF")},
  Silverfish07 = {display_name = 'Silverfish07', artist_colour = HEX('FFAE00')},
  Tovivi = {display_name = 'Tovivi', artist_colour = HEX("FFF700")},
  TunaBear = {display_name = 'TunaBear', artist_colour = HEX("5FEDED")},
  Xenellia = {display_name = 'Xenellia', artist_colour = HEX("9B0000")}
}

poke_load_sprites = function(item)
  local sprite_info = PokemonSprites[item.name]
  local sprite = nil
  local new_pos = {}
  if sprite_info then
    sprite = pokermon_config.pokemon_altart and sprite_info.alt or sprite_info.base
    local position = sprite.pos.x and sprite.pos or nil
    if not position then
      position = sprite.pos[math.random(#sprite.pos)]
      new_pos.x = position.x
      new_pos.y = position.y
      item.poke_multi_sprite = true
    else
      new_pos.x = position.x
      new_pos.y = position.y
    end
    local soul_position = sprite.soul_pos
    
    if position then item.pos = new_pos end
    if soul_position then item.soul_pos = soul_position end
  end
end

poke_get_atlas_prefix = function(name, sprite_info)
  local atlas_prefix = nil
  if pokermon_config.pokemon_spritesheet_overrides[name] then return pokermon_config.pokemon_spritesheet_overrides[name] end
  if sprite_info.alts and sprite_info.alts[pokermon_config.pokemon_spritesheet_atlas] then
    atlas_prefix = pokermon_config.pokemon_spritesheet_atlas
  else
    atlas_prefix = "AtlasJokersBasic"
  end
  return atlas_prefix
end

poke_load_atlas = function(item)
  if not item.poke_custom_atlas and PokemonSprites[item.name] then
    local sprite_info = PokemonSprites[item.name]
    local atlas_prefix = poke_get_atlas_prefix(item.name, sprite_info)
    if sprite_info.alts and sprite_info.alts[atlas_prefix] and sprite_info.alts[atlas_prefix].artist then
      local artist_info = nil
      if type(sprite_info.alts[atlas_prefix].artist) == 'string' then
        artist_info = poke_artist_info[sprite_info.alts[atlas_prefix].artist]
        if artist_info then
          item.artist = artist_info.display_name
          item.artist_colours = {artist_info.artist_colour}
          item.artist_highlight_colours = artist_info.highlight_colour
        end
      else
        local artists = sprite_info.alts[atlas_prefix].artist
        local display_names = {}
        local artist_colours = {}
        item.artist = {}
        item.artist_colours = {}
        item.artist_highlight_colours = {}
        for i = 1, #artists do
          artist_info = poke_artist_info[artists[i]]
          item.artist[#item.artist + 1] = artist_info.display_name
          item.artist_colours[#item.artist_colours + 1] = artist_info.artist_colour
          item.artist_highlight_colours[#item.artist_highlight_colours + 1] = artist_info.highlight_colour
        end
      end
      if sprite_info.alts[atlas_prefix].soul_pos then
        item.soul_pos = sprite_info.alts[atlas_prefix].soul_pos
      end
      if sprite_info.alts[atlas_prefix].anim_atlas then
        item.animated = true
        item.atlas = sprite_info.alts[atlas_prefix].anim_atlas
        item.pos = {x = 0, y = 0}
      end
    end
    if not item.animated then
      if sprite_info.gen_atlas and item.gen then
        local gen_string = nil
        if item.gen < 10 then
          gen_string = 'Gen0'..item.gen 
        else
          gen_string = 'Gen'..item.gen
        end
        item.atlas = atlas_prefix..gen_string
      elseif sprite_info.others_atlas then
        item.atlas = atlas_prefix.."Others"
      else
        item.atlas = atlas_prefix.."Natdex"
      end
      if sprite_info.lookup_gen_atlas and item.gen then
        local gen_string = nil
        if item.gen < 10 then
          gen_string = 'Gen0'..item.gen 
        else
          gen_string = 'Gen'..item.gen
        end
        item.poke_lookup_atlas = atlas_prefix..gen_string
      end
    end
  end
end