[manifest]
version = "1.0.0"
dump_lua = true
priority = -1

#Nested check
[[patches]]
[patches.module]
source = "setup.lua"
before = "main.lua"
name = "pokermon.setup"


# Splash Screen
[[patches]]
[patches.pattern]
target = "game.lua"
pattern = "SC = Card(G.ROOM.T.w/2 - SC_scale*G.CARD_W/2, 10. + G.ROOM.T.h/2 - SC_scale*G.CARD_H/2, SC_scale*G.CARD_W, SC_scale*G.CARD_H, G.P_CARDS.empty, G.P_CENTERS['j_joker'])"
position = "after"
payload = '''
if pokermon_config.pokemon_splash then
  local pokemon = {}
  for k, v in pairs(G.P_CENTERS) do
    if v.set == 'Joker' and v.stage and v.discovered then
      table.insert(pokemon, v)
    end
  end
  if #pokemon > 0 then
    local chosen = math.random(#pokemon)
    local chosencard = pokemon[chosen]
    SC = Card(G.ROOM.T.w/2 - SC_scale*G.CARD_W/2, 10. + G.ROOM.T.h/2 - SC_scale*G.CARD_H/2, SC_scale*G.CARD_W, SC_scale*G.CARD_H, G.P_CARDS.empty, chosencard)
  end
end
'''
match_indent = true


# Replace start menu logo with Pokermon
[[patches]]
[patches.pattern]
target = "game.lua"
pattern = '''
G.SPLASH_LOGO = Sprite(0, 0, 
    13*SC_scale, 
    13*SC_scale*(G.ASSET_ATLAS["balatro"].py/G.ASSET_ATLAS["balatro"].px),
    G.ASSET_ATLAS["balatro"], {x=0,y=0})
'''
position = "after"
payload = '''
    if pokermon_config.pokemon_title then
      local poke_logo = pokermon_config.pokemon_aprilfools and "poke_smeargle_logo" or "poke_logo"
      G.SPLASH_LOGO = Sprite(0, 0, 
          13/333*389*SC_scale, 
          13/333*389*SC_scale*(G.ASSET_ATLAS[poke_logo].py/G.ASSET_ATLAS[poke_logo].px),
          G.ASSET_ATLAS[poke_logo], {x=0.0,y=0})
    end
'''
match_indent = true
overwrite = true

#Tutorial Functionality
[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = "local row_dollars_chips = G.HUD:get_UIE_by_ID('row_dollars_chips')"
position = "at"
payload = "local row_dollars_chips = G.HUD and G.HUD:get_UIE_by_ID('row_dollars_chips')"
match_indent = true